import { useEffect, useMemo, useRef, useState } from "preact/hooks";
import { applyCalculations } from "../calculations/calculationEngine";
import { CalculationSpecification } from "../calculations/calculationTypes";
import { HyperPbiConfig, parseConfig } from "../config/hyperpbiConfig";
import { applyConfigToData } from "../data/applyConfig";
import { NormalizedData } from "../data/normalizeData";
import { GeocodeResult } from "../providers/providerTypes";
import { HyperPbiRoot } from "../render/HyperPbiRoot";
import { DashboardComponent, HyperPbiSchema } from "../schema/hyperpbiSchema";
import { migrateSchema } from "../schema/schemaMigrations";
import { migrateFieldReferences } from "../schema/migrateFieldReferences";
import { validateReferences } from "../schema/validateReferences";
import { validateSchema } from "../schema/validateSchema";
import { RuntimeSettings } from "../settings";
import { parseJson } from "../utils/safeJson";
import { AiPromptTab } from "./ai/AiPromptTab";
import { CalculationsTab } from "./CalculationsTab";
import { CodeEditor } from "./CodeEditor";
import { DataPreview } from "./DataPreview";
import { FieldsPanel } from "./FieldsPanel";
import { HelpDocsPanel } from "./HelpDocsPanel";
import { InteractionsPanel } from "./InteractionsPanel";
import { MapServicesPanel } from "./MapServicesPanel";
import { StudioSettings } from "./StudioSettings";
import { SkillTab } from "./SkillTab";
import { defaultStudioLayout, parseStudioLayout, StudioLayoutPreference } from "./studioLayout";
import { copyText } from "./textActions";
import { createInteractionDiagnostics, ExternalSelectionFailureReason, ExternalSelectionResult, InteractionDetails, InteractionDiagnostics } from "../powerbi/interactionDiagnostics";
import { sanitizeCss } from "../security/sanitizeCss";
import { sanitizeHtml } from "../security/sanitizeHtml";
import { RuntimeConfigTab } from "./config/RuntimeConfigTab";
import { ExternalFilterResult } from "../powerbi/externalFilters";
import { FilterOperator } from "../schema/hyperpbiSchema";

type EditorTab="specification"|"config"|"ai"|"skill"|"calculations"|"mapServices"|"settings"|"interactions"|"help";
type BottomTab="data"|"fields"|"logs"|"errors"|"mapServices"|"geocode"|"interactions";
interface StudioLog{level:"info"|"error"|"success";message:string;timestamp?:string;}
interface ValidationResult{schema?:HyperPbiSchema;config?:HyperPbiConfig;data?:NormalizedData;errors:string[];warnings:string[];}

function sanitizerWarnings(schema:HyperPbiSchema,config:HyperPbiConfig):string[]{
    const warnings=sanitizeCss(`${schema.styles?.globalCss??""}\n${schema.css??""}`,"#studio-preview",{mode:config.security?.cssMode}).warnings.map(warning=>`Sanitizer: ${warning}`);
    const visit=(component:DashboardComponent,path:string)=>{if(component.css)warnings.push(...sanitizeCss(component.css,`[data-hp-id="studio"]`,{mode:config.security?.cssMode}).warnings.map(warning=>`${path}: ${warning}`));if("html" in component&&component.html)warnings.push(...sanitizeHtml(component.html,{mode:config.security?.htmlMode}).warnings.map(warning=>`${path}: ${warning}`));Object.entries(component.slots??{}).forEach(([name,html])=>warnings.push(...sanitizeHtml(html,{mode:config.security?.htmlMode}).warnings.map(warning=>`${path} slot ${name}: ${warning}`)));if("children" in component)component.children?.forEach((child,index)=>visit(child,`${path}/children/${index}`));if("tabs" in component)component.tabs.forEach((tab,index)=>(tab.children??tab.components??tab.content??[]).forEach((child,childIndex)=>visit(child,`${path}/tabs/${index}/${childIndex}`)));if("chart" in component)visit(component.chart,`${path}/chart`);};
    [schema.toolbar??[],schema.leftPanel??[],schema.components,schema.rightPanel??[]].forEach((items,group)=>items.forEach((component,index)=>visit(component,`Component ${group}/${index}`)));
    return Array.from(new Set(warnings));
}

function validateDraft(specification:string,configuration:string,data:NormalizedData):ValidationResult{
    const errors:string[]=[];const warnings:string[]=[];const parsed=parseJson(specification);if(parsed.error)errors.push(`Specification JSON: ${parsed.error}`);const validated=parsed.value?validateSchema(migrateFieldReferences(migrateSchema(parsed.value),data.fields)):undefined;if(validated&&!validated.valid)errors.push(...validated.errors.map(error=>`Specification: ${error}`));const config=parseConfig(configuration);errors.push(...config.errors);if(!validated?.schema||!config.config)return{schema:validated?.schema,config:config.config,errors,warnings};warnings.push(...sanitizerWarnings(validated.schema,config.config));const calculated=applyCalculations(data,validated.schema.calculations);errors.push(...calculated.errors.map(error=>`Calculation: ${error}`));warnings.push(...calculated.warnings);const configured=applyConfigToData(calculated.data,config.config);warnings.push(...validateReferences(validated.schema,configured));return{schema:validated.schema,config:config.config,data:configured,errors,warnings};
}
function validateStructure(specification:string,configuration:string):{schema?:HyperPbiSchema;errors:string[]}{const errors:string[]=[];const parsed=parseJson(specification);if(parsed.error)errors.push(`Specification JSON: ${parsed.error}`);const validated=parsed.value?validateSchema(migrateSchema(parsed.value)):undefined;if(validated&&!validated.valid)errors.push(...validated.errors.map(error=>`Specification: ${error}`));errors.push(...parseConfig(configuration).errors);return{schema:validated?.schema,errors};}

export function HyperPbiStudio({instanceId,data,settings,initialSpecification,initialConfiguration,initialLayout,onSave,onDraftChange,onLayoutChange,selectionIdentityCount=0,hostAllowsInteractions=false,initialInteractionDiagnostics,selectExternal:externalSelect=()=>({sent:false,reason:"component did not call selectExternal"}),clearExternal:externalClear=()=>({sent:false,reason:"component did not call selectExternal"}),applyExternalFilter:externalFilter=()=>({sent:false,reason:"component did not call selectExternal"}),clearExternalFilter:externalFilterClear=()=>({sent:false,reason:"component did not call selectExternal"}),initialEditorTab="ai",webAccessAvailable=false}:{instanceId:string;data:NormalizedData;settings:RuntimeSettings;initialSpecification:string;initialConfiguration:string;initialLayout?:string;onSave:(specification:string,configuration:string)=>void;onDraftChange?:(specification:string,configuration:string)=>void;onLayoutChange?:(layout:string)=>void;selectionIdentityCount?:number;hostAllowsInteractions?:boolean;initialInteractionDiagnostics?:InteractionDiagnostics;selectExternal?:(indices:number[],multiSelect?:boolean,details?:InteractionDetails)=>ExternalSelectionResult;clearExternal?:(details?:InteractionDetails)=>ExternalSelectionResult;applyExternalFilter?:(field:string,operator:FilterOperator,value:unknown,details?:InteractionDetails)=>ExternalFilterResult;clearExternalFilter?:(details?:InteractionDetails)=>ExternalFilterResult;initialEditorTab?:EditorTab;webAccessAvailable?:boolean}){
    const [specification,setSpecification]=useState(initialSpecification);const [configuration,setConfiguration]=useState(initialConfiguration);const [editorTab,setEditorTab]=useState<EditorTab>(initialEditorTab);const [bottomTab,setBottomTab]=useState<BottomTab>("data");
    const [logs,setLogs]=useState<StudioLog[]>([{level:"info",message:"Builder ready. Describe the dashboard, copy the prompt, paste the AI response, validate, preview, and save.",timestamp:new Date().toISOString()}]);const [errors,setErrors]=useState<string[]>([]);const [warnings,setWarnings]=useState<string[]>([]);const [preview,setPreview]=useState<{schema:HyperPbiSchema;config:HyperPbiConfig;data:NormalizedData}>();const [geocodeResults,setGeocodeResults]=useState<GeocodeResult[]>([]);const [layout,setLayout]=useState<StudioLayoutPreference>(()=>initialLayout?parseStudioLayout(initialLayout):defaultStudioLayout);const [interactionDiagnostics,setInteractionDiagnostics]=useState<InteractionDiagnostics>(()=>initialInteractionDiagnostics??createInteractionDiagnostics(settings.enableInteractions,hostAllowsInteractions,selectionIdentityCount));const workbenchRef=useRef<HTMLDivElement>(null);
    const dirty=specification!==initialSpecification||configuration!==initialConfiguration;const structure=useMemo(()=>validateStructure(specification,configuration),[specification,configuration]);const status=structure.errors.length?"Invalid":dirty?"Unsaved":preview?"Ready":"Saved";
    useEffect(()=>onDraftChange?.(specification,configuration),[specification,configuration]);
    const appendLog=(message:string,level:StudioLog["level"]="info")=>setLogs(current=>[...current.slice(-199),{message,level,timestamp:new Date().toISOString()}]);
    const updateInteraction=(indices:number[],details:InteractionDetails,result:ExternalSelectionResult)=>setInteractionDiagnostics(current=>({...current,externalInteractionEnabled:settings.enableInteractions,hostAllowsInteractions,selectionIdentityCount,lastClickedComponentId:details.componentId,lastClickedComponentType:details.componentType,lastClickedField:details.field,lastClickedValue:details.value,lastResolvedSourceRowCount:details.matchedRowCount??indices.length,lastSelectedSourceRowIndices:indices.slice(0,25),externalMode:details.externalMode??"selection",filterSent:false,selectionSent:result.sent,externalSelectionSent:result.sent,filterTargetTable:undefined,filterTargetColumn:undefined,reasonExternalSelectionNotSent:result.sent?undefined:result.reason}));
    const selectExternal=(indices:number[],multiSelect=false,details:InteractionDetails={})=>{const result=externalSelect(indices,multiSelect,details);updateInteraction(indices,details,result);return result;};
    const clearExternal=(details:InteractionDetails={})=>{const result=externalClear(details);updateInteraction([],details,result);return result;};
    const updateFilter=(details:InteractionDetails,result:ExternalFilterResult)=>setInteractionDiagnostics(current=>({...current,externalInteractionEnabled:settings.enableInteractions,hostAllowsInteractions,selectionIdentityCount,lastClickedComponentId:details.componentId,lastClickedComponentType:details.componentType,lastClickedField:details.field,lastClickedValue:details.value,lastResolvedSourceRowCount:details.matchedRowCount??0,lastSelectedSourceRowIndices:[],externalMode:"filter",filterSent:result.sent,selectionSent:false,externalSelectionSent:false,filterTargetTable:result.target?.table,filterTargetColumn:result.target?.column,reasonExternalSelectionNotSent:result.sent?undefined:result.reason}));
    const applyExternalFilter=(field:string,operator:FilterOperator,value:unknown,details:InteractionDetails={})=>{const result=externalFilter(field,operator,value,details);updateFilter({...details,field},result);return result;};
    const clearExternalFilter=(details:InteractionDetails={})=>{const result=externalFilterClear(details);updateFilter(details,result);return result;};
    const reportInteraction=(details:InteractionDetails,reason:ExternalSelectionFailureReason="component did not call selectExternal",indices:number[]=[])=>updateInteraction(indices,details,{sent:false,reason});
    const validate=()=>{try{const result=validateDraft(specification,configuration,data);setErrors(result.errors);setWarnings(result.warnings);if(result.errors.length){result.errors.forEach(message=>appendLog(message,"error"));setBottomTab("errors");return result;}appendLog(`Validation passed with ${result.warnings.length} warning(s).`,"success");if(result.warnings.length)result.warnings.forEach(message=>appendLog(message));setBottomTab(result.warnings.length?"errors":"logs");return result;}catch(error){const message=`Validation failed unexpectedly: ${error instanceof Error?error.message:String(error)}`;setErrors([message]);setWarnings([]);appendLog(message,"error");setBottomTab("errors");return{errors:[message],warnings:[]};}};
    const run=(candidate=specification,candidateConfig=configuration):boolean=>{try{const result=validateDraft(candidate,candidateConfig,data);setErrors(result.errors);setWarnings(result.warnings);if(result.errors.length||!result.schema||!result.config||!result.data){result.errors.forEach(message=>appendLog(message,"error"));setBottomTab("errors");return false;}setPreview({schema:result.schema,config:result.config,data:result.data});appendLog(`Rendered ${result.data.rows.length.toLocaleString()} rows with ${result.warnings.length} warning(s).`,"success");if(result.warnings.length)setBottomTab("errors");return true;}catch(error){const message=`Render failed safely: ${error instanceof Error?error.message:String(error)}`;setErrors([message]);setWarnings([]);appendLog(message,"error");setBottomTab("errors");return false;}};
    const save=()=>{const result=validate();if(!result.errors.length&&result.schema&&result.config&&run())onSave(specification,configuration);};
    const formatActive=()=>{const target=editorTab==="config"?"config":"specification";try{if(target==="config")setConfiguration(JSON.stringify(JSON.parse(configuration),null,2));else setSpecification(JSON.stringify(JSON.parse(specification),null,2));setEditorTab(target);appendLog(`Formatted ${target} JSON.`,"success");}catch(error){const message=`Cannot format invalid ${target} JSON: ${error instanceof Error?error.message:String(error)}`;setErrors([message]);appendLog(message,"error");setBottomTab("errors");}};
    const applyAi=(json:string,merge:boolean,configJson?:string)=>{if(configJson)setConfiguration(configJson);if(!merge){setSpecification(json);if(layout.advanced)setEditorTab("specification");return;}try{const current=JSON.parse(specification) as HyperPbiSchema;const incoming=JSON.parse(json) as HyperPbiSchema;setSpecification(JSON.stringify({...current,...incoming,components:[...current.components,...incoming.components],calculations:{fields:[...(current.calculations?.fields??[]),...(incoming.calculations?.fields??[])],metrics:[...(current.calculations?.metrics??[]),...(incoming.calculations?.metrics??[])]}},null,2));if(layout.advanced)setEditorTab("specification");}catch(error){appendLog(`Merge failed: ${error instanceof Error?error.message:String(error)}`,"error");}};
    const updateCalculations=(calculations:CalculationSpecification)=>{const parsed=parseJson(specification);if(parsed.value&&typeof parsed.value==="object")setSpecification(JSON.stringify({...parsed.value as object,calculations},null,2));};
    const parsedConfig=parseConfig(configuration).config;const changeConfig=(config:HyperPbiConfig)=>setConfiguration(JSON.stringify(config,null,2));const showBottom=layout.advanced&&layout.bottomOpen||!layout.advanced&&Boolean(errors.length||warnings.length);
    const tab=(id:EditorTab,label:string)=><button class={editorTab===id?"active":""} onClick={()=>setEditorTab(id)}>{label}</button>;
    const persistLayout=(next:StudioLayoutPreference)=>{setLayout(next);onLayoutChange?.(JSON.stringify(next));};
    const startMainResize=(event:preact.JSX.TargetedPointerEvent<HTMLDivElement>)=>{event.preventDefault();const host=workbenchRef.current;if(!host)return;const rect=host.getBoundingClientRect();const vertical=settings.editor.previewPosition==="bottom"||rect.width<780;const move=(pointer:PointerEvent)=>{const raw=vertical?(pointer.clientY-rect.top)/rect.height*100:(pointer.clientX-rect.left)/rect.width*100;setLayout(current=>({...current,editorPercent:Math.min(75,Math.max(25,raw))}));};const up=()=>{document.removeEventListener("pointermove",move);document.removeEventListener("pointerup",up);setLayout(current=>{onLayoutChange?.(JSON.stringify(current));return current;});};document.addEventListener("pointermove",move);document.addEventListener("pointerup",up);};
    const startBottomResize=(event:preact.JSX.TargetedPointerEvent<HTMLDivElement>)=>{event.preventDefault();const startY=event.clientY;const startHeight=layout.bottomHeight;const maxHeight=Math.max(180,window.innerHeight*.6);const move=(pointer:PointerEvent)=>setLayout(current=>({...current,bottomHeight:Math.min(maxHeight,Math.max(120,startHeight+(startY-pointer.clientY)))}));const up=()=>{document.removeEventListener("pointermove",move);document.removeEventListener("pointerup",up);setLayout(current=>{onLayoutChange?.(JSON.stringify(current));return current;});};document.addEventListener("pointermove",move);document.addEventListener("pointerup",up);};
    const bottomOutput=()=>{if(bottomTab==="data")return JSON.stringify((preview?.data??data).rows,null,2);if(bottomTab==="fields")return JSON.stringify((preview?.data??data).fields,null,2);if(bottomTab==="logs")return logs.map(log=>`${log.timestamp??""} ${log.level.toUpperCase()} ${log.message}`).join("\n");if(bottomTab==="errors")return [...errors,...warnings].join("\n")||"No validation issues.";if(bottomTab==="geocode")return JSON.stringify(geocodeResults,null,2);if(bottomTab==="mapServices")return JSON.stringify(parsedConfig?.providers??{},null,2);return JSON.stringify(interactionDiagnostics,null,2);};
    const copyBottom=async()=>{const copied=await copyText(bottomOutput());appendLog(copied?`Copied ${bottomTab} output.`:`Copy was blocked by the Power BI host.`,copied?"success":"error");};
    const toggleAdvanced=()=>{const next={...layout,advanced:!layout.advanced};persistLayout(next);if(layout.advanced)setEditorTab("ai");};
    const bottomTabs:Array<[BottomTab,string]>=layout.advanced?[["data","Data"],["fields","Fields"],["logs","Logs"],["errors",`Issues ${errors.length+warnings.length||""}`],["mapServices","Map Services"],["geocode",`Geocode ${geocodeResults.length||""}`],["interactions","Interactions"]]:[["data","Data preview"],["fields","Fields"],["errors",`Issues ${errors.length+warnings.length||""}`]];
    return <div class={`hp-studio hp-studio-${settings.theme.mode} hp-preview-${settings.editor.previewPosition} ${layout.advanced?"hp-studio-advanced":"hp-studio-simple"}`}>
        <header class="hp-studio-header"><div class="hp-header-left"><div class="hp-studio-brand"><span>H</span><div><strong>HyperPBI Builder</strong><small class={`hp-studio-state hp-state-${status.toLowerCase()}`}>{status}</small></div></div></div><div class="hp-studio-actions">{layout.advanced&&<><button type="button" onClick={formatActive}>Format JSON</button><button type="button" onClick={()=>validate()}>Validate</button><button type="button" class="hp-run-button" onClick={()=>run()}>Validate & Preview</button><button type="button" onClick={()=>persistLayout({...layout,bottomOpen:!layout.bottomOpen})}>{layout.bottomOpen?"Hide Data & Fields":"Data & Fields"}</button></>}<button type="button" class="hp-advanced-toggle" onClick={toggleAdvanced}>{layout.advanced?"Simple mode":"Advanced"}</button><button type="button" onClick={()=>setEditorTab("help")}>Help</button><button class={`hp-save-return ${preview?"is-ready":""}`} type="button" disabled={!layout.advanced&&!preview} onClick={save}>Save & return</button></div></header>
        <nav class="hp-studio-tabs">{tab("ai",layout.advanced?"AI builder":"Guided builder")}{!layout.advanced&&tab("help","How it works")}{layout.advanced&&<>{tab("specification","JSON")}{tab("config","Runtime config")}{tab("skill","AI skill")}{tab("calculations","Calculations")}{tab("mapServices","Map services")}{tab("settings","Field mapping")}{tab("interactions","Interactions")}{tab("help","Documentation")}</>}</nav>
        <div ref={workbenchRef} class="hp-studio-workbench" style={{"--hp-editor-size":`${layout.editorPercent}%`}}><section class="hp-studio-editor-pane">{editorTab==="specification"&&<CodeEditor value={specification} onChange={setSpecification} theme={settings.theme.mode} fontSize={settings.editor.fontSize} wordWrap={settings.editor.wordWrap} ariaLabel="HyperPBI specification JSON"/>}{editorTab==="config"&&<RuntimeConfigTab data={data} configuration={configuration} onChange={setConfiguration} theme={settings.theme.mode} fontSize={settings.editor.fontSize} wordWrap={settings.editor.wordWrap}/>} {editorTab==="settings"&&<StudioSettings data={data} configuration={configuration} onChange={setConfiguration}/>} {editorTab==="ai"&&<AiPromptTab data={data} currentSpecification={specification} onApply={applyAi} onPreview={(json,configJson)=>run(json,configJson??configuration)} previewReady={Boolean(preview)} diagnostics={interactionDiagnostics}/>} {editorTab==="skill"&&<SkillTab data={data}/>} {editorTab==="calculations"&&<CalculationsTab data={data} schema={structure.schema} onChange={updateCalculations} theme={settings.theme.mode} fontSize={settings.editor.fontSize} wordWrap={settings.editor.wordWrap}/>} {editorTab==="mapServices"&&parsedConfig&&<MapServicesPanel data={data} config={parsedConfig} onChange={changeConfig} onResults={results=>setGeocodeResults(current=>results.length>1?results:[...current.slice(-199),...results])} onLog={appendLog} webAccessAvailable={webAccessAvailable}/>} {editorTab==="interactions"&&<InteractionsPanel diagnostics={interactionDiagnostics}/>} {editorTab==="help"&&<HelpDocsPanel/>}</section>
            {settings.editor.previewPosition!=="hidden"&&<><div class="hp-main-resize-handle" role="separator" aria-label="Resize builder and preview" onPointerDown={startMainResize}/><section class="hp-studio-preview"><div class="hp-pane-label">Live preview</div>{preview?<HyperPbiRoot instanceId={`${instanceId}-preview`} schema={preview.schema} data={preview.data} settings={settings} config={preview.config} referenceWarnings={validateReferences(preview.schema,preview.data)} renderMs={0} selectExternal={selectExternal} clearExternal={clearExternal} applyExternalFilter={applyExternalFilter} clearExternalFilter={clearExternalFilter} reportInteraction={reportInteraction} webAccessAvailable={webAccessAvailable}/>:<div class="hp-preview-empty"><span>◇</span><strong>Your validated preview will appear here</strong><p>Copy the AI prompt, paste the AI response, then select Validate & Preview.</p>{layout.advanced&&<button class="hp-primary-action hp-preview-validate" type="button" onClick={()=>run()}>Validate & Preview</button>}</div>}</section></>}
        </div>
        {showBottom&&<section class="hp-studio-bottom" style={{height:`${layout.bottomHeight}px`}}><div class="hp-bottom-resize-handle" role="separator" aria-label="Resize data panel" onPointerDown={startBottomResize}/><nav>{bottomTabs.map(([id,label])=><button class={bottomTab===id?"active":""} onClick={()=>setBottomTab(id)}>{label}</button>)}<span/><button type="button" onClick={()=>void copyBottom()}>Copy output</button><button type="button" onClick={()=>persistLayout({...layout,bottomOpen:false})}>Close</button></nav><div class="hp-bottom-content">{bottomTab==="data"&&<DataPreview data={preview?.data??data}/>} {bottomTab==="fields"&&<FieldsPanel data={preview?.data??data}/>} {bottomTab==="logs"&&<div class="hp-log-view">{logs.map(log=><div class={`hp-log-${log.level}`}><span>{log.level.toUpperCase()}</span><time>{log.timestamp?.slice(11,19)}</time><div>{log.message}</div></div>)}</div>} {bottomTab==="errors"&&<div class="hp-errors-panel"><header><strong>Issues</strong><button type="button" onClick={()=>void copyBottom()}>Copy Issues</button></header>{errors.length||warnings.length?<><ul>{errors.map(error=><li>{error}</li>)}</ul><ul>{warnings.map(warning=><li>{warning}</li>)}</ul></>:<div class="hp-ready-state">✓ No validation issues</div>}</div>} {bottomTab==="mapServices"&&<div class="hp-bottom-summary"><strong>{parsedConfig?.providers?.mode??"core"} mode</strong><span>Basemap: {parsedConfig?.providers?.basemap?.provider??"none"}</span><span>Geocoder: {parsedConfig?.providers?.geocoder?.provider??"none"}</span></div>} {bottomTab==="geocode"&&<div class="hp-geocode-table"><table><thead><tr><th>Address</th><th>Status</th><th>Latitude</th><th>Longitude</th><th>Provider</th><th>Cache</th><th>Error</th></tr></thead><tbody>{geocodeResults.map(result=><tr><td>{result.sourceAddress}</td><td>{result.status}</td><td>{result.latitude??"—"}</td><td>{result.longitude??"—"}</td><td>{result.provider}</td><td>{result.cacheHit?"Yes":"No"}</td><td>{result.error??""}</td></tr>)}</tbody></table></div>} {bottomTab==="interactions"&&<InteractionsPanel diagnostics={interactionDiagnostics}/>}</div></section>}
        <footer class="hp-studio-status"><span>HyperPBI Schema 1.0</span><span>{status}</span><span>{data.rows.length.toLocaleString()} rows loaded{data.loadStatus?.moreRowsAvailable?" · more available":""}</span><span>{Object.keys(data.fields).length} fields</span><span>{selectionIdentityCount.toLocaleString()} selection IDs</span></footer>
    </div>;
}
