import type { EChartsCoreOption } from "echarts/core";
import { aggregateValue } from "../../../data/aggregations";
import type { AdvancedChartComponent, CategoryChartComponent, GaugeChartComponent, ScatterChartComponent } from "../../../schema/hyperpbiSchema";
import { categoricalColor } from "../../../utils/colors";
import { mergeSafeEChartOptions } from "../safeEChartOptions";
import type { ChartAdapter } from "./types";
import { baseOption, groupRows, scaleScatterPointSizes, semanticResult, sourceIndices } from "./shared";

export const categoryAdapter: ChartAdapter<CategoryChartComponent> = {
    type:"barChart", fields:component=>[component.category,component.measure].filter((field):field is string=>Boolean(field)),
    build(component,rows,context){const grouped=component.category?groupRows(rows,component.category,component.measure,component.aggregation):[];const horizontal=component.type==="horizontalBarChart";const pie=component.type==="pieChart"||component.type==="donutChart";const bindings=grouped.map((group,dataIndex)=>({seriesIndex:0,dataIndex,sourceRowIndices:sourceIndices(group.rows,context),field:component.category,value:group.rawKey}));let option:EChartsCoreOption;
        if(pie)option={...baseOption(context),legend:{bottom:0},series:[{type:"pie",selectedMode:"multiple",radius:component.type==="donutChart"?["45%","72%"]:"72%",data:grouped.map(item=>({name:item.key,value:item.value,itemStyle:{color:categoricalColor(item.key)}})),label:{show:grouped.length<=12}}]};
        else if(component.type==="heatmap")option={...baseOption(context),xAxis:{type:"category",data:grouped.map(item=>item.key)},yAxis:{type:"category",data:[component.measure??"Value"]},visualMap:{min:0,max:Math.max(1,...grouped.map(item=>item.value)),orient:"horizontal",bottom:0},series:[{type:"heatmap",selectedMode:"multiple",data:grouped.map((item,index)=>[index,0,item.value])}]};
        else {const type=component.type==="lineChart"||component.type==="areaChart"?"line":"bar";option={...baseOption(context),xAxis:horizontal?{type:"value"}:{type:"category",data:grouped.map(item=>item.key),axisLabel:{hideOverlap:true}},yAxis:horizontal?{type:"category",data:grouped.map(item=>item.key),axisLabel:{hideOverlap:true}}:{type:"value"},series:[{type,selectedMode:"multiple",data:grouped.map(item=>item.value),areaStyle:component.type==="areaChart"?{}:undefined,smooth:component.type==="lineChart"||component.type==="areaChart",itemStyle:{color:context.theme.primary}}]};}
        return semanticResult(option,component,bindings);
    }
};

export const scatterAdapter: ChartAdapter<ScatterChartComponent>={type:"scatterChart",fields:component=>[component.x,component.y,component.pointSize].filter((field):field is string=>Boolean(field)),build(component,rows,context){const valid=rows.filter(row=>Number.isFinite(Number(row[component.x??""]))&&Number.isFinite(Number(row[component.y??""])));const sizes=component.pointSize?scaleScatterPointSizes(valid.map(row=>Number(row[component.pointSize!]))):valid.map(()=>12);return semanticResult({...baseOption(context),xAxis:{type:"value"},yAxis:{type:"value"},series:[{type:"scatter",selectedMode:"multiple",data:valid.map((row,index)=>({value:[Number(row[component.x??""]),Number(row[component.y??""])],symbolSize:sizes[index]}))}]},component,valid.map((row,dataIndex)=>({seriesIndex:0,dataIndex,sourceRowIndices:sourceIndices([row],context),field:component.interaction?.field,value:component.interaction?.field?row[component.interaction.field]:undefined})));}};
export const gaugeAdapter: ChartAdapter<GaugeChartComponent>={type:"gauge",fields:component=>[component.measure].filter((field):field is string=>Boolean(field)),build(component,rows,context){const value=Number(aggregateValue(rows,component.measure,component.aggregation??"avg")??0);return semanticResult({...baseOption(context),series:[{type:"gauge",selectedMode:"multiple",data:[{value,name:component.title}],detail:{fontSize:18},progress:{show:true}}]},component,[{seriesIndex:0,dataIndex:0,sourceRowIndices:sourceIndices(rows,context),field:component.measure,value}]);}};
export const advancedAdapter: ChartAdapter<AdvancedChartComponent>={type:"advancedChart",fields:component=>[component.category,component.measure,component.x,component.y,component.pointSize].filter((field):field is string=>Boolean(field)),build(component,rows,context){const limited=rows.slice(0,component.maxDataRows??30000);const option=mergeSafeEChartOptions({...baseOption(context),dataset:{source:limited}},component.options);const series=Array.isArray((option.option as {series?:unknown}).series)?(option.option as {series:unknown[]}).series.length:1;const bindings=Array.from({length:Math.max(1,series)},(_,seriesIndex)=>limited.map((row,dataIndex)=>({seriesIndex,dataIndex,sourceRowIndices:sourceIndices([row],context),field:component.category,value:component.category?row[component.category]:undefined}))).flat();return{option:option.option,bindings,warnings:option.warnings};}};
