import { aggregateValue } from "../../../data/aggregations";
import type { DataRow } from "../../../data/normalizeData";
import type { TreemapChartComponent } from "../../../schema/hyperpbiSchema";
import type { ChartAdapter, ChartDatumBinding } from "./types";
import { baseOption, semanticResult, sourceIndices } from "./shared";

interface TreeNode { name:string; valueKey:string; field:string; rows:DataRow[]; children:Map<string,TreeNode>; }
export const treemapAdapter: ChartAdapter<TreemapChartComponent>={type:"treemapChart",fields:component=>[...component.pathFields,component.valueField,component.labelField].filter((field):field is string=>Boolean(field)),build(component,rows,context){const root:TreeNode={name:"root",valueKey:"root",field:component.pathFields[0]??"",rows:[],children:new Map()};const depth=Math.min(component.maxDepth??component.pathFields.length,component.pathFields.length);for(const row of rows){let node=root;node.rows.push(row);for(const [level,field] of component.pathFields.slice(0,depth).entries()){const valueKey=String(row[field]??"(Blank)");const name=level===depth-1&&component.labelField?String(row[component.labelField]??valueKey):valueKey;let child=node.children.get(valueKey);if(!child){child={name,valueKey,field,rows:[],children:new Map()};node.children.set(valueKey,child);}child.rows.push(row);node=child;}}
    const bindings:ChartDatumBinding[]=[];let dataIndex=0;const build=(node:TreeNode):Record<string,unknown>=>{const ownIndex=dataIndex++;bindings.push({seriesIndex:0,dataIndex:ownIndex,dataType:"node",sourceRowIndices:sourceIndices(node.rows,context),field:node.field,value:node.valueKey});return{name:node.name,value:Number(aggregateValue(node.rows,component.valueField,component.aggregation??"sum")??0),children:node.children.size?Array.from(node.children.values()).map(build):undefined};};const data=Array.from(root.children.values()).map(build);return semanticResult({...baseOption(context),series:[{type:"treemap",selectedMode:"multiple",roam:false,nodeClick:false,data,label:{show:true}}]},component,bindings);}};
