import type { WaterfallChartComponent } from "../../../schema/hyperpbiSchema";
import type { ChartAdapter, ChartDatumBinding } from "./types";
import { baseOption, groupRows, intentColor, semanticResult, sourceIndices } from "./shared";

export const waterfallAdapter: ChartAdapter<WaterfallChartComponent>={type:"waterfallChart",fields:component=>[component.category,component.measure],build(component,rows,context){const groups=groupRows(rows,component.category,component.measure,component.aggregation??"sum");const names:string[]=[];const base:number[]=[];const bars:Array<Record<string,unknown>>=[];const bindings:ChartDatumBinding[]=[];let running=0;
    if(component.showStart!==false){names.push("Start");base.push(0);bars.push({value:0,rawValue:0,itemStyle:{color:intentColor(component.totalIntent,context,context.theme.primary)}});bindings.push({seriesIndex:1,dataIndex:0,sourceRowIndices:[],field:component.category,value:"Start"});}
    for(const group of groups){const before=running;running+=group.value;const dataIndex=names.length;names.push(group.key);base.push(Math.min(before,running));bars.push({value:Math.abs(group.value),rawValue:group.value,itemStyle:{color:group.value>=0?intentColor(component.positiveIntent,context,context.theme.success):intentColor(component.negativeIntent,context,context.theme.danger)},label:{show:true,formatter:group.value>=0?`+${group.value}`:String(group.value)}});bindings.push({seriesIndex:1,dataIndex,sourceRowIndices:sourceIndices(group.rows,context),field:component.category,value:group.rawKey});}
    if(component.showEnd!==false){const dataIndex=names.length;names.push("Total");base.push(Math.min(0,running));bars.push({value:Math.abs(running),rawValue:running,itemStyle:{color:intentColor(component.totalIntent,context,context.theme.primary)},label:{show:true,formatter:String(running)}});bindings.push({seriesIndex:1,dataIndex,sourceRowIndices:sourceIndices(rows,context),field:component.measure,value:running});}
    return semanticResult({...baseOption(context),tooltip:{trigger:"item",confine:true,formatter:(params:{data?:{rawValue?:unknown};name?:string})=>`${params.name??""}: ${params.data?.rawValue??""}`},xAxis:{type:"category",data:names},yAxis:{type:"value"},series:[{type:"bar",stack:"waterfall",silent:true,itemStyle:{color:"transparent"},data:base},{type:"bar",stack:"waterfall",selectedMode:"multiple",data:bars}]},component,bindings);}};
