export type ComponentCategory = "Layout" | "Controls" | "Navigation" | "Display" | "Charts" | "Tables" | "Maps" | "Custom components" | "Advanced components";

export interface ComponentCapability {
    fields: boolean;
    calculations: boolean;
    css: boolean;
    slots: boolean;
    interactions: boolean;
    externalSelection: boolean;
    customHtml: boolean;
}

export interface ComponentMetadata {
    type: string;
    label: string;
    category: ComponentCategory;
    useWhen: string;
    level: "recommended" | "standard" | "advanced";
    capability: ComponentCapability;
}

const capabilities = (overrides: Partial<ComponentCapability> = {}): ComponentCapability => ({ fields: false, calculations: false, css: true, slots: true, interactions: false, externalSelection: false, customHtml: false, ...overrides });
const item = (type: string, label: string, category: ComponentCategory, useWhen: string, level: ComponentMetadata["level"] = "standard", override: Partial<ComponentCapability> = {}): ComponentMetadata => ({ type, label, category, useWhen, level, capability: capabilities(override) });

export const componentCatalog: ComponentMetadata[] = [
    item("grid", "Grid", "Layout", "Responsive 12-column dashboard sections", "recommended"), item("flex", "Flex row/column", "Layout", "Compact toolbars and flowing groups"), item("split", "Split layout", "Layout", "Two coordinated content regions"), item("section", "Section", "Layout", "Named content grouping", "recommended"), item("toolbar", "Toolbar", "Layout", "Compact controls above content"), item("leftPanel", "Left panel", "Layout", "Persistent filter rail"), item("rightPanel", "Right panel", "Layout", "Persistent details rail"), item("spacer", "Spacer", "Layout", "Small intentional separation", "advanced"), item("divider", "Divider", "Layout", "Subtle visual separation"),
    item("searchBox", "Search box", "Controls", "Search all visible row values", "recommended", { fields: true, interactions: true }), item("textInput", "Text input", "Controls", "Text field filtering", "standard", { fields: true, interactions: true }), item("numberInput", "Number input", "Controls", "Numeric thresholds", "standard", { fields: true, interactions: true }), item("slider", "Slider", "Controls", "Bounded numeric filtering", "standard", { fields: true, interactions: true }), item("select", "Select", "Controls", "Compact categorical filtering", "recommended", { fields: true, interactions: true }), item("multiSelect", "Multi-select", "Controls", "Filtering by several categories", "standard", { fields: true, interactions: true }), item("segmentedControl", "Segmented control", "Controls", "Two to seven high-frequency choices", "recommended", { fields: true, interactions: true, externalSelection: true }), item("toggle", "Toggle", "Controls", "Boolean state or view switch", "standard", { interactions: true }), item("button", "Button", "Controls", "Clear filters or open a view", "standard", { interactions: true }), item("buttonGroup", "Button group", "Controls", "Small action groups", "standard", { interactions: true }), item("filterChips", "Filter chips", "Controls", "Visible applied-filter summary", "recommended", { fields: true, interactions: true }), item("dateRange", "Date range", "Controls", "Start/end date filtering", "standard", { fields: true, interactions: true }),
    item("tabs", "Tabs", "Navigation", "Separate overview, map, and details", "recommended", { interactions: true }), item("collapsible", "Collapsible section", "Navigation", "Hide secondary content", "standard", { interactions: true }), item("accordion", "Accordion", "Navigation", "Compact grouped filters", "standard", { interactions: true }), item("drawer", "Drawer / slide-over", "Navigation", "Selected-record details without leaving context", "recommended", { fields: true, interactions: true }), item("filterDrawer", "Filter drawer", "Navigation", "On-demand compact filter controls", "recommended", { fields: true, interactions: true }), item("stepper", "Stepper", "Navigation", "Sequential app-style flows", "advanced", { interactions: true }),
    item("kpi", "KPI card", "Display", "One decision-critical number", "recommended", { fields: true, calculations: true }), item("metricGrid", "Metric grid", "Display", "Three to six summary metrics", "recommended", { fields: true, calculations: true }), item("infoCard", "Info card", "Display", "Short explanatory or record content", "standard", { fields: true }), item("statusBadge", "Status badge", "Display", "Compact status labeling", "standard", { fields: true }), item("progressBar", "Progress bar", "Display", "Progress toward a target", "standard", { fields: true, calculations: true }), item("alert", "Alert", "Display", "Actionable exception banner", "standard", { fields: true, calculations: true }), item("statList", "Stat list", "Display", "Compact label/value summary", "standard", { fields: true, calculations: true }), item("detailPanel", "Detail panel", "Display", "Selected-row fields, groups, badges, and copyable values", "recommended", { fields: true, interactions: true }), item("timeline", "Timeline / activity feed", "Display", "Operational history and status events", "recommended", { fields: true, interactions: true }),
    item("barChart", "Bar chart", "Charts", "Ranked category comparison", "recommended", { fields: true, calculations: true, interactions: true, externalSelection: true }), item("horizontalBarChart", "Horizontal bar", "Charts", "Long category labels", "recommended", { fields: true, calculations: true, interactions: true, externalSelection: true }), item("lineChart", "Line chart", "Charts", "Time or ordered trends", "recommended", { fields: true, calculations: true, interactions: true, externalSelection: true }), item("areaChart", "Area chart", "Charts", "Trend plus magnitude", "standard", { fields: true, calculations: true, interactions: true, externalSelection: true }), item("pieChart", "Pie chart", "Charts", "Few-part composition only", "standard", { fields: true, calculations: true, interactions: true, externalSelection: true }), item("donutChart", "Donut chart", "Charts", "Few-part composition with central space", "standard", { fields: true, calculations: true, interactions: true, externalSelection: true }), item("scatterChart", "Scatter chart", "Charts", "Relationship between two measures", "standard", { fields: true, calculations: true, interactions: true, externalSelection: true }), item("gauge", "Gauge", "Charts", "Single target attainment", "standard", { fields: true, calculations: true }), item("heatmap", "Heatmap", "Charts", "Dense intensity comparison", "standard", { fields: true, calculations: true, interactions: true }), item("smallMultiples", "Small multiples", "Charts", "Repeat one comparison across a split field", "recommended", { fields: true, calculations: true, interactions: true, externalSelection: true }),
    item("table", "Detail table", "Tables", "Row-level investigation and export-ready detail", "recommended", { fields: true, calculations: true, interactions: true, externalSelection: true }), item("matrix", "Matrix / pivot", "Tables", "Summarized row-by-column comparison", "recommended", { fields: true, calculations: true, interactions: true }),
    item("map", "Map", "Maps", "Spatial patterns and selectable features", "recommended", { fields: true, calculations: true, interactions: true, externalSelection: true }),
    item("text", "Text", "Custom components", "Safe plain text"), item("markdown", "Markdown", "Custom components", "Structured explanatory content"), item("html", "Sanitized HTML", "Custom components", "Branded static content", "advanced", { customHtml: true }), item("custom", "Custom HTML/CSS", "Custom components", "Safe app-like cards, lists, and slicers", "advanced", { fields: true, calculations: true, interactions: true, externalSelection: true, customHtml: true }),
    item("advancedChart", "Advanced ECharts", "Advanced components", "JSON-only radar, treemap, sankey, funnel, calendar, network, combo, or waterfall visuals", "advanced", { fields: true, calculations: true, interactions: true, externalSelection: true })
];

export const componentTypeNames = componentCatalog.map(component => component.type);
export const componentCategories: ComponentCategory[] = ["Layout", "Controls", "Navigation", "Display", "Charts", "Tables", "Maps", "Custom components", "Advanced components"];
export const componentsByCategory = (category: ComponentCategory): ComponentMetadata[] => componentCatalog.filter(component => component.category === category);
export const componentPromptReference = (): string => componentCategories.map(category => `${category}: ${componentsByCategory(category).map(component => `${component.type} (${component.useWhen})`).join("; ")}`).join("\n");

