import type { ComponentDescriptor } from "./componentDescriptors";

export const geolibreDescriptor: ComponentDescriptor = {
  type: "geolibre",
  label: "GeoLibre workspace",
  category: "Maps",
  maturity: "beta",
  complexity: "advanced",
  useWhen:
    "A report needs GeoLibre's authentic project-based GIS workspace, layer management, GIS styling, or advanced browser-safe geospatial formats",
  capabilities: {
    fields: true,
    calculations: false,
    css: true,
    slots: true,
    interactions: true,
    externalSelection: true,
    customHtml: false,
  },
  interaction: {
    defaultEnabled: true,
    naturalTrigger: "click",
    autoExternalMode: "selection",
  },
  schema: {
    required: ["type", "id"],
    allowed: [
      "type",
      "id",
      "dataset",
      "title",
      "subtitle",
      "span",
      "order",
      "responsive",
      "heightMode",
      "minHeight",
      "aspectRatio",
      "className",
      "hidden",
      "props",
      "style",
      "css",
      "slots",
      "data",
      "visibility",
      "interactions",
      "interaction",
      "ariaLabel",
      "icon",
      "variant",
      "size",
      "disabled",
      "tooltip",
      "uiAction",
      "height",
      "project",
      "powerBi",
      "runtime",
      "capabilityProfile",
    ],
  },
  fields: [
    { property: "interaction", requirement: "any", handler: "interaction" },
    { property: "powerBi", requirement: "any", handler: "geolibre-powerbi" },
  ],
  inspector: [
    { property: "dataset", label: "Default dataset", control: "dataset", group: "Data" },
    { property: "title", label: "Title", control: "text", group: "Identity" },
    { property: "span", label: "Span", control: "number", group: "Layout" },
    {
      property: "heightMode",
      label: "Height mode",
      control: "enum",
      options: ["fixed", "fill"],
      group: "Layout",
      help: "Use fill inside a bounded fill-height layout; otherwise GeoLibre uses the fixed height.",
    },
    { property: "height", label: "Fixed height", control: "number", group: "Layout" },
    {
      property: "powerBi",
      label: "Power BI layer bindings",
      control: "json",
      group: "Data",
      help: "Bind Field Manifest aliases to GeoLibre layers. Detailed GIS styling stays in the GeoLibre GUI.",
    },
    {
      property: "project",
      label: "GeoLibre project",
      control: "json",
      group: "Advanced",
      advanced: true,
      help: "Versioned, sanitized native GeoLibre project. Prefer editing it through the embedded workspace.",
    },
    {
      property: "runtime",
      label: "Runtime",
      control: "json",
      group: "Advanced",
      advanced: true,
    },
    {
      property: "capabilityProfile",
      label: "Capability profile",
      control: "enum",
      options: ["powerbi-embedded", "viewer"],
      group: "Advanced",
    },
    { property: "interaction", label: "Selection integration", control: "json", group: "Interaction" },
    { property: "ariaLabel", label: "Accessible label", control: "text", group: "Accessibility" },
  ],
  documentation: {
    summary:
      "Isolated GeoLibre 2.5.0 GIS workspace with native project persistence and identity-safe Power BI-backed GeoJSON layers.",
    accessibility: [
      "Give the workspace an ariaLabel and provide an adjacent table or summary for keyboard-first access to selected Power BI records.",
    ],
    relatedTypes: ["map", "table"],
  },
  example: {
    type: "geolibre",
    id: "gis_workspace",
    title: "GIS workspace",
    span: 12,
    heightMode: "fixed",
    height: 520,
    capabilityProfile: "powerbi-embedded",
    runtime: { channel: "managed", panels: "open", theme: "system" },
    powerBi: {
      layers: [
        {
          id: "locations",
          title: "Power BI locations",
          geometry: {
            latitudeField: "__latitude_field__",
            longitudeField: "__longitude_field__",
          },
        },
      ],
      selection: { enabled: true, externalHighlight: true, maxSelectionCount: 1000 },
    },
    interaction: {
      enabled: true,
      trigger: "click",
      internalMode: "highlight",
      internalScope: "all",
      externalMode: "selection",
      selectionMode: "replace",
      multiSelect: true,
    },
  },
  rendering: "direct",
  containers: [],
};
