import { getComponentDescriptor, type ComponentDescriptor } from "./componentDescriptors";

const sankey = getComponentDescriptor("sankeyChart");
if (!sankey) throw new Error("The networkGraph descriptor requires the sankeyChart base descriptor.");

const removedProperties = new Set(["valueField", "aggregation", "nodeAlign", "events", "drill"]);
const graphProperties = [
    "sourceLabelField",
    "targetLabelField",
    "sourceCategoryField",
    "targetCategoryField",
    "edgeLabelField",
    "edgeWeightField",
    "layout",
    "orientation",
    "roam",
    "draggable",
    "directed",
    "showLabels",
    "showEdgeLabels",
    "nodeSize",
    "repulsion",
    "edgeLength",
    "gravity",
    "levelGap",
    "nodeGap",
    "edgeWidth",
    "edgeOpacity",
    "edgeCurveness",
    "arrowSize",
    "maxNodes",
];

const additionalFields: ComponentDescriptor["fields"] = [
    { property: "sourceLabelField", requirement: "any", handler: "scalar" },
    { property: "targetLabelField", requirement: "any", handler: "scalar" },
    { property: "sourceCategoryField", requirement: "any", handler: "scalar" },
    { property: "targetCategoryField", requirement: "any", handler: "scalar" },
    { property: "edgeLabelField", requirement: "any", handler: "scalar" },
    { property: "edgeWeightField", requirement: "numeric", handler: "scalar" },
];

const additionalInspector: ComponentDescriptor["inspector"] = [
    { property: "sourceLabelField", label: "Source label field", control: "field", group: "Data" },
    { property: "targetLabelField", label: "Target label field", control: "field", group: "Data" },
    { property: "sourceCategoryField", label: "Source category field", control: "field", group: "Data" },
    { property: "targetCategoryField", label: "Target category field", control: "field", group: "Data" },
    { property: "edgeLabelField", label: "Edge label field", control: "field", group: "Data" },
    { property: "edgeWeightField", label: "Edge weight field", control: "field", group: "Data", help: "Optional numeric edge weight. Duplicate source-target rows are summed." },
    { property: "layout", label: "Graph layout", control: "enum", options: ["hybrid", "hierarchical", "force", "circular"], group: "Layout", help: "Hybrid is the calm default: hierarchy-aware spacing with fixed settled positions." },
    { property: "orientation", label: "Hierarchy orientation", control: "enum", options: ["horizontal", "vertical"], group: "Layout", help: "Applies to hybrid and hierarchical layouts." },
    { property: "levelGap", label: "Level gap", control: "number", group: "Layout", help: "Distance between hierarchy levels for hybrid and hierarchical layouts." },
    { property: "nodeGap", label: "Node gap", control: "number", group: "Layout", help: "Minimum spacing between nodes within a hierarchy level." },
    { property: "repulsion", label: "Force repulsion", control: "number", group: "Layout", help: "Applies only to force layout." },
    { property: "edgeLength", label: "Force edge length", control: "number", group: "Layout", help: "Applies only to force layout." },
    { property: "gravity", label: "Force gravity", control: "number", group: "Layout", help: "Applies only to force layout." },
    { property: "roam", label: "Pan and zoom", control: "checkbox", group: "Interaction" },
    { property: "draggable", label: "Draggable nodes", control: "checkbox", group: "Interaction", help: "Defaults off for settled layouts and on for force layout." },
    { property: "directed", label: "Directed arrows", control: "checkbox", group: "Appearance" },
    { property: "showLabels", label: "Show node labels", control: "checkbox", group: "Appearance" },
    { property: "showEdgeLabels", label: "Show edge labels", control: "checkbox", group: "Appearance" },
    { property: "nodeSize", label: "Node size", control: "number", group: "Appearance" },
    { property: "edgeWidth", label: "Edge width", control: "number", group: "Appearance" },
    { property: "edgeOpacity", label: "Edge opacity", control: "number", group: "Appearance" },
    { property: "edgeCurveness", label: "Edge curveness", control: "number", group: "Appearance" },
    { property: "arrowSize", label: "Arrow size", control: "number", group: "Appearance" },
    { property: "maxNodes", label: "Maximum nodes", control: "number", group: "Advanced", help: "Bounded from 2 through 5,000; defaults to 1,500." },
];

export const networkGraphDescriptor: ComponentDescriptor = {
    ...sankey,
    type: "networkGraph",
    label: "Network graph",
    category: "Charts",
    maturity: "beta",
    complexity: "standard",
    useWhen: "Interactive source-to-target relationships, dependency networks, lineage, and effort trees",
    capabilities: { ...sankey.capabilities, interactions: true, externalSelection: true },
    interaction: {
        defaultEnabled: true,
        naturalTrigger: "click",
        autoExternalMode: "selection",
    },
    schema: {
        required: ["type", "id", "sourceField", "targetField"],
        allowed: [
            ...sankey.schema.allowed.filter(property => !removedProperties.has(property) && !graphProperties.includes(property)),
            ...graphProperties,
        ],
    },
    fields: [
        ...sankey.fields.filter(field => !removedProperties.has(field.property)),
        ...additionalFields,
    ],
    inspector: [
        ...sankey.inspector.filter(item => !removedProperties.has(item.property) && !graphProperties.includes(item.property)),
        ...additionalInspector,
    ],
    documentation: {
        summary: "Interactive node-link graph from source-target edge rows with calm hybrid, deterministic hierarchical, force, or circular layout.",
        accessibility: [
            "Nodes and edges preserve Power BI row lineage for selection. Provide an adjacent table or detail view when keyboard access to every relationship is required; drag positioning is pointer-first when enabled.",
        ],
        relatedTypes: ["sankeyChart", "table", "advancedChart"],
    },
    example: {
        type: "networkGraph",
        id: "network_graph",
        title: "Relationship graph",
        sourceField: "__field_key__",
        targetField: "__field_key_2__",
        layout: "hybrid",
        orientation: "horizontal",
        roam: true,
        draggable: false,
        directed: true,
        showLabels: true,
        showEdgeLabels: false,
        nodeSize: 22,
        levelGap: 185,
        nodeGap: 64,
        edgeWidth: 1.25,
        edgeOpacity: 0.62,
        arrowSize: 5,
        maxNodes: 1500,
        interaction: {
            enabled: true,
            trigger: "click",
            internalMode: "highlight",
            internalScope: "self",
            externalMode: "selection",
            selectionMode: "replace",
            multiSelect: true,
            clearOnSecondClick: true,
        },
    },
    rendering: "direct",
    containers: [],
};
