import { ContentComponent } from "../../schema/hyperpbiSchema";

export interface CustomComponentTemplate { id:string; name:string; description:string; component:ContentComponent; }
export function customComponentTemplates(fieldKeys:string[]=[]):CustomComponentTemplate[]{
    const field=fieldKeys[0]??"field_key";const second=fieldKeys[1]??field;
    return [
        {id:"kpi",name:"Custom KPI tile",description:"Compact branded record count.",component:{type:"custom",id:"custom_kpi",html:"<div class='custom-kpi'><span>Records</span><strong>{{count}}</strong></div>",css:".custom-kpi{display:grid;gap:4px;padding:12px;border:1px solid var(--hp-border);border-radius:8px;background:var(--hp-surface)}.custom-kpi span{font-size:10px;text-transform:uppercase}.custom-kpi strong{font-size:24px}"}},
        {id:"slicer",name:"Custom slicer/list",description:"Distinct externally selectable values that remain visible.",component:{type:"custom",id:"custom_slicer",repeat:{source:"rows",distinctBy:field,sortBy:field,sortDirection:"asc",limit:200,template:`<div class='slicer-item'>{{row.${field}}}</div>`},interactions:{onClick:{action:"selectWhere",selectionMode:"replace",internal:false,external:true,where:{op:"=",left:{field},right:{valueFromRow:field}}}},css:".hp-custom-body{display:flex;flex-wrap:wrap;gap:5px}.hp-custom-repeat-row{cursor:pointer}.slicer-item{padding:5px 9px;border:1px solid var(--hp-border);border-radius:999px;background:var(--hp-surface)}.hp-custom-repeat-row.is-selected .slicer-item{border-color:var(--hp-primary);background:color-mix(in srgb,var(--hp-primary) 12%,var(--hp-surface))}"}},
        {id:"status",name:"Custom status card",description:"Selected/first-row status with safe tokens.",component:{type:"custom",id:"custom_status",html:`<div class='status-card'><span>Status</span><strong>{{row.${field}}}</strong></div>`,repeat:{source:"rows",limit:1,template:`<div class='status-value'>{{row.${field}}}</div>`},css:".status-card,.status-value{padding:9px;border-left:3px solid var(--hp-primary);background:color-mix(in srgb,var(--hp-primary) 6%,var(--hp-surface))}.status-card span{display:block;font-size:9px;text-transform:uppercase}"}},
        {id:"record",name:"Custom record card",description:"Compact two-field record summary.",component:{type:"custom",id:"custom_record",repeat:{source:"rows",limit:12,template:`<article class='record-card'><strong>{{row.${field}}}</strong><span>{{row.${second}}}</span></article>`},css:".hp-custom-body{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:6px}.record-card{display:grid;gap:2px;padding:8px;border:1px solid var(--hp-border);border-radius:6px}.record-card span{color:color-mix(in srgb,var(--hp-text) 60%,transparent);font-size:10px}"}},
        {id:"alert",name:"Custom alert banner",description:"Safe high-visibility banner without scripts.",component:{type:"custom",id:"custom_alert",html:"<div class='custom-alert'><strong>Attention required</strong><span>{{count}} records are currently in scope.</span></div>",css:".custom-alert{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 12px;border:1px solid var(--hp-warning);border-radius:6px;background:color-mix(in srgb,var(--hp-warning) 10%,var(--hp-surface))}"}},
        {id:"chips",name:"Compact filter chips",description:"Distinct compact selectable chips.",component:{type:"custom",id:"custom_filter_chips",repeat:{source:"rows",distinctBy:field,sortBy:field,sortDirection:"asc",limit:100,template:`<span class='filter-chip'>{{row.${field}}}</span>`},interactions:{onClick:{action:"selectWhere",selectionMode:"toggle",internal:false,external:true,where:{op:"=",left:{field},right:{valueFromRow:field}}}},css:".hp-custom-body{display:flex;flex-wrap:wrap;gap:4px}.filter-chip{display:block;padding:3px 7px;border:1px solid var(--hp-border);border-radius:12px;font-size:10px}.hp-custom-repeat-row.is-selected .filter-chip{background:var(--hp-primary);border-color:var(--hp-primary);color:#fff}"}}
    ];
}

