import { describe,expect,it } from "vitest";
import { mergeSafeEChartOptions, sanitizeEChartOptions } from "../src/components/charts/safeEChartOptions";
import { registeredEChartSeries } from "../src/components/charts/EChartRenderer";
import { componentCatalog, componentTypeNames } from "../src/catalog/componentCatalog";
import { customComponentTemplates } from "../src/components/custom/customComponentTemplates";
import { designPresets } from "../src/design/stylePresets";

describe("advanced dashboard contracts",()=>{
    it("sanitizes advanced ECharts options and preserves safe JSON",()=>{const result=sanitizeEChartOptions({title:{text:"Operations"},tooltip:{formatter:"<script>bad()</script>"},series:[{type:"radar",data:[[1,2]]},{type:"custom",renderItem:()=>null}],graphic:{href:"https://example.com"},constructor:{polluted:true}});expect(result.option).toMatchObject({title:{text:"Operations"},series:[{type:"radar",data:[[1,2]]},{}]});expect(JSON.stringify(result.option)).not.toContain("script");expect(JSON.stringify(result.option)).not.toContain("https://");expect(JSON.stringify(result.option)).not.toContain("polluted");expect(result.warnings.length).toBeGreaterThan(2);});
    it("safely merges options without mutating the generated base",()=>{const base={grid:{left:40,right:10},series:[{type:"bar",data:[1]}]};const result=mergeSafeEChartOptions(base,{grid:{left:20},series:[{type:"line",data:[2]}]});expect(result.option).toMatchObject({grid:{left:20,right:10},series:[{type:"line",data:[2]}]});expect(base.grid.left).toBe(40);});
    it("registers and permits every declarative ECharts series shipped by ECharts 6",()=>{const result=sanitizeEChartOptions({tooltip:{formatter:"{b}: {c}"},series:registeredEChartSeries.map(type=>({type,data:[]}))});expect(result.warnings).toEqual([]);expect(result.option).toMatchObject({tooltip:{formatter:"{b}: {c}"},series:registeredEChartSeries.map(type=>({type,data:[]}))});});
    it("keeps one catalog source for old and new components",()=>{for(const type of ["grid","custom","table","map","advancedChart","drawer","filterDrawer","segmentedControl","timeline","matrix","smallMultiples"])expect(componentTypeNames).toContain(type);expect(new Set(componentCatalog.map(item=>item.type)).size).toBe(componentCatalog.length);});
    it("defines six complete professional presets",()=>{expect(designPresets.map(item=>item.name)).toEqual(["Enterprise Light","Bright Modern","Futuristic Light","Dark Ops Center","Dense Compact","Map Command Center"]);for(const preset of designPresets){expect(preset.theme.primaryColor).toBeTruthy();expect(preset.guidance.selected).toBeTruthy();expect(preset.guidance.table).toBeTruthy();}});
    it("ships safe custom templates including a row-aware slicer",()=>{const templates=customComponentTemplates(["leadby","status"]);expect(templates).toHaveLength(6);const slicer=templates.find(item=>item.id==="slicer")?.component;expect(slicer?.repeat).toMatchObject({distinctBy:"leadby",sortBy:"leadby"});expect(slicer?.interactions?.onClick).toMatchObject({action:"selectWhere",internal:false,external:true,where:{right:{valueFromRow:"leadby"}}});const markup=templates.map(item=>`${item.component.html??""}${item.component.repeat?.template??""}`).join(" ");expect(markup).not.toMatch(/onclick|<script|javascript:/i);});
});
