import { describe,expect,it } from "vitest";
import { mergeSafeBuiltInEChartOptions, mergeSafeEChartOptions, sanitizeEChartOptions } from "../src/components/charts/safeEChartOptions";
import { registeredEChartSeries } from "../src/components/charts/EChartRenderer";
import { componentCatalog, componentTypeNames } from "../src/catalog/componentCatalog";
import { customComponentTemplates } from "../src/components/custom/customComponentTemplates";
import { designPresets } from "../src/design/stylePresets";
import { componentJsonExamples } from "../src/catalog/componentJsonExamples";
import { formatBuiltInChartValue, scaleScatterPointSizes } from "../src/components/charts/ChartBlock";

describe("advanced dashboard contracts",()=>{
    it("sanitizes advanced ECharts options and preserves safe JSON",()=>{const result=sanitizeEChartOptions({title:{text:"Operations"},tooltip:{formatter:"<script>bad()</script>"},series:[{type:"radar",data:[[1,2]]},{type:"custom",renderItem:()=>null}],graphic:{href:"https://example.com"},constructor:{polluted:true}});expect(result.option).toMatchObject({title:{text:"Operations"},series:[{type:"radar",data:[[1,2]]},{}]});expect(JSON.stringify(result.option)).not.toContain("script");expect(JSON.stringify(result.option)).not.toContain("https://");expect(JSON.stringify(result.option)).not.toContain("polluted");expect(result.warnings.length).toBeGreaterThan(2);});
    it("safely merges options without mutating the generated base",()=>{const base={grid:{left:40,right:10},series:[{type:"bar",data:[1]}]};const result=mergeSafeEChartOptions(base,{grid:{left:20},series:[{type:"line",data:[2]}]});expect(result.option).toMatchObject({grid:{left:20,right:10},series:[{type:"line",data:[2]}]});expect(base.grid.left).toBe(40);});
    it("preserves runtime data and selectedMode when styling a built-in series",()=>{const result=mergeSafeBuiltInEChartOptions({series:[{type:"bar",selectedMode:"multiple",data:[1,2]}]},{series:[{barMaxWidth:20,itemStyle:{color:"#123456"}}]});expect(result.option).toMatchObject({series:[{type:"bar",selectedMode:"multiple",data:[1,2],barMaxWidth:20,itemStyle:{color:"#123456"}}]});});
    it("registers and permits every declarative ECharts series shipped by ECharts 6",()=>{const result=sanitizeEChartOptions({tooltip:{formatter:"{b}: {c}"},series:registeredEChartSeries.map(type=>({type,data:[]}))});expect(result.warnings).toEqual([]);expect(result.option).toMatchObject({tooltip:{formatter:"{b}: {c}"},series:registeredEChartSeries.map(type=>({type,data:[]}))});});
    it("keeps one catalog source for old and new components",()=>{for(const type of ["grid","custom","table","map","advancedChart","drawer","filterDrawer","segmentedControl","timeline","matrix","smallMultiples"])expect(componentTypeNames).toContain(type);expect(new Set(componentCatalog.map(item=>item.type)).size).toBe(componentCatalog.length);});
    it("defines six complete professional presets",()=>{expect(designPresets.map(item=>item.name)).toEqual(["Enterprise Light","Bright Modern","Futuristic Light","Dark Ops Center","Dense Compact","Map Command Center"]);for(const preset of designPresets){expect(preset.theme.primaryColor).toBeTruthy();expect(preset.guidance.selected).toBeTruthy();expect(preset.guidance.table).toBeTruthy();}});
    it("ships safe custom templates including a row-aware universal slicer",()=>{const templates=customComponentTemplates(["leadby","status"]);expect(templates).toHaveLength(6);const slicer=templates.find(item=>item.id==="slicer")?.component;expect(slicer?.repeat).toMatchObject({distinctBy:"leadby",sortBy:"leadby"});expect(slicer?.interactions?.onClick).toMatchObject({action:"selectWhere",where:{right:{valueFromRow:"leadby"}}});expect(slicer?.interaction).toMatchObject({enabled:true,internalMode:"none",externalMode:"filter",field:"leadby"});const markup=templates.map(item=>`${item.component.html??""}${item.component.repeat?.template??""}`).join(" ");expect(markup).not.toMatch(/onclick|<script|javascript:/i);});
    it("never emits dirty rectangles or lazy updates in chart catalog examples",()=>{const json=JSON.stringify(componentJsonExamples);expect(json).not.toContain('"useDirtyRect":true');expect(json).not.toContain('"lazyUpdate":true');expect(componentJsonExamples.scatterChart).toMatchObject({pointSize:"__size_measure_field_key__"});});
    it("formats built-in tooltip values without floating-point noise",()=>{expect(formatBuiltInChartValue(888820.7200000001)).toBe(new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(888820.72));expect(formatBuiltInChartValue(42)).toBe(new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(42));expect(formatBuiltInChartValue({bad:true})).toBe("");});
    it("uses a bounded scatter point-size scale",()=>{const sizes=scaleScatterPointSizes([0,25,100]);expect(sizes[0]).toBeGreaterThanOrEqual(8);expect(sizes[2]).toBeLessThanOrEqual(36);expect(sizes[0]).toBeLessThan(sizes[1]);expect(sizes[1]).toBeLessThan(sizes[2]);});
});
