import { describe,expect,it } from "vitest";
import { calculateAggregates } from "../src/data/aggregations";
import { evaluateDatasets } from "../src/data/datasets";
import { normalizeMapBindings } from "../src/data/normalizeMapBindings";
import { NormalizedData,NormalizedField } from "../src/data/normalizeData";
import { createFieldAliasRegistry } from "../src/fields/fieldAliasRegistry";
import { FieldResolver } from "../src/fields/fieldResolver";
import { extractJsonWithDiagnostics } from "../src/ai/extractJsonFromAiResponse";
import { prepareSpecification } from "../src/schema/prepareSpecification";
import { validateSchema } from "../src/schema/validateSchema";
import { componentTree,deleteComponent,duplicateComponent,moveComponent,updateComponent } from "../src/editor/inspector/specificationEditor";
import { composeAiPrompt } from "../src/ai/promptComposer";
import { defaultAiPromptSettings } from "../src/ai/aiPromptSettings";

const rows=[{orders_id:"A",orders_status:"Open",orders_month:"2026-01-01",orders_amount:10},{orders_id:"B",orders_status:"Open",orders_month:"2026-01-01",orders_amount:20},{orders_id:"C",orders_status:"Closed",orders_month:"2026-02-01",orders_amount:30}];
const fields:Record<string,NormalizedField>={orders_id:{key:"orders_id",displayName:"ID",queryName:"Orders[ID]",sourceTable:"Orders",sourceColumn:"ID",qualifiedName:"Orders.ID",type:"dimension",roles:[],kind:"column",dataType:"text"},orders_status:{key:"orders_status",displayName:"Status",queryName:"Orders[Status]",sourceTable:"Orders",sourceColumn:"Status",qualifiedName:"Orders.Status",type:"dimension",roles:[],kind:"column",dataType:"text"},orders_month:{key:"orders_month",displayName:"Month",queryName:"Orders[Month]",sourceTable:"Orders",sourceColumn:"Month",qualifiedName:"Orders.Month",type:"date",roles:[],kind:"column",dataType:"date"},orders_amount:{key:"orders_amount",displayName:"Amount",queryName:"Orders[Amount]",sourceTable:"Orders",sourceColumn:"Amount",qualifiedName:"Orders.Amount",type:"measure",roles:[],kind:"measure",dataType:"number"}};
const data:NormalizedData={rows,rowKeys:["a","b","c"],fields,aggregates:calculateAggregates(rows),map:normalizeMapBindings(rows,fields,undefined,undefined,["a","b","c"])};

describe("AI-first version 2 foundation",()=>{
    it("creates deterministic semantic aliases, honors privacy, overrides, and legacy keys",()=>{const reversed:NormalizedData={...data,fields:Object.fromEntries(Object.entries(fields).reverse())};expect(createFieldAliasRegistry(data).entries.map(item=>item.alias)).toEqual(createFieldAliasRegistry(reversed).entries.map(item=>item.alias));const registry=createFieldAliasRegistry(data,{orders_status:"workStatus"},"types");expect(registry.byAlias.get("workStatus")?.semanticRole).toBe("status");expect(registry.byAlias.get("workStatus")?.profile).toBeUndefined();expect(new FieldResolver(data).resolve("orders_status").key).toBe("orders_status");expect(createFieldAliasRegistry(data,{orders_id:"duplicate",orders_status:"duplicate"}).errors).toHaveLength(2);});
    it("handles alias collisions without field-order counters",()=>{const collisionFields={a:{...fields.orders_id,key:"a",displayName:"Name",sourceTable:"Alpha",sourceColumn:"Name",queryName:"Alpha[Name]"},b:{...fields.orders_id,key:"b",displayName:"Name",sourceTable:"Beta",sourceColumn:"Name",queryName:"Beta[Name]"}};const collisionData={...data,fields:collisionFields};expect(createFieldAliasRegistry(collisionData).entries.map(item=>item.alias).sort()).toEqual(["alphaName","betaName"]);});
    it("evaluates logical datasets once with filtering, derive, grouping, sorting, limits, and lineage",()=>{const definitions={open:{source:"powerbi",filter:{field:"orders_status",operator:"=" as const,value:"Open"},derive:{double:{op:"*" as const,args:[{field:"orders_amount"},{value:2}]}},groupBy:["orders_month"],metrics:{amount:{op:"sum" as const,field:"double"}},sort:[{field:"amount",direction:"descending" as const}],limit:1}};const cache=new Map();const first=evaluateDatasets(data,definitions,cache).datasets.get("open")!;expect(first.data.rows).toEqual([{orders_month:"2026-01-01",amount:60}]);expect(first.lineage).toEqual([[0,1]]);const second=evaluateDatasets(data,definitions,cache).datasets.get("open")!;expect(second.diagnostic.cacheStatus).toBe("hit");});
    it("detects unknown dataset sources and cycles",()=>{const result=evaluateDatasets(data,{a:{source:"b"},b:{source:"a"},missing:{source:"nope"}});expect(result.errors.map(item=>item.code)).toEqual(expect.arrayContaining(["DATASET_CYCLE","UNKNOWN_DATASET"]));});
    it("rejects unknown version 2 properties with structured suggestions while accepting v1 leniency",()=>{const invalid=validateSchema({version:"2.0",components:[{type:"lineChart",id:"trend",category:"orders_month",meausre:"orders_amount"}]});expect(invalid.valid).toBe(false);expect(invalid.diagnostics?.find(item=>item.code==="UNKNOWN_PROPERTY")?.suggestions).toContain("measure");expect(validateSchema({version:"1.0",components:[{type:"text",legacyExtra:true}]}).valid).toBe(true);});
    it("expands definitions and all built-in patterns with stable child IDs",()=>{const specification={version:"2.0",definitions:{standard:{type:"kpi",variant:"primary"}},components:[{use:"standard",id:"amount-kpi",field:"amount"},{type:"pattern",pattern:"kpi-row",id:"summary",fields:["amount"]},{type:"pattern",pattern:"trend-and-breakdown",id:"trend",date:"month",measure:"amount",breakdown:"status"},{type:"pattern",pattern:"record-explorer",id:"records",columns:["id","status"],details:{titleField:"id",fields:["status"]}},{type:"pattern",pattern:"map-and-details",id:"locations"}]};const prepared=prepareSpecification(specification,data);expect(prepared.errors).toEqual([]);expect(JSON.stringify(prepared.schema)).toContain("summary--kpi-1");expect(JSON.stringify(prepared.schema)).toContain("trend--trend");expect(JSON.stringify(prepared.schema)).toContain("records--table");expect(JSON.stringify(prepared.schema)).toContain("locations--map");expect((prepared.authoring as typeof specification).components[1]).toMatchObject({type:"pattern"});});
    it("resolves aliases into runtime keys and binds named dataset output fields",()=>{const specification={version:"2.0",data:{datasets:{monthly:{source:"powerbi",groupBy:["month"],metrics:{total:{op:"sum",field:"amount"}}}}},components:[{type:"lineChart",id:"trend",dataset:"monthly",category:"month",measure:"total"}]};const prepared=prepareSpecification(specification,data);expect(prepared.errors).toEqual([]);expect(prepared.schema?.components[0]).toMatchObject({category:"orders_month",measure:"total"});expect((prepared.authoring as typeof specification).components[0].category).toBe("month");});
    it("extracts common wrappers and diagnoses multiple or truncated JSON",()=>{expect(extractJsonWithDiagnostics("\uFEFF Prose {\"version\":\"2.0\",\"components\":[]} done").value).toBeTruthy();expect(extractJsonWithDiagnostics("{} {}").diagnostics?.[0].code).toBe("MULTIPLE_JSON_OBJECTS");expect(extractJsonWithDiagnostics('{"version":"2.0"').diagnostics?.[0].code).toBe("TRUNCATED_JSON");});
    it("composes job-aware prompts and omits irrelevant map and advanced modules",()=>{const create=composeAiPrompt(data,defaultAiPromptSettings,{currentSpecification:"SECRET"});expect(create.includedModules).not.toContain("maps");expect(create.includedModules).not.toContain("advanced-chart");expect(create.prompt).not.toContain("SECRET");const improve=composeAiPrompt(data,{...defaultAiPromptSettings,job:"improve"},{currentSpecification:'{"version":"2.0","components":[]}'});expect(improve.includedModules).toContain("current-specification");});
    it("edits the canonical component tree without a private state format",()=>{const specification={version:"2.0",components:[{type:"text",id:"a",title:"A"},{type:"text",id:"b",title:"B"}]};expect(componentTree(specification).map(item=>item.id)).toEqual(["a","b"]);expect((updateComponent(specification,"a",{title:"Changed"}) as typeof specification).components[0].title).toBe("Changed");expect((moveComponent(specification,"b",-1) as typeof specification).components[0].id).toBe("b");expect(componentTree(duplicateComponent(specification,"a")).map(item=>item.id)).toContain("a-copy");expect(componentTree(deleteComponent(specification,"a")).map(item=>item.id)).toEqual(["b"]);});
});
