import { h, render } from "preact";
import { describe, expect, it } from "vitest";
import { componentCatalog, componentTypeNames } from "../src/catalog/componentCatalog";
import { componentJsonExample, componentJsonExamples } from "../src/catalog/componentJsonExamples";
import { AiPromptComponentReference } from "../src/editor/ai/AiPromptComponentReference";
import { validateSchema } from "../src/schema/validateSchema";

describe("AI component catalog",()=>{
    it("provides complete copyable JSON and interaction help for every component",()=>{const host=document.createElement("div");render(h(AiPromptComponentReference,{fieldKeys:["field"]}),host);expect(host.querySelectorAll(".hp-component-json")).toHaveLength(componentTypeNames.length);expect(host.querySelectorAll(".hp-component-json button")).toHaveLength(componentTypeNames.length);expect(host.querySelectorAll(".hp-interaction-summary")).toHaveLength(componentTypeNames.length);expect(host.textContent).toContain("Copy interaction JSON");expect(host.textContent).toContain("Copy component JSON");expect(host.innerHTML).toContain("__field_key__");});
    it("covers metadata and a valid universal interaction example for every catalog type",()=>{expect(Object.keys(componentJsonExamples).sort()).toEqual([...componentTypeNames].sort());expect(componentCatalog).toHaveLength(componentTypeNames.length);for(const metadata of componentCatalog){expect(metadata.interaction.naturalTrigger).toMatch(/click|change/);const json=componentJsonExample(metadata.type);const component=JSON.parse(json) as Record<string,unknown>;expect(component.type).toBe(metadata.type);expect(component.interaction).toBeTruthy();expect(component).not.toHaveProperty("internal");expect(component).not.toHaveProperty("external");expect(component).not.toHaveProperty("selectable");expect(component).not.toHaveProperty("selectionMode");expect(validateSchema({version:"1.0",components:[component]})).toMatchObject({valid:true,errors:[]});}});
    it("documents full KPI, table, map, custom, and advanced chart policies",()=>{expect(componentJsonExamples.kpi).toMatchObject({field:"__field_key__",aggregation:"sum",interaction:{enabled:false,internalMode:"none",externalMode:"none"}});expect(componentJsonExamples.table).toMatchObject({pagination:true,search:true,resizableColumns:true,interaction:{enabled:true,showSelector:true,externalMode:"auto"}});expect(componentJsonExamples.map).toHaveProperty("interaction.internalMode","highlight");expect(componentJsonExamples.custom).toHaveProperty("interaction.externalMode","filter");expect(componentJsonExamples.advancedChart).toHaveProperty("options.toolbox.show",true);});
    it("fails loudly when a catalog example is missing",()=>expect(()=>componentJsonExample("unknownComponent")).toThrow("Missing component JSON example"));
});
