import { h, render } from "preact";
import { useReducer } from "preact/hooks";
import { act } from "preact/test-utils";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { RenderContext, type RenderContextValue } from "../src/render/RenderContext";
import { dashboardReducer, initialDashboardState } from "../src/render/stateStore";
import { OverlayTrigger } from "../src/components/overlays/OverlayTrigger";
import { OverlayHost } from "../src/components/overlays/OverlayHost";
import { overlayRuntime } from "../src/components/overlays/overlayRuntime";
import { executeUiActions } from "../src/actions/uiActions";
import { defaultConfig } from "../src/config/hyperpbiConfig";
import { toRuntimeSettings, VisualFormattingSettingsModel } from "../src/settings";
import type { DropdownComponent, HyperPbiSchema } from "../src/schema/hyperpbiSchema";
import { AppNavbar } from "../src/components/app/AppNavbar";

const dropdown:DropdownComponent={type:"dropdown",id:"commands",trigger:{label:"Commands"},items:[{id:"apply",label:"Apply",action:{type:"setState",target:"applied",value:true},interaction:{enabled:true,trigger:"click",internalMode:"none",externalMode:"filter",field:"Status",value:"Open"}}]};
const schema:HyperPbiSchema={version:"1.0",components:[dropdown,{type:"modal",id:"editor",title:"Editor",children:[{type:"text",id:"modal_text",text:"Modal content"}]}]};
const applyExternalFilter=vi.fn(()=>({sent:true as const}));

function Harness(){const [state,dispatch]=useReducer(dashboardReducer,initialDashboardState());const rows=[{Status:"Open"},{Status:"Closed"}];const data={rows,rowKeys:["0","1"],fields:{Status:{key:"Status",displayName:"Status",type:"dimension",roles:[]}},aggregates:{count:2,sum:{},avg:{},min:{},max:{},distinctCount:{},first:{}},map:{hasGeometry:false,hasLatLon:false,hasXY:false,hasAddress:false,mode:"none",bindings:{tooltip:[],details:[]},layers:[],warnings:[],invalidFeatureCount:0}} as any;const value={data,rows,sourceRows:rows,sourceRowKeys:data.rowKeys,getRowsForComponent:()=>rows,componentRows:()=>[],schema,settings:toRuntimeSettings(new VisualFormattingSettingsModel()),state,dispatch,warnings:[],selectExternal:vi.fn(()=>({sent:true})),clearExternal:vi.fn(()=>({sent:true})),applyExternalFilter,clearExternalFilter:vi.fn(()=>({sent:true})),reportInteraction:vi.fn(),config:defaultConfig,webAccessAvailable:false,isOverlayOpen:(id:string)=>state.openOverlays.includes(id)} as unknown as RenderContextValue;value.executeUiAction=(action,event)=>executeUiActions(action,value,event);return <RenderContext.Provider value={value}><OverlayTrigger component={dropdown}/><button id="modal-opener" type="button" onClick={event=>value.executeUiAction({type:"openOverlay",target:"editor"},event)}>Edit</button><AppNavbar config={{actions:[{id:"more",label:"More",menu:[{id:"refresh",label:"Refresh",action:{type:"refresh"}}]}],user:{name:"Jane",menu:[{id:"profile",label:"Profile",action:{type:"refresh"}}]},notifications:{count:1,items:[{id:"notice",message:"Ready"}]}}} sidebarVisible={false} sidebarCollapsed={false} state={state} dispatch={dispatch}/><output data-applied>{String(Boolean(state.values.applied))}</output><OverlayHost/></RenderContext.Provider>;}

const settle=()=>new Promise(resolve=>setTimeout(resolve,50));
describe("shared overlay runtime",()=>{
    beforeEach(()=>{applyExternalFilter.mockClear();overlayRuntime.triggers.clear();overlayRuntime.panels.clear();overlayRuntime.definitions.clear();overlayRuntime.stack=[];document.body.replaceChildren();});
    afterEach(()=>{render(null,document.body);overlayRuntime.triggers.clear();overlayRuntime.panels.clear();overlayRuntime.definitions.clear();overlayRuntime.stack=[];document.body.replaceChildren();});
    it("executes dropdown actions and interactions, then restores trigger focus",async()=>{await act(async()=>{render(<Harness/>,document.body);await settle();});const trigger=document.querySelector("#commands-trigger") as HTMLButtonElement;await act(async()=>{trigger.click();await settle();});expect(document.querySelector('[role="menu"]')).not.toBeNull();const item=document.querySelector('[role="menuitem"]') as HTMLButtonElement;await act(async()=>{item.click();await settle();});expect(document.querySelector("[data-applied]")?.textContent).toBe("true");expect(applyExternalFilter).toHaveBeenCalledWith("Status","=","Open",expect.objectContaining({componentId:"commands"}));expect(document.querySelector('[role="menu"]')).toBeNull();expect(document.activeElement).toBe(trigger);});
    it("dismisses only the top overlay with outside click or Escape",async()=>{await act(async()=>{render(<Harness/>,document.body);await settle();});const trigger=document.querySelector("#commands-trigger") as HTMLButtonElement;await act(async()=>{trigger.click();await settle();});expect(overlayRuntime.stack).toEqual(["commands"]);await act(async()=>{document.dispatchEvent(new MouseEvent("pointerdown",{bubbles:true}));await settle();});expect(document.querySelector('[role="menu"]')).toBeNull();await act(async()=>{trigger.click();await settle();});await act(async()=>{document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}));await settle();});expect(document.querySelector('[role="menu"]')).toBeNull();expect(document.activeElement).toBe(trigger);});
    it("traps modal focus, closes on document Escape, and restores its opener",async()=>{await act(async()=>{render(<Harness/>,document.body);await settle();});const opener=document.querySelector("#modal-opener") as HTMLButtonElement;await act(async()=>{opener.click();await settle();});const dialog=document.querySelector('[role="dialog"]') as HTMLElement;expect(dialog).not.toBeNull();const close=dialog.querySelector("button") as HTMLButtonElement;expect(document.activeElement).toBe(close);const tab=new KeyboardEvent("keydown",{key:"Tab",bubbles:true,cancelable:true});close.dispatchEvent(tab);expect(tab.defaultPrevented).toBe(true);await act(async()=>{document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}));await settle();});expect(document.querySelector('[role="dialog"]')).toBeNull();expect(document.activeElement).toBe(opener);});
    it("uses the same dropdown host for navbar action, user, and notification menus",async()=>{await act(async()=>{render(<Harness/>,document.body);await settle();});expect(document.querySelector(".hp-navbar-user-menu")).toBeNull();const navbarTrigger=Array.from(document.querySelectorAll<HTMLButtonElement>(".hp-navbar-action")).find(button=>button.textContent?.includes("More"))!;await act(async()=>{navbarTrigger.click();await settle();});expect(document.querySelector("#hp-navbar-action-more-0-panel [role=menu]")).not.toBeNull();});
});
