import { describe,expect,it,vi } from "vitest";
import { getBasemapProvider } from "../src/providers/basemapProviderRegistry";
import { getGeocoderProvider } from "../src/providers/geocoderProviderRegistry";
import { GeocodeQueue } from "../src/providers/geocoders/geocodeQueue";
import { normalizeAddress } from "../src/providers/geocoders/normalizeAddress";
import { GeocoderProvider } from "../src/providers/providerTypes";
import { validateProviderConfig } from "../src/providers/providerConfig";
import { geocoderUnavailableReason } from "../src/providers/providerPolicy";

describe("provider architecture",()=>{
    it("provides policy-safe defaults",()=>{expect(getBasemapProvider("osm").defaults.attribution).toContain("OpenStreetMap");expect(getGeocoderProvider("nominatim").defaults.autocomplete).toBe(false);});
    it("normalizes cache keys",()=>expect(normalizeAddress([" 10 Main ","Austin "," TX"])).toBe("10 main, austin, tx"));
    it("rejects unsafe provider configuration",()=>expect(validateProviderConfig({geocoder:{provider:"nominatim",enabled:true,endpoint:`${"http"}://unsafe`,rateLimitPerSecond:2,autocomplete:false,userTriggeredOnly:true}}).length).toBeGreaterThan(0));
    it("runs sequentially and reuses cached results",async()=>{const geocode=vi.fn(async()=>({latitude:1,longitude:2}));const provider:GeocoderProvider={id:"custom",label:"test",external:true,defaults:{provider:"custom",enabled:true,autocomplete:false,userTriggeredOnly:true},geocode};const waits:number[]=[];const queue=new GeocodeQueue(provider,{provider:"custom",enabled:true,cache:true,rateLimitPerSecond:1,autocomplete:false,userTriggeredOnly:true},undefined,async ms=>{waits.push(ms);});const results=await queue.run(["10 Main","10 Main"]);expect(geocode).toHaveBeenCalledTimes(1);expect(results[1].status).toBe("cached");expect(waits).toHaveLength(1);});
    it("parses the highest-scoring ArcGIS findAddressCandidates result",async()=>{const fetchMock=vi.fn(async(_input:RequestInfo|URL)=>({ok:true,json:async()=>({candidates:[{score:82,location:{x:-95.3,y:29.7}},{score:98,location:{x:-95.4,y:29.8}}]})}));vi.stubGlobal("fetch",fetchMock);const result=await getGeocoderProvider("arcgis").geocode("901 Bagby",{provider:"arcgis",enabled:true,endpoint:"https://example.test/GeocodeServer",minScore:80,countryCode:"USA",category:"Address",token:"secret",autocomplete:false,userTriggeredOnly:true});expect(result).toEqual({latitude:29.8,longitude:-95.4});const url=new URL(String(fetchMock.mock.calls[0]?.[0]));expect(url.pathname).toMatch(/GeocodeServer\/findAddressCandidates$/);expect(url.searchParams.get("SingleLine")).toBe("901 Bagby");expect(url.searchParams.get("token")).toBe("secret");vi.unstubAllGlobals();});
    it("parses Nominatim labels, bounds, and the configured interactive result limit",async()=>{const fetchMock=vi.fn(async(_input:RequestInfo|URL)=>({ok:true,json:async()=>[{lat:"29.76",lon:"-95.37",display_name:"Houston, Texas",boundingbox:["29.5","30.1","-95.8","-94.9"]},{lat:"30.27",lon:"-97.74",display_name:"Austin, Texas"},{lat:"32.78",lon:"-96.8",display_name:"Dallas, Texas"}]}));vi.stubGlobal("fetch",fetchMock);const results=await getGeocoderProvider("nominatim").search!("Texas",{provider:"nominatim",enabled:true,endpoint:"https://nominatim.openstreetmap.org/search",resultLimit:2,autocomplete:false,userTriggeredOnly:true});expect(results).toEqual([{latitude:29.76,longitude:-95.37,label:"Houston, Texas",bounds:[-95.8,29.5,-94.9,30.1],provider:"nominatim"},{latitude:30.27,longitude:-97.74,label:"Austin, Texas",bounds:undefined,provider:"nominatim"}]);const url=new URL(String(fetchMock.mock.calls[0]?.[0]));expect(url.searchParams.get("limit")).toBe("2");vi.unstubAllGlobals();});
    it("parses ArcGIS search labels and extents",async()=>{const fetchMock=vi.fn(async()=>({ok:true,json:async()=>({candidates:[{address:"City Hall",score:99,location:{x:-95.37,y:29.76},extent:{xmin:-95.4,ymin:29.7,xmax:-95.3,ymax:29.8}}]})}));vi.stubGlobal("fetch",fetchMock);const results=await getGeocoderProvider("arcgis").search!("City Hall",{provider:"arcgis",enabled:true,endpoint:"https://example.test/GeocodeServer",resultLimit:5,minScore:80,autocomplete:false,userTriggeredOnly:true});expect(results[0]).toMatchObject({label:"City Hall",bounds:[-95.4,29.7,-95.3,29.8],provider:"arcgis"});vi.unstubAllGlobals();});
    it("reports exact geocoder policy rejection reasons",()=>{const enabled={mode:"maps" as const,geocoder:{provider:"nominatim" as const,enabled:true,endpoint:"https://nominatim.openstreetmap.org/search",autocomplete:false as const,userTriggeredOnly:true as const},privacyAcknowledged:true};expect(geocoderUnavailableReason(enabled,true,false)).toBe("Core package does not include external providers.");expect(geocoderUnavailableReason(enabled,false,true)).toBe("WebAccess is unavailable or denied by the Power BI host.");expect(geocoderUnavailableReason({...enabled,geocoder:{...enabled.geocoder,enabled:false}},true,true)).toBe("The geocoder provider is disabled.");expect(geocoderUnavailableReason({...enabled,privacyAcknowledged:false},true,true)).toBe("Privacy acknowledgment is required before geocoding.");expect(geocoderUnavailableReason({...enabled,geocoder:{...enabled.geocoder,endpoint:`${"http"}://unsafe`}},true,true)).toBe("The geocoder provider configuration is invalid.");expect(geocoderUnavailableReason(enabled,true,true)).toBeUndefined();});
});
