import { h,render } from "preact";
import { useState } from "preact/hooks";
import { act } from "preact/test-utils";
import { describe,expect,it,vi } from "vitest";
import { defaultConfigJson,parseConfig } from "../src/config/hyperpbiConfig";
import { RuntimeConfigTab } from "../src/editor/config/RuntimeConfigTab";
import { formToRuntimeConfig,normalizeRuntimeConfig,runtimeConfigToForm } from "../src/editor/config/runtimeConfigForm";
import { NormalizedData } from "../src/data/normalizeData";
import { calculateAggregates } from "../src/data/aggregations";
import { normalizeMapBindings } from "../src/data/normalizeMapBindings";

const rows=[{status:"Open"}];const fields={status:{key:"status",displayName:"Status",sourceTable:"Work",sourceColumn:"Status",type:"dimension" as const,roles:["values"]}};const data:NormalizedData={rows,rowKeys:rows.map((_,i)=>`row-${i}`),fields,aggregates:calculateAggregates(rows),map:normalizeMapBindings(rows,fields,undefined,undefined,rows.map((_,i)=>`row-${i}`))};
function Harness({changed}:{changed:(value:string)=>void}){const [value,setValue]=useState(defaultConfigJson);return <RuntimeConfigTab data={data} configuration={value} onChange={next=>{setValue(next);changed(next);}}/>;}
const click=(host:HTMLElement,text:string)=>Array.from(host.querySelectorAll("button")).find(button=>button.textContent===text)?.dispatchEvent(new MouseEvent("click",{bubbles:true}));

describe("Runtime Config GUI",()=>{
    it("updates JSON immediately from GUI changes",()=>{const changed=vi.fn();const host=document.createElement("div");act(()=>render(<Harness changed={changed}/>,host));const label=Array.from(host.querySelectorAll("label")).find(item=>item.textContent?.includes("Show dashboard header"));act(()=>{const input=label?.querySelector("input") as HTMLInputElement;input.checked=true;input.dispatchEvent(new Event("change",{bubbles:true}));});expect(parseConfig(changed.mock.lastCall?.[0]).config?.renderer?.showHeader).toBe(true);});
    it("applies valid JSON to the GUI only after Apply JSON",()=>{const changed=vi.fn();const host=document.createElement("div");act(()=>render(<Harness changed={changed}/>,host));const textarea=host.querySelector('textarea[aria-label="Advanced runtime configuration JSON"]') as HTMLTextAreaElement;const next=JSON.stringify({version:"1.0",renderer:{showHeader:true},security:{cssMode:"trusted",htmlMode:"sanitized"}});act(()=>{textarea.value=next;textarea.dispatchEvent(new Event("input",{bubbles:true}));});let header=Array.from(host.querySelectorAll("label")).find(item=>item.textContent?.includes("Show dashboard header"))?.querySelector("input") as HTMLInputElement;expect(header.checked).toBe(false);act(()=>click(host,"Apply JSON"));header=Array.from(host.querySelectorAll("label")).find(item=>item.textContent?.includes("Show dashboard header"))?.querySelector("input") as HTMLInputElement;expect(header.checked).toBe(true);expect(changed).toHaveBeenCalled();});
    it("keeps GUI state unchanged when JSON is invalid",()=>{const changed=vi.fn();const host=document.createElement("div");act(()=>render(<Harness changed={changed}/>,host));const textarea=host.querySelector('textarea[aria-label="Advanced runtime configuration JSON"]') as HTMLTextAreaElement;act(()=>{textarea.value="{bad";textarea.dispatchEvent(new Event("input",{bubbles:true}));});act(()=>click(host,"Apply JSON"));const header=Array.from(host.querySelectorAll("label")).find(item=>item.textContent?.includes("Show dashboard header"))?.querySelector("input") as HTMLInputElement;expect(header.checked).toBe(false);expect(host.textContent).toContain("GUI values are unchanged");expect(changed).not.toHaveBeenCalled();});
    it("round-trips renderer, security, providers, bindings, and ArcGIS options",()=>{const normalized=normalizeRuntimeConfig(defaultConfigJson).config!;const form=runtimeConfigToForm(normalized);const result=formToRuntimeConfig({...form,showHeader:true,cssMode:"trusted",packageMode:"maps",geocoderProvider:"arcgis",geocoderEnabled:true,endpoint:"https://example.test/GeocodeServer",minScore:91,token:"token",countryCode:"USA",category:"Address",map:{address:"status",tooltip:["status"],details:["status"]}},normalized);expect(runtimeConfigToForm(result)).toMatchObject({showHeader:true,cssMode:"trusted",packageMode:"maps",geocoderProvider:"arcgis",geocoderEnabled:true,minScore:91,token:"token",countryCode:"USA",category:"Address",map:{address:"status",tooltip:["status"],details:["status"]}});});
});
