import {describe,expect,it} from "vitest";
import {calculateAggregates} from "../src/data/aggregations";
import {resolveDatasetSchemas} from "../src/data/datasetSchema";
import {normalizeMapBindings} from "../src/data/normalizeMapBindings";
import type {NormalizedData,NormalizedField} from "../src/data/normalizeData";
import {canonicalizeSpecificationFieldReferences,specificationFieldReferences} from "../src/fields/specificationFieldReferences";
import {prepareSpecification} from "../src/schema/prepareSpecification";
import {validateReferences} from "../src/schema/validateReferences";

const fields:Record<string,NormalizedField>={model_status_key:{key:"model_status_key",displayName:"Status",sourceTable:"Work",sourceColumn:"Status",queryName:"Work.Status",type:"dimension",kind:"column",dataType:"text",origin:"powerbi-column",roles:[]},model_amount_sum:{key:"model_amount_sum",displayName:"Amount",sourceTable:"Work",sourceColumn:"Amount",queryName:"Sum(Work.Amount)",type:"measure",kind:"column",dataType:"number",origin:"powerbi-column",roles:[]},model_latitude:{key:"model_latitude",displayName:"Latitude",sourceTable:"Work",sourceColumn:"Latitude",type:"latitude",kind:"column",dataType:"number",origin:"powerbi-column",roles:[]},model_longitude:{key:"model_longitude",displayName:"Longitude",sourceTable:"Work",sourceColumn:"Longitude",type:"longitude",kind:"column",dataType:"number",origin:"powerbi-column",roles:[]}};
const rows=[{model_status_key:"Open",model_amount_sum:10,model_latitude:29.7,model_longitude:-95.3}];const data:NormalizedData={fields,rows,rowKeys:["1"],aggregates:calculateAggregates(rows),map:normalizeMapBindings(rows,fields)};
const dashboard=()=>({version:"2.0",data:{datasets:{base:{source:"powerbi",select:["status","amount","doubleAmount"],derive:{doubleAmount:{op:"*",args:[{field:"amount"},{value:2}]}}},chained:{source:"base",select:["status","doubleAmount"]}}},components:[
 {type:"table",id:"records",columns:[{field:"status",title:"Status"},{field:"amount",title:"Amount"}],interaction:{enabled:true,externalMode:"filter",field:"status"}},
 {type:"detailPanel",id:"details",groups:[{fields:["status",{field:"amount"}]}]},
 {type:"custom",id:"custom",html:"{{status}} {{row.status}} {{item.status}} {{datum.status}} {{metric.total}} {{state.mode}}",repeat:{source:"rows",template:"{{status}}",distinctBy:"status",sortBy:"amount"},interactions:{onClick:[{action:"selectWhere",where:{op:"=",left:{field:"status"},right:{valueFromRow:"status"}}}]}},
 {type:"svg",id:"diagram",viewBox:"0 0 100 100",elements:[{type:"rect",id:"bar",width:{bind:"amount"},height:10},{type:"text",id:"label",text:{template:"{{datum.status}}"}}]},
 {type:"map",id:"locations",layers:[{id:"points",name:"Points",source:{type:"powerbi",bindings:{latitude:"latitude",longitude:"longitude"}},renderer:{type:"uniqueValue",field:"status",fieldSource:"powerbi",values:[]},visibility:{conditionField:"status",conditionValues:["Open"]},popup:{enabled:true,fields:[{field:"status",fieldSource:"powerbi"}]}},{id:"service",name:"Service",source:{type:"arcgisFeature",url:"https://services.example.test/FeatureServer/0"},join:{powerBiField:"status",serviceField:"SERVICE_STATUS"},renderer:{type:"uniqueValue",field:"SERVICE_STATUS",fieldSource:"service"},popup:{enabled:true,fields:[{field:"SERVICE_STATUS",fieldSource:"service"},{field:"status",fieldSource:"powerbi"}]}}]}
]});

describe("shared specification field occurrences",()=>{
 it("canonicalizes nested aliases while preserving service and runtime namespaces",()=>{const value=dashboard();const datasets=resolveDatasetSchemas(data,{});const diagnostics=canonicalizeSpecificationFieldReferences(value,data,datasets);expect(diagnostics.filter(item=>item.code==="UNKNOWN_FIELD")).toEqual([]);const text=JSON.stringify(value);expect(text).toContain("model_status_key");expect(text).toContain("model_amount_sum");expect(text).toContain("SERVICE_STATUS");expect(text).toContain("{{metric.total}}");expect(text).toContain("{{state.mode}}");const paths=specificationFieldReferences(value).map(item=>item.path);expect(paths).toContain("/components/0/columns/0/field");expect(paths).toContain("/components/1/groups/0/fields/1/field");expect(paths).toContain("/components/4/layers/0/visibility/conditionField");});
 it("prepares a complete alias-authored dashboard and validates without false missing fields",()=>{const prepared=prepareSpecification(dashboard(),data,{repair:false});expect(prepared.errors).toEqual([]);expect(prepared.schema).toBeDefined();expect(validateReferences(prepared.schema!,data).filter(message=>message.includes("missing field"))).toEqual([]);expect((prepared.schema!.components[4] as any).layers[0].renderer.field).toBe("model_status_key");});
 it("reports display names and unknown references without guessing",()=>{const duplicateData={...data,fields:{...fields,a:{...fields.model_status_key,key:"a",displayName:"Duplicate"},b:{...fields.model_status_key,key:"b",displayName:"Duplicate"}}};const spec={version:"2.0",components:[{type:"table",id:"records",columns:["Duplicate","notAField"]}]};const diagnostics=canonicalizeSpecificationFieldReferences(spec,duplicateData,resolveDatasetSchemas(duplicateData,{}));expect(diagnostics).toEqual(expect.arrayContaining([expect.objectContaining({code:"UNKNOWN_FIELD",received:"Duplicate"}),expect.objectContaining({code:"UNKNOWN_FIELD",received:"notAField"})]));expect((spec.components[0].columns)).toEqual(["Duplicate","notAField"]);});
});
