import { h, render } from "preact";
import { afterEach, describe, expect, it, vi } from "vitest";
import { calculateAggregates } from "../src/data/aggregations";
import { normalizeMapBindings } from "../src/data/normalizeMapBindings";
import { DataRow, NormalizedData } from "../src/data/normalizeData";
import { clearComponentInteraction, componentRows, executeComponentInteraction, rowsForComponent } from "../src/interactions/componentInteraction";
import { createInteractionPayload } from "../src/interactions/interactionPayload";
import { componentKindForType, resolveInteractionPolicy } from "../src/interactions/interactionPolicy";
import { componentCatalog } from "../src/catalog/componentCatalog";
import { defaultConfig } from "../src/config/hyperpbiConfig";
import { RenderContextValue } from "../src/render/RenderContext";
import { dashboardReducer, initialDashboardState } from "../src/render/stateStore";
import { HyperPbiRoot } from "../src/render/HyperPbiRoot";
import { validateReferences } from "../src/schema/validateReferences";
import { ComponentBase, HyperPbiSchema } from "../src/schema/hyperpbiSchema";
import { toRuntimeSettings, VisualFormattingSettingsModel } from "../src/settings";

const rows:DataRow[]=[{status:"Open",amount:10},{status:"Closed",amount:20},{status:"Open",amount:30}];
const fields:NormalizedData["fields"]={status:{key:"status",displayName:"Status",sourceTable:"Work",sourceColumn:"Status",type:"dimension",roles:["values"]},amount:{key:"amount",displayName:"Amount",sourceTable:"Work",sourceColumn:"Amount",type:"measure",roles:["measure"]}};
const data:NormalizedData={rows,fields,aggregates:calculateAggregates(rows),map:normalizeMapBindings(rows,fields)};

function harness(config=defaultConfig){
    const selectExternal=vi.fn(()=>({sent:true as const}));const clearExternal=vi.fn(()=>({sent:true as const}));const applyExternalFilter=vi.fn(()=>({sent:true as const,target:{table:"Work",column:"Status"}}));const clearExternalFilter=vi.fn(()=>({sent:true as const}));const reportInteraction=vi.fn();
    const context={} as RenderContextValue;
    Object.assign(context,{data,rows,sourceRows:rows,schema:{version:"1.0",components:[]},settings:toRuntimeSettings(new VisualFormattingSettingsModel()),state:initialDashboardState(),warnings:[],config,webAccessAvailable:false,selectExternal,clearExternal,applyExternalFilter,clearExternalFilter,reportInteraction});
    context.dispatch=action=>{context.state=dashboardReducer(context.state,action);};context.componentRows=id=>componentRows(id,context);context.getRowsForComponent=id=>rowsForComponent(rows,rows,id,context);
    return{context,selectExternal,clearExternal,applyExternalFilter,clearExternalFilter,reportInteraction};
}
const component=(interaction:NonNullable<ComponentBase["interaction"]>,type="table"):ComponentBase=>({type,id:"source",interaction});

afterEach(()=>document.body.replaceChildren());

describe("universal interaction policy",()=>{
    it("honors enabled and click/change triggers",()=>{const test=harness();const disabled=resolveInteractionPolicy(component({enabled:false}),test.context.config,"dataPoint");expect(executeComponentInteraction(disabled,createInteractionPayload(component({enabled:false}),{rowIndices:[0]}),test.context,{trigger:"click"}).executed).toBe(false);const change=resolveInteractionPolicy(component({enabled:true,trigger:"change"},"select"),test.context.config,"control");expect(executeComponentInteraction(change,createInteractionPayload(component({enabled:true},"select"),{rowIndices:[0],field:"status",value:"Open"}),test.context,{trigger:"click"}).reason).toBe("trigger mismatch");});
    it("keeps explicit component policy above runtime fallback",()=>{const runtime={...defaultConfig,interactions:{crossFilter:true,multiSelect:true,externalMode:"selection" as const}};expect(resolveInteractionPolicy(component({enabled:true,externalMode:"filter"}),runtime,"dataPoint").externalMode).toBe("filter");expect(resolveInteractionPolicy({type:"select",id:"control"},runtime,"control").externalMode).toBe("selection");expect(resolveInteractionPolicy({type:"select",id:"control"},defaultConfig,"control").externalMode).toBe("filter");expect(resolveInteractionPolicy({type:"table",id:"row",selectable:true} as ComponentBase,defaultConfig,"dataPoint").externalMode).toBe("selection");});
    it("normalizes legacy flags without changing saved dashboards",()=>{expect(resolveInteractionPolicy({type:"table",selectable:true,selectionMode:"filter",external:false} as ComponentBase,defaultConfig,"dataPoint")).toMatchObject({enabled:true,showSelector:true,internalMode:"filter",internalScope:"self",externalMode:"none"});expect(resolveInteractionPolicy({type:"select",internal:false,external:true},defaultConfig,"control")).toMatchObject({enabled:true,internalMode:"none",externalMode:"filter"});});
});

describe("universal interaction execution",()=>{
    it("implements internal none, highlight, and filter independently",()=>{for(const mode of ["none","highlight","filter"] as const){const test=harness();const item=component({enabled:true,internalMode:mode,internalScope:"self",externalMode:"none"});const policy=resolveInteractionPolicy(item,test.context.config,"dataPoint");executeComponentInteraction(policy,createInteractionPayload(item,{rowIndices:[0,2],field:"status",value:"Open"}),test.context,{trigger:"click"});expect(test.context.state.componentSelectedRows.source).toEqual([0,2]);expect(test.context.componentRows("source")).toEqual(mode==="highlight"?[0,2]:[]);expect(test.context.state.selectedRows).toEqual(mode==="none"?[]:[0,2]);expect(test.context.state.interactionFilters).toHaveLength(mode==="filter"?1:0);}});
    it("applies self, others, and all scopes per component",()=>{for(const scope of ["self","others","all"] as const){const test=harness();test.context.dispatch({type:"interactionFilter",filter:{originComponentId:"source",field:"status",operator:"=",value:"Open",scope}});expect(test.context.getRowsForComponent("source").length).toBe(scope==="others"?3:2);expect(test.context.getRowsForComponent("target").length).toBe(scope==="self"?3:2);}});
    it("scopes highlight rows without removing data",()=>{const test=harness();const item=component({enabled:true,internalMode:"highlight",internalScope:"others",externalMode:"none"});executeComponentInteraction(resolveInteractionPolicy(item,test.context.config,"dataPoint"),createInteractionPayload(item,{rowIndices:[0,2]}),test.context,{trigger:"click"});expect(test.context.componentRows("source")).toEqual([]);expect(test.context.componentRows("target")).toEqual([0,2]);expect(test.context.getRowsForComponent("source")).toHaveLength(3);expect(test.context.getRowsForComponent("target")).toHaveLength(3);});
    it("supports external none, selection, filter, and auto",()=>{const none=harness();let item=component({enabled:true,externalMode:"none",internalMode:"none"});executeComponentInteraction(resolveInteractionPolicy(item,none.context.config,"dataPoint"),createInteractionPayload(item,{rowIndices:[0]}),none.context,{trigger:"click"});expect(none.selectExternal).not.toHaveBeenCalled();const selection=harness();item=component({enabled:true,externalMode:"selection",internalMode:"none"});executeComponentInteraction(resolveInteractionPolicy(item,selection.context.config,"dataPoint"),createInteractionPayload(item,{rowIndices:[0]}),selection.context,{trigger:"click"});expect(selection.selectExternal).toHaveBeenCalledWith([0],false,expect.any(Object));const filter=harness();item=component({enabled:true,externalMode:"filter",internalMode:"none",field:"status"});executeComponentInteraction(resolveInteractionPolicy(item,filter.context.config,"dataPoint"),createInteractionPayload(item,{rowIndices:[0],field:"status",value:"Open"}),filter.context,{trigger:"click"});expect(filter.applyExternalFilter).toHaveBeenCalledWith("status","=","Open",expect.any(Object));});
    it("sends one In filter for multi-select and clears on the second click",()=>{const test=harness();const item=component({enabled:true,externalMode:"filter",internalMode:"highlight",field:"status",selectionMode:"add",multiSelect:true});const policy=resolveInteractionPolicy(item,test.context.config,"dataPoint");executeComponentInteraction(policy,createInteractionPayload(item,{rowIndices:[0],field:"status",value:"Open"}),test.context,{trigger:"click"});executeComponentInteraction(policy,createInteractionPayload(item,{rowIndices:[1],field:"status",value:"Closed"}),test.context,{trigger:"click"});expect(test.applyExternalFilter).toHaveBeenLastCalledWith("status","in",expect.arrayContaining(["Open","Closed"]),expect.any(Object));const clearItem=component({enabled:true,externalMode:"selection",internalMode:"highlight",clearOnSecondClick:true});const clearPolicy=resolveInteractionPolicy(clearItem,test.context.config,"dataPoint");const payload=createInteractionPayload(clearItem,{rowIndices:[2]});executeComponentInteraction(clearPolicy,payload,test.context,{trigger:"click"});executeComponentInteraction(clearPolicy,payload,test.context,{trigger:"click"});expect(test.clearExternal).toHaveBeenCalled();expect(test.context.componentRows("source")).toEqual([]);});
    it("keeps internal behavior when the global external gate is off",()=>{const test=harness({...defaultConfig,interactions:{...defaultConfig.interactions,crossFilter:false}});const item=component({enabled:true,externalMode:"selection",internalMode:"filter",field:"status"});executeComponentInteraction(resolveInteractionPolicy(item,test.context.config,"dataPoint"),createInteractionPayload(item,{rowIndices:[0,2],field:"status",value:"Open"}),test.context,{trigger:"click"});expect(test.context.state.interactionFilters).toHaveLength(1);expect(test.selectExternal).not.toHaveBeenCalled();expect(test.reportInteraction).toHaveBeenCalledWith(expect.any(Object),"interactions disabled",[0,2]);});
    it("reports an ambiguous filter field and explicit clearing",()=>{const test=harness();const item=component({enabled:true,externalMode:"filter",internalMode:"none"});const policy=resolveInteractionPolicy(item,test.context.config,"dataPoint");executeComponentInteraction(policy,createInteractionPayload(item,{rowIndices:[0]}),test.context,{trigger:"click"});expect(test.reportInteraction).toHaveBeenCalledWith(expect.any(Object),"field has no Power BI filter target",[0]);clearComponentInteraction(policy,"source",test.context);expect(test.clearExternalFilter).toHaveBeenCalled();});
});

describe("universal component adapters",()=>{
    it("assigns every catalog type to one family adapter",()=>{for(const metadata of componentCatalog)expect(componentKindForType(metadata.type)).toMatch(/control|dataPoint|display|navigation|layout|content|custom/);});
    it("allows table row clicks with the selector hidden",()=>{const host=document.createElement("div");const selectExternal=vi.fn(()=>({sent:true as const}));render(h(HyperPbiRoot,{instanceId:"hidden-selector",schema:{version:"1.0",components:[{type:"table",id:"records",columns:["status"],interaction:{enabled:true,showSelector:false,internalMode:"none",externalMode:"selection"}}]},data,settings:toRuntimeSettings(new VisualFormattingSettingsModel()),renderMs:0,selectExternal}),host);expect(host.querySelector("input[aria-label='Select row']")).toBeNull();(host.querySelector("tbody tr") as HTMLElement).click();expect(selectExternal).toHaveBeenCalledWith([0],false,expect.any(Object));});
    it("supports keyboard interaction and prevents parent/child duplicate execution",()=>{const host=document.createElement("div");const selectExternal=vi.fn(()=>({sent:true as const}));const policy={enabled:true,trigger:"click" as const,internalMode:"none" as const,externalMode:"selection" as const,field:"status",value:"Open"};const schema:HyperPbiSchema={version:"1.0",components:[{type:"grid",id:"parent",interaction:policy,children:[{type:"text",id:"child",text:"Open",interaction:policy}]}]};render(h(HyperPbiRoot,{instanceId:"event-guard",schema,data,settings:toRuntimeSettings(new VisualFormattingSettingsModel()),renderMs:0,selectExternal}),host);const child=host.querySelector("[data-hp-id='child']") as HTMLElement;child.dispatchEvent(new KeyboardEvent("keydown",{key:"Enter",bubbles:true}));expect(selectExternal).toHaveBeenCalledTimes(1);});
    it("warns when an enabled display component cannot create a payload",()=>{const schema={version:"1.0" as const,components:[{type:"alert",id:"alert",text:"Notice",interaction:{enabled:true,externalMode:"selection" as const}}]};expect(validateReferences(schema,data).join(" ")).toContain("no usable field, value, or row payload");});
});
