import type { DataRow } from "../../data/normalizeData";
import type { DashboardState } from "../../render/stateStore";
import type { SvgBoundValue, SvgConditionDefinition, SvgDataContextDefinition, SvgPrimitive, SvgValue } from "./svgTypes";
import { resolveSvgScale } from "./svgScales";

export interface SvgBindingContext { row: DataRow; rows: DataRow[]; state: DashboardState; index?: number; count?: number; warnings?: string[]; }
const object = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
const fieldValue = (field: string, context: SvgBindingContext): unknown => field === "$index" ? context.index ?? 0 : field === "$count" ? context.count ?? context.rows.length : context.row[field];
const compare = (condition: SvgConditionDefinition, context: SvgBindingContext): boolean => { const left = fieldValue(condition.field, context), right = condition.value; switch (condition.operator) { case "=": return left === right || String(left) === String(right); case "!=": return !(left === right || String(left) === String(right)); case ">": return Number(left) > Number(right); case ">=": return Number(left) >= Number(right); case "<": return Number(left) < Number(right); case "<=": return Number(left) <= Number(right); case "contains": return String(left ?? "").includes(String(right ?? "")); case "in": return Array.isArray(right) && right.some(item => String(item) === String(left)); case "between": return Array.isArray(right) && right.length === 2 && Number(left) >= Number(right[0]) && Number(left) <= Number(right[1]); } };
export const renderSvgTemplate = (template: string, context: SvgBindingContext): string => template.replace(/\{\{\s*([A-Za-z_$][\w$.-]*)\s*\}\}/g, (_match, token: string) => { const key = token.startsWith("row.") ? token.slice(4) : token.startsWith("state.") ? token.slice(6) : token; const value = token.startsWith("state.") ? context.state.values[key] : fieldValue(key, context); if (value === undefined) { context.warnings?.push(`SVG template field “${token}” was not found.`); return ""; } return String(value); });
function resolveBound(value: SvgBoundValue, context: SvgBindingContext): SvgPrimitive {
    if (value.when) return compare(value.when, context) ? value.then ?? null : value.else ?? null;
    if (value.state) { const actual = context.state.values[value.state], expected = object(value.equals) && typeof value.equals.template === "string" ? renderSvgTemplate(value.equals.template, context) : value.equals; return String(actual) === String(expected) ? value.then ?? true : value.else ?? false; }
    if (value.template !== undefined) return renderSvgTemplate(value.template, context);
    if (value.bind !== undefined) { const raw = fieldValue(value.bind, context); if (raw === undefined) context.warnings?.push(`SVG field “${value.bind}” was not found.`); if (value.map) return value.map[String(raw)] ?? value.fallback ?? null; if (value.scale) return resolveSvgScale(raw, value.scale, context.rows.map(row => value.bind ? row[value.bind] : undefined)); return raw == null || ["string", "number", "boolean"].includes(typeof raw) ? raw as SvgPrimitive : String(raw); }
    return value.fallback ?? null;
}
export function resolveSvgValue(value: SvgValue | undefined, context: SvgBindingContext): SvgPrimitive | undefined { if (value === undefined) return undefined; return object(value) ? resolveBound(value as SvgBoundValue, context) : value as SvgPrimitive; }
export function compileSvgPosition(position: { x?: SvgValue; y?: SvgValue; rotate?: SvgValue; scale?: SvgValue } | undefined, context: SvgBindingContext): string | undefined { if (!position) return undefined; const x = Number(resolveSvgValue(position.x, context) ?? 0), y = Number(resolveSvgValue(position.y, context) ?? 0), rotate = Number(resolveSvgValue(position.rotate, context) ?? 0), scale = Number(resolveSvgValue(position.scale, context) ?? 1); if (![x, y, rotate, scale].every(Number.isFinite)) { context.warnings?.push("SVG position contains a nonnumeric value."); return undefined; } return `translate(${x} ${y}) rotate(${rotate}) scale(${scale})`; }
export function aggregateSvgRow(rows: DataRow[]): DataRow { const keys = new Set(rows.flatMap(row => Object.keys(row))); const result: DataRow = {}; for (const key of keys) { const values = rows.map(row => row[key]).filter(value => value !== null && value !== undefined); const numeric = values.length > 0 && values.every(value => typeof value === "number" && Number.isFinite(value)); result[key] = numeric ? (values as number[]).reduce((sum, value) => sum + value, 0) : values[0] ?? null; } return result; }
export function resolveSvgDataContextRow(dataContext: SvgDataContextDefinition | undefined, rows: DataRow[], rowKeys: string[], selectedKeys: string[], warnings: string[]): DataRow { const mode = dataContext?.mode ?? "aggregate"; if (mode === "selectedRow") { const selected = selectedKeys.length ? rowKeys.indexOf(selectedKeys[0]) : -1; if (selected >= 0) return rows[selected]; warnings.push("SVG selectedRow context has no selected row; aggregate context was used."); return aggregateSvgRow(rows); } if (mode === "first") { const sorted = [...rows]; if (dataContext?.sortBy) { const field = dataContext.sortBy, direction = dataContext.sortDirection === "asc" ? 1 : -1; sorted.sort((a, b) => String(a[field] ?? "").localeCompare(String(b[field] ?? ""), undefined, { numeric: true }) * direction); } else if (rows.length > 1) warnings.push("SVG first-row context is nondeterministic without sortBy."); return sorted[0] ?? {}; } return aggregateSvgRow(rows); }
