import { componentCategories, componentsByCategory } from "../../catalog/componentCatalog";
import { customComponentTemplates } from "../../components/custom/customComponentTemplates";
import { copyText } from "../textActions";
import { minimalDashboardJson } from "../../ai/minimalDashboard";
import { componentJsonExample } from "../../catalog/componentJsonExamples";

const capabilityLabels:Record<string,string>={fields:"Fields",calculations:"Calc",css:"CSS",slots:"Slots",interactions:"Click",externalSelection:"Power BI",customHtml:"HTML"};
export function AiPromptComponentReference({fieldKeys=[]}:{fieldKeys?:string[]}) {
    return <details class="hp-ai-details hp-catalog"><summary>Component catalog & safe custom templates</summary><p>Each expandable example is a complete, production-oriented configuration. Replace every <code>__...field_key__</code> placeholder with a normalized Power BI field key.</p><section class="hp-minimal-dashboard"><strong>Minimal dashboard JSON</strong><pre>{minimalDashboardJson}</pre><button type="button" onClick={()=>void copyText(minimalDashboardJson)}>Copy minimal dashboard JSON</button></section>{componentCategories.map(category=><details open={category==="Display"}><summary>{category}</summary><div class="hp-catalog-grid">{componentsByCategory(category).map(component=>{const example=componentJsonExample(component.type);return <article class={`hp-level-${component.level}`}><header><strong>{component.label}</strong><code>{component.type}</code></header><p>{component.useWhen}</p><div>{Object.entries(component.capability).filter(([,enabled])=>enabled).map(([key])=><span>{capabilityLabels[key]}</span>)}</div><details class="hp-component-json"><summary>Complete component JSON</summary><pre>{example}</pre><button type="button" onClick={()=>void copyText(example)}>Copy component JSON</button></details></article>;})}</div></details>)}<section class="hp-template-gallery"><h4>Custom component templates</h4><div>{customComponentTemplates(fieldKeys).map(template=><article><strong>{template.name}</strong><span>{template.description}</span><button type="button" onClick={()=>void copyText(JSON.stringify(template.component,null,2))}>Copy component JSON</button></article>)}</div></section></details>;
}
