import { AiPromptSettings } from "../../ai/aiPromptSettings";
import { builderAudiences, builderComponentOptions, dashboardGoals, layoutPatterns, stylePresetOptions } from "../builder/builderState";

const ChoiceGrid=({items,value,onChoose}:{items:string[];value:string;onChoose:(item:string)=>void})=><div class="hp-choice-grid">{items.map(item=><button type="button" class={value===item?"is-selected":""} onClick={()=>onChoose(item)}>{item}</button>)}</div>;
export function AiPromptSettingsPanel({ value, fields, onChange }: { value: AiPromptSettings; fields: string[]; onChange: (value: AiPromptSettings) => void }) {
    const update = <K extends keyof AiPromptSettings>(key: K, next: AiPromptSettings[K]) => onChange({ ...value, [key]: next });
    const toggle=(item:string)=>{const components=value.components.includes(item)?value.components.filter(existing=>existing!==item):[...value.components,item];onChange({...value,components,externalInteractions:components.includes("External Power BI selection"),mapRequired:components.includes("Map"),tableRequired:components.includes("Table"),chartsRequired:components.includes("Charts")||components.includes("Advanced ECharts"),controlsRequired:components.includes("Search box")||components.includes("Filters/selectors")});};
    return <div class="hp-builder-choices">
        <section><header><span>1</span><div><strong>Dashboard goal</strong><small>Choose the closest outcome.</small></div></header><ChoiceGrid items={dashboardGoals} value={value.goal} onChoose={item=>update("goal",item)}/><label class="hp-builder-custom"><span>Or describe it</span><input value={value.goal} onInput={event=>update("goal",event.currentTarget.value)}/></label></section>
        <section><header><span>2</span><div><strong>Audience</strong><small>Sets density and explanation level.</small></div></header><ChoiceGrid items={builderAudiences} value={value.audience} onChoose={item=>update("audience",item)}/></section>
        <section><header><span>3</span><div><strong>Layout pattern</strong><small>Start with a proven information hierarchy.</small></div></header><ChoiceGrid items={layoutPatterns} value={value.layoutPattern} onChoose={item=>update("layoutPattern",item)}/></section>
        <section><header><span>4</span><div><strong>Components</strong><small>Select only what supports the decision.</small></div></header><div class="hp-builder-toggles">{builderComponentOptions.map(item=><label><input type="checkbox" checked={value.components.includes(item)} onChange={()=>toggle(item)}/><span>{item}</span></label>)}</div></section>
        <section><header><span>5</span><div><strong>Style preset</strong><small>Professional tokens and component guidance.</small></div></header><ChoiceGrid items={stylePresetOptions} value={value.stylePreset} onChoose={item=>onChange({...value,stylePreset:item,designStyle:item})}/></section>
        <details class="hp-builder-data-options"><summary>Data privacy & field options</summary><div class="hp-form-grid"><label><span>Privacy</span><select value={value.privacyMode} onChange={event=>update("privacyMode",event.currentTarget.value as AiPromptSettings["privacyMode"])}><option value="fields">Field dictionary only</option><option value="samples">Sample rows</option><option value="masked">Masked samples</option><option value="summary">Summary only</option><option value="types">Types only</option></select></label><label><span>Sample rows</span><input type="number" min="1" max="50" value={value.sampleRows} onInput={event=>update("sampleRows",Math.min(50,Math.max(1,Number(event.currentTarget.value))))}/></label></div><label><span>Fields (empty means all)</span><select multiple onChange={event=>update("selectedFields",Array.from(event.currentTarget.selectedOptions).map(option=>option.value))}>{fields.map(field=><option value={field} selected={value.selectedFields.includes(field)}>{field}</option>)}</select></label></details>
    </div>;
}
