import { AiPromptSettings, promptComponentOptions } from "../../ai/aiPromptSettings";
export function AiPromptSettingsPanel({ value, fields, onChange }: { value: AiPromptSettings; fields: string[]; onChange: (value: AiPromptSettings) => void }) {
    const update = <K extends keyof AiPromptSettings>(key: K, next: AiPromptSettings[K]) => onChange({ ...value, [key]: next });
    return <div class="hp-ai-settings">
        <label><span>Dashboard goal</span><input value={value.goal} onInput={event => update("goal", event.currentTarget.value)} /></label>
        <div class="hp-form-grid"><label><span>Audience</span><select value={value.audience} onChange={event => update("audience", event.currentTarget.value)}>{["Executive","Manager","Engineer","Analyst","Field operations","Public-facing","Internal technical"].map(item=><option>{item}</option>)}</select></label><label><span>Design style</span><select value={value.designStyle} onChange={event => update("designStyle", event.currentTarget.value)}>{["Enterprise compact","Executive","Operations center","GIS/map-centric","Dense analyst view"].map(item=><option>{item}</option>)}</select></label><label><span>Privacy mode</span><select value={value.privacyMode} onChange={event => update("privacyMode", event.currentTarget.value as AiPromptSettings["privacyMode"])}><option value="fields">Field dictionary only</option><option value="samples">Sample rows</option><option value="masked">Masked samples</option><option value="summary">Summary only</option><option value="types">Types only</option></select></label><label><span>Rows (max 50)</span><input type="number" min="1" max="50" value={value.sampleRows} onInput={event => update("sampleRows", Math.min(50,Math.max(1,Number(event.currentTarget.value))))} /></label></div>
        <details class="hp-ai-advanced-options"><summary>Advanced dashboard requirements</summary><fieldset><legend>Requested components</legend><div class="hp-check-grid">{promptComponentOptions.map(item=><label><input type="checkbox" checked={value.components.includes(item)} onChange={event => update("components",event.currentTarget.checked?[...value.components,item]:value.components.filter(existing=>existing!==item))}/><span>{item}</span></label>)}</div></fieldset>
        <fieldset><legend>Requirements</legend><div class="hp-check-grid">{[["mapRequired","Map required"],["tableRequired","Table required"],["chartsRequired","Charts required"],["controlsRequired","Controls required"],["calculationsRequired","Calculations required"],["externalInteractions","External Power BI interactions"]].map(([key,label])=><label><input type="checkbox" checked={Boolean(value[key as keyof AiPromptSettings])} onChange={event=>update(key as keyof AiPromptSettings,event.currentTarget.checked as never)}/><span>{label}</span></label>)}</div></fieldset>
        <label><span>Selected fields (Ctrl/Cmd to select; empty means all)</span><select multiple onChange={event=>update("selectedFields",Array.from(event.currentTarget.selectedOptions).map(option=>option.value))}>{fields.map(field=><option value={field} selected={value.selectedFields.includes(field)}>{field}</option>)}</select></label></details>
    </div>;
}
