import { useMemo, useState } from "preact/hooks";
import { buildAiPrompt } from "../../ai/buildAiPrompt";
import { defaultAiPromptSettings } from "../../ai/aiPromptSettings";
import { fieldDictionaryForPrompt } from "../../ai/fieldDictionaryForPrompt";
import { promptQualityChecks } from "../../ai/promptQualityChecks";
import { NormalizedData } from "../../data/normalizeData";
import { InteractionDiagnostics } from "../../powerbi/interactionDiagnostics";
import { InteractionsPanel } from "../InteractionsPanel";
import { copyText, downloadText } from "../textActions";
import { AiPromptChecklist } from "./AiPromptChecklist";
import { AiPromptComponentReference } from "./AiPromptComponentReference";
import { AiPromptFieldSummary } from "./AiPromptFieldSummary";
import { AiPromptPreview } from "./AiPromptPreview";
import { AiPromptSampleRows } from "./AiPromptSampleRows";
import { AiPromptSettingsPanel } from "./AiPromptSettingsPanel";
import { AiResponseImporter } from "./AiResponseImporter";
import { composeAiPrompt } from "../../ai/promptComposer";
import { fieldManifestForPrompt } from "../../ai/fieldManifestForPrompt";
import { parseConfig } from "../../config/hyperpbiConfig";

export function AiPromptTab({data,currentSpecification,configuration,onConfigurationChange,onApply,onPreview,previewReady,diagnostics,selectedComponentId,selectedComponentType,selectedComponentTitle,selectedComponentPath}:{data:NormalizedData;currentSpecification:string;configuration:string;onConfigurationChange:(json:string)=>void;onApply:(json:string,merge:boolean,configJson?:string)=>void;onPreview:(json:string,configJson?:string)=>boolean;previewReady:boolean;diagnostics:InteractionDiagnostics;selectedComponentId?:string;selectedComponentType?:string;selectedComponentTitle?:string;selectedComponentPath?:string}){
    const [settings,setSettings]=useState(()=>({...defaultAiPromptSettings,aliasOverrides:parseConfig(configuration).config?.fields?.aliases??{}}));const [generated,setGenerated]=useState("");const [copyStatus,setCopyStatus]=useState("");const context={width:window.innerWidth,height:window.innerHeight,currentSpecification,selectedComponentId,selectedComponentType,selectedComponentTitle,selectedComponentPath,insertionTargetId:selectedComponentId,insertionPosition:"inside" as const};let composition;try{composition=composeAiPrompt(data,settings,context);}catch(error){composition={prompt:"",includedModules:[],excludedModules:[],approximateTokens:0,warnings:[error instanceof Error?error.message:String(error)],fieldAliases:[]};}const prompt=generated||composition.prompt;const checks=useMemo(()=>promptQualityChecks(prompt,settings),[prompt,settings]);
    const changeSettings=(next:typeof settings)=>{setSettings(next);if(next.aliasOverrides!==settings.aliasOverrides){const config=parseConfig(configuration).config;if(config)onConfigurationChange(JSON.stringify({...config,fields:{...config.fields,aliases:next.aliasOverrides}},null,2));}};
    const copyPrompt=async()=>{try{const next=buildAiPrompt(data,settings,context);setGenerated(next);const copied=await copyText(next);setCopyStatus(copied?"Prompt copied. Paste it into your preferred AI.":"Copy was blocked; open Review generated prompt and copy manually.");}catch(error){setCopyStatus(error instanceof Error?error.message:String(error));}};
    return <div class="hp-guided-builder"><header class="hp-builder-intro"><div><span>GUIDED BUILDER</span><h2>Build a professional dashboard without editing JSON</h2><p>Bind fields in Power BI, describe the dashboard, copy the AI prompt, paste the AI response, preview, and save.</p></div><div><strong>{Object.keys(data.fields).length}</strong><span>fields ready</span><strong>{data.rows.length.toLocaleString()}</strong><span>rows available</span></div></header><div class="hp-builder-grid"><aside class="hp-builder-support-column"><AiPromptFieldSummary data={data} onCopy={()=>void copyText(JSON.stringify(fieldManifestForPrompt(data,[],settings.privacyMode,settings.aliasOverrides),null,2))}/><AiPromptSampleRows data={data}/></aside><main class="hp-builder-workflow-column"><AiPromptSettingsPanel value={settings} fields={Object.keys(data.fields)} onChange={changeSettings} selectedTarget={selectedComponentId?`${selectedComponentId} (${selectedComponentType??"component"})`:undefined}/><section class="hp-builder-step hp-copy-prompt"><header><span>6</span><div><strong>Generate AI prompt</strong><small>HyperPBI combines your choices, safe engine rules, application patterns, and field aliases.</small></div></header><button class="hp-primary-action" type="button" disabled={(settings.job==="redesign-section"||settings.job==="add-section")&&!selectedComponentId} onClick={()=>void copyPrompt()}>Copy AI Prompt</button>{copyStatus&&<p>{copyStatus}</p>}<details><summary>Review generated prompt</summary><div class="hp-prompt-review"><strong>Included modules:</strong> {composition.includedModules.join(", ")}<br/><strong>Excluded modules:</strong> {composition.excludedModules.join(", ")}<br/><strong>Field aliases:</strong> {composition.fieldAliases.join(", ")}<br/><strong>Privacy mode:</strong> {settings.privacyMode}<br/><strong>Approximate size:</strong> {composition.approximateTokens.toLocaleString()} tokens{composition.warnings.map(item=><p>{item}</p>)}</div><AiPromptPreview prompt={prompt} onCopy={()=>void copyText(prompt)} onDownload={()=>downloadText(prompt,"hyperpbi-ai-prompt.txt")}/><AiPromptChecklist checks={checks}/></details></section><AiResponseImporter data={data} currentSpecification={currentSpecification} aliasOverrides={settings.aliasOverrides} onApply={onApply} onPreview={onPreview}/><section class={`hp-builder-step hp-save-ready ${previewReady?"is-ready":""}`}><header><span>8</span><div><strong>Save to Power BI</strong><small>{previewReady?"Validation passed. Use Save & return in the header.":"Save becomes available after a successful preview."}</small></div></header><div>{previewReady?"✓ Ready to save":"Waiting for a valid preview"}</div></section><details class="hp-builder-support"><summary>Interaction status</summary><InteractionsPanel diagnostics={diagnostics} compact/></details><AiPromptComponentReference fieldKeys={composition.fieldAliases}/></main></div></div>;
}
