import { componentCategories, componentsByCategory } from "../../catalog/componentCatalog";
import { customComponentTemplates } from "../../components/custom/customComponentTemplates";
import { copyText } from "../textActions";
import { minimalDashboardJson } from "../../ai/minimalDashboard";
import { componentJsonExample, componentJsonExamples, universalInteractionReference } from "../../catalog/componentJsonExamples";

const capabilityLabels:Record<string,string>={fields:"Fields",calculations:"Calc",css:"CSS",slots:"Slots",interactions:"Click",externalSelection:"Power BI",customHtml:"HTML"};
export function AiPromptComponentReference({fieldKeys=[]}:{fieldKeys?:string[]}) {
    const interactionJson=JSON.stringify(universalInteractionReference,null,2);
    return <details class="hp-ai-details hp-catalog"><summary>Component catalog & safe custom templates</summary><p>Each expandable example is a canonical component fragment. Replace every <code>__...field_key__</code> placeholder with an alias from the current Field Manifest; the component must validate in its selected dataset scope.</p><section class="hp-interaction-reference"><strong>Universal interaction reference</strong><p>Internal behavior affects HyperPBI; external behavior affects Power BI. An interaction object is optional; when present, component policy overrides Runtime Config.</p><pre>{interactionJson}</pre><button type="button" onClick={()=>void copyText(interactionJson)}>Copy interaction JSON</button></section><section class="hp-minimal-dashboard"><strong>Minimal version 2.0 dashboard JSON</strong><pre>{minimalDashboardJson}</pre><button type="button" onClick={()=>void copyText(minimalDashboardJson)}>Copy minimal dashboard JSON</button></section>{componentCategories.map(category=><details open={category==="Display"}><summary>{category}</summary><div class="hp-catalog-grid">{componentsByCategory(category).map(component=>{const example=componentJsonExample(component.type);const interaction=componentJsonExamples[component.type].interaction as Record<string,unknown>;return <article class={`hp-level-${component.level}`}><header><strong>{component.label}</strong><code>{component.type}</code></header><p>{component.useWhen}</p><div>{Object.entries(component.capability).filter(([,enabled])=>enabled).map(([key])=><span>{capabilityLabels[key]}</span>)}</div><dl class="hp-interaction-summary"><dt>Example interaction</dt><dd>Enabled: {String(interaction.enabled)}</dd><dd>Trigger: {String(interaction.trigger??component.interaction.naturalTrigger)}</dd><dd>Internal: {String(interaction.internalMode)} / {String(interaction.internalScope??"all")}</dd><dd>External: {String(interaction.externalMode)}</dd><dd>Field: {String(interaction.field??"payload-derived")}</dd><dd>Selector: {String(interaction.showSelector??false)}</dd></dl><details class="hp-component-json"><summary>Canonical component fragment</summary><pre>{example}</pre><button type="button" onClick={()=>void copyText(example)}>Copy component JSON</button></details></article>;})}</div></details>)}<section class="hp-template-gallery"><h4>Custom component templates</h4><div>{customComponentTemplates(fieldKeys).map(template=><article><strong>{template.name}</strong><span>{template.description}</span><button type="button" onClick={()=>void copyText(JSON.stringify(template.component,null,2))}>Copy component JSON</button></article>)}</div></section></details>;
}
