import { useState } from "preact/hooks";
import { applyChangePackage } from "../../ai/applyChangePackage";
import { buildRepairPrompt } from "../../ai/buildRepairPrompt";
import { isAiChangePackage } from "../../ai/changePackage";
import { validateAiChangePackage } from "../../ai/changePackageValidation";
import { extractJsonFromAiResponse } from "../../ai/extractJsonFromAiResponse";
import { minimalDashboardJson } from "../../ai/minimalDashboard";
import { validateAiGeneratedSpec } from "../../ai/validateAiGeneratedSpec";
import { parseConfig } from "../../config/hyperpbiConfig";
import type { NormalizedData } from "../../data/normalizeData";
import type { HyperPbiSchema } from "../../schema/hyperpbiSchema";
import { copyText } from "../textActions";

export function buildAiImportErrorLog(response:string,json:string,errors:string[],warnings:string[],message:string):string{return[`Timestamp: ${new Date().toISOString()}`,`Message: ${message||"No message"}`,"Errors:",...(errors.length?errors.map(error=>`- ${error}`):["- None"]),"Warnings:",...(warnings.length?warnings.map(warning=>`- ${warning}`):["- None"]),"Extracted/repaired JSON:",json||"(none)","Original pasted AI response:",response||"(empty)"].join("\n");}

export function AiResponseImporter({data,currentSpecification,aliasOverrides={},onApply,onPreview}:{data:NormalizedData;currentSpecification:string;aliasOverrides?:Record<string,string>;onApply:(json:string,merge:boolean,configJson?:string)=>void;onPreview:(json:string,configJson?:string)=>boolean}){
    const [response,setResponse]=useState("");const [json,setJson]=useState("");const [configJson,setConfigJson]=useState<string>();const [errors,setErrors]=useState<string[]>([]);const [warnings,setWarnings]=useState<string[]>([]);const [message,setMessage]=useState("");const [summary,setSummary]=useState("");const [diagnostics,setDiagnostics]=useState<import("../../schema/diagnostics").Diagnostic[]>([]);const [repairs,setRepairs]=useState<import("../../schema/diagnostics").Diagnostic[]>([]);
    const inspect=()=>{const extracted=extractJsonFromAiResponse(response);if(extracted.error){setErrors([extracted.error]);setJson("");setMessage("Response could not be read.");return;}const configErrors=extracted.configJson?parseConfig(extracted.configJson).errors.map(error=>`Configuration: ${error}`):[];let applyJson=extracted.json??JSON.stringify(extracted.value);let previewJson=applyJson;let mutationSummary="Complete dashboard replacement.";let validation;
        if(isAiChangePackage(extracted.value)){const checked=validateAiChangePackage(extracted.value);if(!checked.package){setErrors([...checked.errors,...configErrors]);setSummary("");return;}let current:HyperPbiSchema;try{current=JSON.parse(currentSpecification) as HyperPbiSchema;}catch{setErrors(["The current dashboard is invalid; a targeted change cannot be applied."]);return;}const applied=applyChangePackage(current,checked.package);if(!applied.schema){setErrors(applied.errors);setSummary("No mutation applied.");return;}previewJson=JSON.stringify(applied.schema,null,2);mutationSummary=applied.summary;validation=validateAiGeneratedSpec(applied.schema,data,aliasOverrides);}else validation=validateAiGeneratedSpec(extracted.value,data,aliasOverrides);
        const nextJson=validation.authoring&&!isAiChangePackage(extracted.value)?JSON.stringify(validation.authoring,null,2):applyJson;setJson(nextJson);setConfigJson(extracted.configJson);setErrors([...validation.errors,...configErrors]);setWarnings(validation.warnings);setDiagnostics(validation.diagnostics);setRepairs(validation.repairs);setSummary(mutationSummary);return{applyJson:nextJson,previewJson,configJson:extracted.configJson,errors:[...validation.errors,...configErrors]};};
    const validateAndPreview=()=>{const result=inspect();if(!result||result.errors.length){setMessage("No changes were applied. Copy the repair prompt and correct the response.");return;}const rendered=onPreview(result.previewJson,result.configJson);if(rendered)onApply(result.applyJson,false,result.configJson);setMessage(rendered?"Resulting dashboard validated and previewed. Save & return is now available.":"No changes were applied because the resulting preview was invalid.");};const repair=buildRepairPrompt(json||response||currentSpecification,diagnostics.length?diagnostics:errors,data,warnings);
    return <section class="hp-ai-import hp-builder-step"><header><span>7</span><div><strong>Paste AI response</strong><small>Complete 2.0 dashboards and discriminated HyperPBI change packages are accepted.</small></div></header><textarea value={response} onInput={event=>setResponse(event.currentTarget.value)} placeholder="Paste a complete dashboard or hyperpbi-change package…"/><button class="hp-primary-action hp-validate-preview" type="button" onClick={validateAndPreview}>Validate resulting dashboard & Preview</button>{summary&&<div class="hp-mutation-summary"><strong>Mutation summary:</strong> {summary}</div>}{message&&<div class={`hp-import-message ${errors.length?"is-error":"is-ok"}`}>{message}</div>}{repairs.length>0&&<div class="hp-validation-list"><strong>Safe repairs performed</strong><ul>{repairs.map(item=><li>{item.message}</li>)}</ul></div>}{errors.length>0&&<section class="hp-repair-panel"><button type="button" onClick={()=>void copyText(buildAiImportErrorLog(response,json,errors,warnings,message))}>Copy error log</button><strong>Repair needed</strong><p>{errors[0]}</p><pre>{minimalDashboardJson}</pre><button type="button" onClick={()=>void copyText(repair)}>Copy repair prompt</button></section>}{warnings.length>0&&<div class="hp-validation-list"><strong>{warnings.length} note(s)</strong><ul>{warnings.map(warning=><li>{warning}</li>)}</ul></div>}<details class="hp-inline-advanced"><summary>Response options</summary><div class="hp-button-row"><button type="button" onClick={()=>inspect()}>Validate only</button><button type="button" onClick={()=>{setResponse("");setJson("");setConfigJson(undefined);setErrors([]);setWarnings([]);setDiagnostics([]);setRepairs([]);setMessage("");setSummary("");}}>Clear</button></div>{json&&<pre>{json}</pre>}</details></section>;
}
