import { useState } from "preact/hooks";
import { buildRepairPrompt } from "../../ai/buildRepairPrompt";
import { extractJsonFromAiResponse } from "../../ai/extractJsonFromAiResponse";
import { validateAiGeneratedSpec } from "../../ai/validateAiGeneratedSpec";
import { NormalizedData } from "../../data/normalizeData";
import { copyText } from "../textActions";

export function AiResponseImporter({ data, currentSpecification, onApply, onPreview }: { data: NormalizedData; currentSpecification: string; onApply: (json:string, merge:boolean)=>void; onPreview:(json:string)=>boolean }) {
    const [response,setResponse]=useState(""); const [json,setJson]=useState(""); const [errors,setErrors]=useState<string[]>([]); const [warnings,setWarnings]=useState<string[]>([]);const [message,setMessage]=useState("");
    const inspect=()=>{const result=extractJsonFromAiResponse(response);if(result.error){setErrors([result.error]);setWarnings([]);setMessage("Response could not be read.");return undefined;}const validation=validateAiGeneratedSpec(result.value,data);const nextJson=result.json??"";setJson(nextJson);setErrors(validation.errors);setWarnings(validation.warnings);return{json:nextJson,validation};};
    const validateAndPreview=()=>{const result=inspect();if(!result||result.validation.errors.length){setMessage("Copy the repair prompt, ask the AI to correct the response, then paste it again.");return;}onApply(result.json,false);const rendered=onPreview(result.json);setMessage(rendered?"Dashboard validated and previewed. Save & return is now available.":"Preview could not be rendered.");};
    const repair=buildRepairPrompt(json||response||currentSpecification,errors,data,warnings);
    return <section class="hp-ai-import hp-builder-step"><header><span>7</span><div><strong>Paste AI response</strong><small>Paste the complete response; extra prose and JSON fences are accepted.</small></div></header><textarea value={response} onInput={event=>setResponse(event.currentTarget.value)} placeholder="Paste the response from ChatGPT, Copilot, DeepSeek, or your approved AI here…"/><button class="hp-primary-action hp-validate-preview" type="button" onClick={validateAndPreview}>Validate & Preview</button>{message&&<div class={`hp-import-message ${errors.length?"is-error":"is-ok"}`}>{message}</div>}{errors.length>0&&<div class="hp-validation-list hp-validation-error"><strong>{errors.length} issue(s) found</strong><ul>{errors.map(error=><li>{error}</li>)}</ul><button type="button" onClick={()=>void copyText(repair)}>Copy repair prompt</button></div>}{warnings.length>0&&<div class="hp-validation-list"><strong>{warnings.length} note(s)</strong><ul>{warnings.map(warning=><li>{warning}</li>)}</ul>{errors.length===0&&<button type="button" onClick={()=>void copyText(repair)}>Copy repair prompt</button>}</div>}<details class="hp-inline-advanced"><summary>Response options</summary><div class="hp-button-row"><button type="button" onClick={()=>inspect()}>Validate only</button>{json&&<button disabled={errors.length>0} onClick={()=>onApply(json,true)}>Merge with current</button>}<button type="button" onClick={()=>{setResponse("");setJson("");setErrors([]);setWarnings([]);setMessage("");}}>Clear</button></div>{json&&<details><summary>Show extracted JSON</summary><pre>{json}</pre></details>}</details></section>;
}
