import { useState } from "preact/hooks";
import { buildRepairPrompt } from "../../ai/buildRepairPrompt";
import { extractJsonFromAiResponse } from "../../ai/extractJsonFromAiResponse";
import { validateAiGeneratedSpec } from "../../ai/validateAiGeneratedSpec";
import { NormalizedData } from "../../data/normalizeData";
import { copyText } from "../textActions";
import { minimalDashboardJson } from "../../ai/minimalDashboard";
import { parseConfig } from "../../config/hyperpbiConfig";

export function buildAiImportErrorLog(response:string,json:string,errors:string[],warnings:string[],message:string):string{return[`Timestamp: ${new Date().toISOString()}`,`Message: ${message||"No message"}`,"Errors:",...(errors.length?errors.map(error=>`- ${error}`):["- None"]),"Warnings:",...(warnings.length?warnings.map(warning=>`- ${warning}`):["- None"]),"Extracted/repaired JSON:",json||"(none)","Original pasted AI response:",response||"(empty)"].join("\n");}

export function AiResponseImporter({ data, currentSpecification, onApply, onPreview }: { data: NormalizedData; currentSpecification: string; onApply: (json:string, merge:boolean, configJson?:string)=>void; onPreview:(json:string,configJson?:string)=>boolean }) {
    const [response,setResponse]=useState(""); const [json,setJson]=useState(""); const [configJson,setConfigJson]=useState<string>(); const [errors,setErrors]=useState<string[]>([]); const [warnings,setWarnings]=useState<string[]>([]);const [message,setMessage]=useState("");
    const inspect=()=>{const result=extractJsonFromAiResponse(response);if(result.error){setJson("");setConfigJson(undefined);setErrors([result.error]);setWarnings([]);setMessage("Response could not be read.");return undefined;}const specValidation=validateAiGeneratedSpec(result.value,data);const configErrors=result.configJson?parseConfig(result.configJson).errors.map(error=>`Configuration: ${error}`):[];const validation={...specValidation,errors:[...specValidation.errors,...configErrors]};const nextJson=result.json??"";setJson(nextJson);setConfigJson(result.configJson);setErrors(validation.errors);setWarnings(validation.warnings);return{json:nextJson,configJson:result.configJson,validation};};
    const validateAndPreview=()=>{const result=inspect();if(!result||result.validation.errors.length){setMessage("Copy the repair prompt, ask the AI to correct the response, then paste it again.");return;}onApply(result.json,false,result.configJson);const rendered=onPreview(result.json,result.configJson);setMessage(rendered?"Dashboard validated and previewed. Save & return is now available.":"Preview could not be rendered.");};
    const repair=buildRepairPrompt(json||response||currentSpecification,errors,data,warnings);
    return <section class="hp-ai-import hp-builder-step"><header><span>7</span><div><strong>Paste AI response</strong><small>Paste the complete response; prose, fences, package exports, smart quotes, and trailing commas are accepted.</small></div></header><textarea value={response} onInput={event=>setResponse(event.currentTarget.value)} placeholder="Paste the response from ChatGPT, Copilot, DeepSeek, or your approved AI here…"/><button class="hp-primary-action hp-validate-preview" type="button" onClick={validateAndPreview}>Validate & Preview</button>{message&&<div class={`hp-import-message ${errors.length?"is-error":"is-ok"}`}>{message}</div>}{errors.length>0&&<section class="hp-repair-panel"><button class="hp-copy-error-log" type="button" onClick={()=>void copyText(buildAiImportErrorLog(response,json,errors,warnings,message))}>Copy error log</button><strong>Repair needed</strong><p>Detected reason: {errors[0]}</p><pre>{minimalDashboardJson}</pre><button type="button" onClick={()=>void copyText(repair)}>Copy repair prompt</button></section>}{warnings.length>0&&<div class="hp-validation-list"><strong>{warnings.length} note(s)</strong><ul>{warnings.map(warning=><li>{warning}</li>)}</ul>{errors.length===0&&<button type="button" onClick={()=>void copyText(repair)}>Copy repair prompt</button>}</div>}<details class="hp-inline-advanced"><summary>Response options</summary><div class="hp-button-row"><button type="button" onClick={()=>inspect()}>Validate only</button>{json&&<button disabled={errors.length>0} onClick={()=>onApply(json,true,configJson)}>Merge with current</button>}<button type="button" onClick={()=>{setResponse("");setJson("");setConfigJson(undefined);setErrors([]);setWarnings([]);setMessage("");}}>Clear</button></div>{json&&<details><summary>Show extracted JSON</summary><pre>{json}</pre></details>}</details></section>;
}
