export interface DashboardRecipe { id: string; title: string; layout: string; components: string; styling: string; interactions: string; }

export const dashboardRecipes: DashboardRecipe[] = [
    { id: "executive", title: "Executive overview", layout: "Header, 3–5 KPI cards, two decision charts, compact exception table", components: "metricGrid, bar/line chart, alert, table", styling: "Enterprise Light or Bright Modern; concise labels and restrained semantic color", interactions: "Charts and exception rows select externally; table uses highlight mode" },
    { id: "operations", title: "Operations dashboard", layout: "Compact filter toolbar, KPI strip, status charts, timeline, exception table", components: "searchBox, segmentedControl, metricGrid, barChart, timeline, table", styling: "Dense Compact with warning/danger only for exceptions", interactions: "Internal filters remain visible; external selection on charts and rows" },
    { id: "map", title: "Map-first dashboard", layout: "Filter drawer, map spanning 7–8 columns, selected detail drawer on the right", components: "filterDrawer, map, drawer, detailPanel, short table", styling: "Map Command Center; map dominates and supporting panels stay compact", interactions: "Map feature selection opens detail drawer and selects source identities" },
    { id: "detail", title: "Detail explorer", layout: "Search and pill filters, highlight-mode table, right slide-over detail panel", components: "searchBox, segmentedControl, table, drawer, detailPanel", styling: "Enterprise Light with high row readability", interactions: "Row click retains all rows, opens details, and selects externally" },
    { id: "kpi", title: "KPI monitoring", layout: "Dense KPI grid, threshold alerts, trend small multiples, short exceptions", components: "metricGrid, alert, gauge or lineChart, smallMultiples, table", styling: "Bright Modern or Dark Ops Center; strong number hierarchy", interactions: "KPI state is informational; trend/category clicks may select externally" },
    { id: "table", title: "Table-heavy reporting", layout: "Filter drawer, summary matrix, full-width paginated detail table", components: "filterDrawer, filterChips, matrix, table", styling: "Dense Compact; sticky headers and minimal chart decoration", interactions: "Use highlight mode when rows drive external report selection" },
    { id: "custom-slicer", title: "Custom slicer/list", layout: "Distinct compact list or pill row above main content", components: "custom repeat with distinctBy and sortBy", styling: "Selected wrappers use is-selected and hp-row-selected", interactions: "selectWhere compares field with valueFromRow; internal:false, external:true, externalMode:filter" },
    { id: "bright-theme", title: "Bright enterprise theme", layout: "Clear header/KPI/chart/detail hierarchy", components: "Standard enterprise component mix", styling: "White surfaces, blue/teal accents, subtle borders; no rainbow palettes", interactions: "Use one consistent selected-state color" },
    { id: "future-theme", title: "Futuristic light theme", layout: "Precise modular grid with technical but readable hierarchy", components: "KPI strip, advanced chart only when justified, detail table", styling: "Near-white/cyan, small radii, no neon glow or excessive gradients", interactions: "Cyan selection outline and explicit focus states" },
    { id: "dense-600", title: "Dense 600x500 Power BI visual", layout: "One compact header/filter row, 2–3 KPIs, one chart, one bounded table", components: "search/select, metricGrid, one chart, paginated table", styling: "6px gaps, 8px padding, short titles, legends hidden when redundant", interactions: "Keep lists/tables visible with highlight mode; avoid drawers wider than 320px" }
];

export const dashboardRecipePrompt = (): string => dashboardRecipes.map(recipe => `### ${recipe.title}\nLayout: ${recipe.layout}. Components: ${recipe.components}. Styling: ${recipe.styling}. Interaction: ${recipe.interactions}.`).join("\n\n");
