export interface DashboardRecipe { id: string; title: string; layout: string; components: string; styling: string; interactions: string; }

export const dashboardRecipes: DashboardRecipe[] = [
    { id: "executive", title: "Executive overview", layout: "Header, 3–5 KPI cards, two decision charts, compact exception table", components: "metricGrid, bar/line chart, alert, table", styling: "Enterprise Light or Bright Modern; concise labels and restrained semantic color", interactions: "Charts and exception rows select externally; table uses highlight mode" },
    { id: "operations", title: "Operations dashboard", layout: "Compact filter toolbar, KPI strip, status charts, timeline, exception table", components: "searchBox, segmentedControl, metricGrid, barChart, timeline, table", styling: "Dense Compact with warning/danger only for exceptions", interactions: "Internal filters remain visible; external selection on charts and rows" },
    { id: "professional-app", title: "Professional operations application", layout: "Compact navbar, collapsible sidebar, page header, KPI row, decision charts, exception table, detail offcanvas", components: "app shell, card, metricGrid, chart, table, offcanvas, dataGrid", styling: "Enterprise Light; professional sidebar with clear navigation hierarchy", interactions: "Table row click opens detail offcanvas; charts select externally" },
    { id: "command-center", title: "Executive command center", layout: "Minimal sidebar or horizontal navigation, page-header metadata, KPI strip, two decision visuals, short exception list", components: "app shell, card, metricGrid, barChart, lineChart, listGroup", styling: "Dark Ops Center; strong number hierarchy; minimal decorative content", interactions: "Charts select externally; exception list highlights internally" },
    { id: "record-explorer", title: "Record explorer", layout: "Search/filter toolbar, native table, selected-row offcanvas, data grid, row action dropdown", components: "app shell, table, offcanvas, dataGrid, dropdown", styling: "Enterprise Light with high table readability; compact cards", interactions: "Row click opens details offcanvas; data grid displays selected record fields" },
    { id: "map", title: "Map command center", layout: "Compact app shell, filter offcanvas, dominant map, exception list, selection detail panel", components: "app shell, map, offcanvas, listGroup, dataGrid", styling: "Map Command Center; map dominates and supporting panels stay compact", interactions: "Map feature selection opens detail panel and selects source identities" },
    { id: "detail", title: "Detail explorer", layout: "Search and pill filters, highlight-mode table, right slide-over detail panel", components: "searchBox, segmentedControl, table, drawer, detailPanel", styling: "Enterprise Light with high row readability", interactions: "Row click retains all rows, opens details, and selects externally" },
    { id: "kpi", title: "KPI monitoring", layout: "Dense KPI grid, threshold alerts, trend small multiples, short exceptions", components: "metricGrid, alert, gauge or lineChart, smallMultiples, table", styling: "Bright Modern or Dark Ops Center; strong number hierarchy", interactions: "KPI state is informational; trend/category clicks may select externally" },
    { id: "table", title: "Table-heavy reporting", layout: "Filter drawer, summary matrix, full-width paginated detail table", components: "filterDrawer, filterChips, matrix, table", styling: "Dense Compact; sticky headers and minimal chart decoration", interactions: "Use highlight mode when rows drive external report selection" },
    { id: "mobile-ops", title: "Mobile operations view", layout: "Navbar, offcanvas sidebar, stacked cards, compact list, no oversized table-first layout", components: "app shell, card, metricGrid, listGroup", styling: "Compact density; sidebar becomes offcanvas; cards stack vertically", interactions: "Tap targets sized for touch; minimal multi-select" },
    { id: "dense-tile", title: "Dense Power BI tile", layout: "No full app shell unless enough width; compact page header, 2–3 KPIs, one chart, bounded table", components: "metricGrid, one chart, table", styling: "Minimal gaps; no sidebar at narrow widths; compact card padding", interactions: "Charts use highlight mode; table uses auto selection" },
    { id: "custom-slicer", title: "Custom slicer/list", layout: "Distinct compact list or pill row above main content", components: "custom repeat with distinctBy and sortBy", styling: "Selection styling is optional", interactions: "selectWhere compares field with valueFromRow; interaction uses internalMode:none, externalMode:filter, and an explicit field" },
    { id: "bright-theme", title: "Bright enterprise theme", layout: "Clear header/KPI/chart/detail hierarchy", components: "Standard enterprise component mix", styling: "White surfaces, blue/teal accents, subtle borders; no rainbow palettes", interactions: "Use one consistent selected-state color" },
    { id: "future-theme", title: "Futuristic light theme", layout: "Precise modular grid with technical but readable hierarchy", components: "KPI strip, advanced chart only when justified, detail table", styling: "Near-white/cyan, small radii, no neon glow or excessive gradients", interactions: "Cyan selection outline and explicit focus states" },
    { id: "dense-600", title: "Dense 600x500 Power BI visual", layout: "One compact header/filter row, 2–3 KPIs, one chart, one bounded table", components: "search/select, metricGrid, one chart, paginated table", styling: "6px gaps, 8px padding, short titles, legends hidden when redundant", interactions: "Keep lists/tables visible with highlight mode; avoid drawers wider than 320px" }
];

export const dashboardRecipePrompt = (): string => dashboardRecipes.map(recipe => `### ${recipe.title}\nLayout: ${recipe.layout}. Components: ${recipe.components}. Styling: ${recipe.styling}. Interaction: ${recipe.interactions}.`).join("\n\n");

