import { componentPromptReference } from "../catalog/componentCatalog";
import { designPresets } from "../design/stylePresets";
import { dashboardRecipePrompt } from "./dashboardRecipes";

export const sharedComponentReference = `Shared component properties: id, span, className, props, style, css, slots, data, visibility, interactions (safe custom actions), interaction (universal behavior), uiAction (declarative navigation/overlay actions), variant (primary/secondary/success/warning/danger/ghost/outline), size (xs/sm/md/lg), disabled, tooltip, ariaLabel, icon, subtitle. Every new component MUST include interaction. Never generate deprecated component internal, external, selectable, or table selectionMode properties. Every id must be unique and ASCII-safe. span uses the responsive 12-column grid. Component css is parsed, allowlisted, and scoped beneath the component data-hp-id.`;
export const componentReference = `Component catalog (choose the smallest useful set; recommended components are preferred for normal dashboards):\n${componentPromptReference()}\n${sharedComponentReference}`;
export const appShellReference = `Application shell: Use root "app" for professional layout with navbar, sidebar, page header, footer, and navigation. App shell is declarative — do not rebuild it through custom HTML. Available: app.enabled, app.layout (vertical/horizontal), app.container (fluid/boxed), app.density (compact/normal), app.stickyHeader, app.contentPadding (none/compact/normal). brand.title, brand.subtitle, brand.icon, brand.shortTitle. navbar.visible, navbar.showSidebarToggle, navbar.showSearch, navbar.actions[], navbar.user (name, initials, status, menu[]). sidebar.visible, sidebar.width, sidebar.collapsedWidth, sidebar.collapsible, sidebar.navigation[]. sidebar.footer. pageHeader.visible, pageHeader.title, pageHeader.subtitle, pageHeader.breadcrumbs[], pageHeader.meta[], pageHeader.actions[]. footer.visible, footer.text.`;
export const uiActionReference = `UI Actions (separate from data interactions): clearFilters, setTab(target,value), setState(target,value), toggleState(target), toggleSidebar, openOverlay(target), closeOverlay(target), toggleOverlay(target), setStep(target,value), nextStep(target), previousStep(target), showToast(title,message,intent,durationMs), dismissToast(target), scrollTo(target), refresh. UI actions never trigger Power BI filtering. Data interaction executes separately. A component may have both uiAction and interaction.`;
export const overlayReference = `Overlay rules: Every modal, offcanvas, drawer, filterDrawer, dropdown, and popover requires an explicit unique ID. Use dropdown for commands, popover for contextual interactive content, offcanvas for persistent details or filters, and modal only for focused blocking tasks. All render through the root OverlayHost with safe declarative actions, focus management, Escape/outside dismissal, and viewport-aware positioning. Use uiAction openOverlay/closeOverlay/toggleOverlay and target an existing overlay ID. Legacy drawer and filterDrawer are normalized to offcanvas.`;
export const stylingReference = `Styling: use theme tokens for color, density, radius, padding, and gap. styles.globalCss is sanitized visual-wide CSS. styles.components contains reusable rules keyed by *, component type, or #component_id; local component css wins. Available presets: ${designPresets.map(item => item.name).join(", ")}. Keep a strong header → KPI → filter → chart → detail hierarchy. Avoid random bright colors, excessive gradients, huge empty cards, cluttered charts, fixed widths, horizontal overflow, and decorative whitespace.`;
export const chartReference = `Chart rules: Prefer first-class semantic charts: barChart, horizontalBarChart, lineChart, areaChart, pieChart, donutChart, scatterChart, gauge, heatmap, comboChart, waterfallChart, sankeyChart, treemapChart, funnelChart, or radarChart. Their options may change presentation but cannot replace generated dataset, series data, links, nodes, encode, transforms, series types, or series counts. Use advancedChart only for an uncommon ECharts configuration no semantic chart can express. advancedChart accepts sanitized JSON-only ECharts 6 options. String formatter templates are allowed; JavaScript functions, event-handler keys, external URLs, and executable markup are not. Use bounded labels, responsive grids, and restrained colors.`;
export const tableReference = `Table rules: use table for row detail and matrix for summarized pivots. Keep columns purposeful. Row clicks work whenever interaction.enabled is true; interaction.showSelector only shows checkbox/radio UI. Use internalMode:"highlight" to retain rows, "filter" to apply scoped HyperPBI filtering, or "none" to keep the source unchanged. Auto external mode selects exact row identities. Never guess a table or matrix filter field; externalMode:"filter" requires explicit interaction.field. Use pagination and bounded maxRows. Tabulator is not bundled; HyperPBI native table is the supported engine. Use density (compact/normal), striped, hover, showRowCount, pageSizeOptions, rowActions, and emptyState for better tables. Columns support sortable, resizable, visible, wrap, frozen (left/right), cellType (text/badge/progress), and intentMap.`;
export const mapReference = `Map rules: Generate Power BI spatial maps (lat/lon, geometry, addresses) by default. Location priority: Geometry > Lat/Lon > X/Y > Address. The practical public ArcGIS REST runtime supports arcgisFeature FeatureServer/MapServer layers, Power BI joins, viewport queries, service or configured renderers, service or configured labels, arcgisTile overlays, and basic arcgisDynamic images. Never invent service URLs, layer IDs, service fields, hosts, or tokens. Public HTTPS services only; no authentication, editing, 3D, relationship/tracing workflows, advanced collision, density grids, or non-4326 output. Center order is [latitude, longitude]. Use the Maps build profile for external requests and package restricted custom hosts via HYPERPBI_MAP_HOSTS.`;
export const interactionReference = `Universal interaction schema: interaction:{enabled,trigger:"auto"|"click"|"change",internalMode:"none"|"highlight"|"filter",internalScope:"self"|"others"|"all",externalMode:"none"|"auto"|"selection"|"filter",field,operator,value,selectionMode:"replace"|"toggle"|"add",multiSelect,showSelector,clearOnSecondClick}. Internal and external behavior are independent. Auto means controls/slicers filter Power BI and row/data-point/item clicks select exact identities. Use internalMode:"none" when the source must not react. External filters require an explicit unambiguous model-column field for table, matrix, map, scatter, and advanced chart interactions; never guess. Use selection for rows/points/features and filter for field-value slicers. Runtime Config is only a global external gate/fallback; component interaction wins. Custom slicers use repeat.distinctBy and interactions.onClick selectWhere/valueFromRow, then pass their payload through the universal engine. Never generate deprecated component internal, external, selectable, or selectionMode properties. Never invent externalSelection, selectionTarget, crossFilter, or powerBISelection in dashboard JSON.`;
export const calculationReference = `Calculation DSL operators: +, -, *, /, %, round, floor, ceil, abs, min, max, =, !=, >, >=, <, <=, and, or, not, concat, contains, startsWith, endsWith, lower, upper, trim, replace, dateDiff, dateAdd, year, quarter, month, week, day, today, now, coalesce, isNull, isNotNull, if, case. Expressions are typed JSON objects containing field/value/op; never functions. Calculated fields and metrics can feed KPIs, charts, tables, matrix values, maps, templates, and conditions.`;
export const securityReference = `Security: no JavaScript, eval, new Function, functions, inline event handlers, event-handler strings, scripts, iframes, external scripts, unsafe URLs, CSS imports, or executable markup. Safe ECharts string formatter templates are allowed, but function callbacks are not. HTML is DOMPurify-sanitized. CSS is parsed, allowlisted, and scoped. Advanced ECharts options are recursively sanitized.`;
export const recipeReference = `Dashboard recipes:\n${dashboardRecipePrompt()}`;
export const specShape = `{"version":"1.0","title":"Dashboard","theme":{"mode":"light","density":"compact"},"styles":{"globalCss":".hp-card{border:1px solid var(--hp-border)}","components":{"*":{"style":{"minWidth":0}},"table":{"css":".hp-table th{font-weight:700}"}}},"calculations":{"fields":[],"metrics":[]},"components":[{"type":"metricGrid","id":"metrics","span":12,"metrics":[{"title":"Records","aggregation":"count"}],"interaction":{"enabled":false,"internalMode":"none","externalMode":"none"}},{"type":"table","id":"details","columns":["field_key"],"span":12,"interaction":{"enabled":true,"trigger":"auto","internalMode":"highlight","internalScope":"self","externalMode":"auto","selectionMode":"replace","multiSelect":true,"showSelector":true,"clearOnSecondClick":true}}]}`;
