import { CalculationMessage, CalculationSpecification, ExpressionNode } from "./calculationTypes";

const operators = new Set(["+","-","*","/","%","round","floor","ceil","abs","min","max","=","!=",">",">=","<","<=","and","or","not","concat","contains","startsWith","endsWith","lower","upper","trim","replace","dateDiff","dateAdd","year","quarter","month","week","day","today","now","coalesce","isNull","isNotNull","if","case"]);
function collect(node: ExpressionNode | undefined, fields: Set<string>, messages: CalculationMessage[], path: string): void {
    if (!node || typeof node !== "object") { messages.push({ level: "error", path, message: "Expression must be an object." }); return; }
    if ("field" in node) { fields.add(String(node.field)); return; }
    if ("value" in node) return;
    if (!("op" in node) || !operators.has(String(node.op))) messages.push({ level: "error", path, message: `Unknown calculation operator: ${"op" in node ? String(node.op) : "missing"}.` });
    Object.entries(node).forEach(([key, value]) => { if (key !== "op" && value && typeof value === "object") { if (Array.isArray(value)) value.forEach((item, index) => { if (item && typeof item === "object") Object.values(item as object).forEach(child => collect(child as ExpressionNode, fields, messages, `${path}.${key}[${index}]`)); }); else collect(value as ExpressionNode, fields, messages, `${path}.${key}`); } });
}
export function validateCalculations(specification: CalculationSpecification | undefined, baseFields: Iterable<string>): CalculationMessage[] {
    if (!specification) return [];
    const messages: CalculationMessage[] = []; const base = new Set(baseFields); const definitions = specification.fields ?? []; const keys = new Set<string>();
    definitions.forEach((definition, index) => { const key=typeof definition.key==="string"?definition.key.trim():"";if(!key){messages.push({level:"error",path:`fields[${index}].key`,message:"Calculated field key is required."});return;}if (!/^[a-z][a-z0-9_]*$/.test(key)) messages.push({ level:"error", path:`fields[${index}].key`, message:"Calculated field keys must use lowercase letters, numbers, and underscores." }); if (base.has(key) || keys.has(key)) messages.push({ level:"error", path:`fields[${index}].key`, message:`Duplicate calculated field key: ${key}.` }); keys.add(key); });
    const dependencies = new Map<string, Set<string>>();
    definitions.forEach((definition, index) => { const key=typeof definition.key==="string"?definition.key.trim():"";const refs = new Set<string>(); collect(definition.expression, refs, messages, `fields[${index}].expression`);if(key)dependencies.set(key, new Set([...refs].filter(reference => keys.has(reference)))); refs.forEach(reference => { if (!base.has(reference) && !keys.has(reference)) messages.push({ level:"error", path:`fields[${index}].expression`, message:`Unknown field: ${reference}.` }); }); });
    const visiting = new Set<string>(); const visited = new Set<string>(); const visit = (key: string): boolean => { if (visiting.has(key)) return true; if (visited.has(key)) return false; visiting.add(key); if ([...(dependencies.get(key) ?? [])].some(visit)) return true; visiting.delete(key); visited.add(key); return false; };
    keys.forEach(key => { if (visit(key)) messages.push({ level:"error", path:"fields", message:`Cyclic calculated field dependency includes ${key}.` }); });
    const available = new Set([...base, ...keys]); const metricKeys = new Set<string>();const aggregations=new Set(["count","countWhere","sum","sumWhere","avg","avgWhere","min","max","distinctCount","ratio","percentOfTotal"]);
    (specification.metrics ?? []).forEach((metric, index) => { const key=typeof metric.key==="string"?metric.key.trim():"";if(!key)messages.push({level:"error",path:`metrics[${index}].key`,message:"Calculated metric key is required."});else if(metricKeys.has(key))messages.push({level:"error",path:`metrics[${index}].key`,message:`Duplicate metric key: ${key}.`});else metricKeys.add(key);if(!aggregations.has(String(metric.aggregation??"")))messages.push({level:"error",path:`metrics[${index}].aggregation`,message:`Unsupported or missing metric aggregation: ${String(metric.aggregation??"missing")}.`});if (metric.field && !available.has(metric.field)) messages.push({ level:"error", path:`metrics[${index}].field`, message:`Unknown field: ${metric.field}.` }); if (metric.where) { const refs = new Set<string>(); collect(metric.where, refs, messages, `metrics[${index}].where`); refs.forEach(reference => { if (!available.has(reference)) messages.push({ level:"error", path:`metrics[${index}].where`, message:`Unknown field: ${reference}.` }); }); } });
    return messages.filter((message, index, all) => all.findIndex(other => other.path === message.path && other.message === message.message) === index);
}
