export interface ComponentTreeItem { id:string;type:string;title?:string;depth:number;path:string; }
type Json=Record<string,unknown>;
const object=(value:unknown):value is Json=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const copy=<T>(value:T):T=>JSON.parse(JSON.stringify(value)) as T;
function childArrays(node:Json):unknown[][]{const arrays:unknown[][]=[];for(const key of ["children","footer"]){if(Array.isArray(node[key]))arrays.push(node[key] as unknown[]);}if(Array.isArray(node.tabs))for(const tab of node.tabs)if(object(tab)&&Array.isArray(tab.children))arrays.push(tab.children);if(node.type==="accordion"&&Array.isArray(node.items))for(const item of node.items)if(object(item)&&Array.isArray(item.children))arrays.push(item.children);return arrays;}
function rootArrays(root:Json):unknown[][]{return ["toolbar","leftPanel","components","rightPanel"].flatMap(key=>Array.isArray(root[key])?[root[key] as unknown[]]:[]);}
function locate(root:Json,id:string):{component:Json;parent:unknown[];index:number}|undefined{const visit=(items:unknown[]):ReturnType<typeof locate>=>{for(let index=0;index<items.length;index+=1){const item=items[index];if(!object(item))continue;if(item.id===id)return{component:item,parent:items,index};for(const children of childArrays(item)){const found=visit(children);if(found)return found;}}return undefined;};for(const items of rootArrays(root)){const result=visit(items);if(result)return result;}return undefined;}
export function componentTree(specification:unknown):ComponentTreeItem[]{if(!object(specification))return[];const result:ComponentTreeItem[]=[];const visit=(items:unknown[],depth:number,path:string)=>items.forEach((item,index)=>{if(!object(item))return;const id=typeof item.id==="string"?item.id:`${String(item.type)}-${index}`;result.push({id,type:String(item.type??"unknown"),title:typeof item.title==="string"?item.title:undefined,depth,path:`${path}/${index}`});childArrays(item).forEach((children,childIndex)=>visit(children,depth+1,`${path}/${index}/children-${childIndex}`));});rootArrays(specification).forEach((items,index)=>visit(items,0,`/root-${index}`));return result;}
export function updateComponent(specification:unknown,id:string,changes:Json):unknown{if(!object(specification))return specification;const next=copy(specification);const found=locate(next,id);if(found)Object.assign(found.component,changes);return next;}
export function deleteComponent(specification:unknown,id:string):unknown{if(!object(specification))return specification;const next=copy(specification);const found=locate(next,id);if(found)found.parent.splice(found.index,1);return next;}
export function moveComponent(specification:unknown,id:string,direction:-1|1):unknown{if(!object(specification))return specification;const next=copy(specification);const found=locate(next,id);if(found){const target=found.index+direction;if(target>=0&&target<found.parent.length){const [item]=found.parent.splice(found.index,1);found.parent.splice(target,0,item);}}return next;}
function collectIds(root:Json):Set<string>{return new Set(componentTree(root).map(item=>item.id));}
function uniqueId(base:string,ids:Set<string>):string{let index=2,candidate=`${base}-copy`;while(ids.has(candidate)){candidate=`${base}-copy-${index}`;index+=1;}ids.add(candidate);return candidate;}
function rekey(node:unknown,ids:Set<string>):void{if(!object(node))return;if(typeof node.id==="string")node.id=uniqueId(node.id,ids);childArrays(node).forEach(children=>children.forEach(child=>rekey(child,ids)));}
export function duplicateComponent(specification:unknown,id:string):unknown{if(!object(specification))return specification;const next=copy(specification);const found=locate(next,id);if(found){const duplicate=copy(found.component);rekey(duplicate,collectIds(next));found.parent.splice(found.index+1,0,duplicate);}return next;}
export function findComponent(specification:unknown,id:string):Json|undefined{if(!object(specification))return undefined;return locate(specification,id)?.component;}
