import {getComponentDescriptor} from "../../catalog/componentDescriptors";import {visitSpecificationComponents,type ComponentVisit} from "../../catalog/componentTraversal";
export interface ComponentTreeItem{id:string;type:string;title?:string;depth:number;path:string;containerPath:string;datasetName:string;}
type Json=Record<string,unknown>;export type ComponentLocation=ComponentVisit;const object=(value:unknown):value is Json=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);const copy=<T>(value:T):T=>JSON.parse(JSON.stringify(value)) as T;const pointer=(value:string)=>value.replace(/~/g,"~0").replace(/\//g,"~1");
export function locateComponent(specification:unknown,id:string):ComponentLocation|undefined{let found:ComponentLocation|undefined;visitSpecificationComponents(specification,visit=>{if(visit.component.id===id){found=visit;return true;}});return found;}
export function componentTree(specification:unknown):ComponentTreeItem[]{const result:ComponentTreeItem[]=[];visitSpecificationComponents(specification,visit=>{result.push({id:typeof visit.component.id==="string"?visit.component.id:`${String(visit.component.type)}-${result.length+1}`,type:String(visit.component.type),title:typeof visit.component.title==="string"?visit.component.title:undefined,depth:visit.depth,path:visit.path,containerPath:visit.containerPath,datasetName:visit.datasetName});});return result;}
export const findComponent=(specification:unknown,id:string)=>locateComponent(specification,id)?.component;
export function updateComponent(specification:unknown,id:string,changes:Json):unknown{if(!object(specification))return specification;const next=copy(specification);const found=locateComponent(next,id);if(found)Object.assign(found.component,changes);return next;}
export function deleteComponent(specification:unknown,id:string):unknown{if(!object(specification))return specification;const next=copy(specification);const found=locateComponent(next,id);if(found){if(Array.isArray(found.parent))found.parent.splice(found.index as number,1);else delete found.parent[found.index as string];}return next;}
export function moveComponent(specification:unknown,id:string,direction:-1|1):unknown{if(!object(specification))return specification;const next=copy(specification);const found=locateComponent(next,id);if(found&&Array.isArray(found.parent)){const target=(found.index as number)+direction;if(target>=0&&target<found.parent.length){const[item]=found.parent.splice(found.index as number,1);found.parent.splice(target,0,item);}}return next;}
const ids=(root:unknown)=>new Set(componentTree(root).map(item=>item.id));function unique(base:string,used:Set<string>){let candidate=`${base}-copy`,index=2;while(used.has(candidate))candidate=`${base}-copy-${index++}`;used.add(candidate);return candidate;}function rekey(node:unknown,used:Set<string>):void{if(!object(node))return;if(typeof node.id==="string")node.id=unique(node.id,used);const descriptor=getComponentDescriptor(String(node.type));for(const container of descriptor?.containers??[]){if(container.kind==="array"&&Array.isArray(node[container.property]))(node[container.property] as unknown[]).forEach(child=>rekey(child,used));else if(container.kind==="single")rekey(node[container.property],used);else if(container.kind==="tabs"&&Array.isArray(node.tabs)){const key=container.property.split(".")[1];node.tabs.forEach(tab=>{if(object(tab)&&Array.isArray(tab[key]))(tab[key] as unknown[]).forEach(child=>rekey(child,used));});}else if(container.kind==="accordion"&&Array.isArray(node.items)){const key=container.property.split(".")[1];node.items.forEach(item=>{if(object(item)&&Array.isArray(item[key]))(item[key] as unknown[]).forEach(child=>rekey(child,used));});}}}
export function duplicateComponent(specification:unknown,id:string):unknown{if(!object(specification))return specification;const next=copy(specification);const found=locateComponent(next,id);if(found&&Array.isArray(found.parent)){const duplicate=copy(found.component);rekey(duplicate,ids(next));found.parent.splice((found.index as number)+1,0,duplicate);}return next;}
export function incomingComponentReferences(specification:unknown,id:string):string[]{const result:string[]=[];const scan=(value:unknown,path:string):void=>{if(Array.isArray(value)){value.forEach((item,index)=>scan(item,`${path}/${index}`));return;}if(!object(value))return;for(const[key,child]of Object.entries(value)){const next=`${path}/${pointer(key)}`;if(["target","targets","componentId"].includes(key)&&(child===id||Array.isArray(child)&&child.includes(id)))result.push(next);scan(child,next);}};scan(specification,"");return result;}
function at(root:Json,path:string):unknown{let value:unknown=root;for(const part of path.split("/").slice(1).map(item=>item.replace(/~1/g,"/").replace(/~0/g,"~"))){if(Array.isArray(value))value=value[Number(part)];else if(object(value))value=value[part];else return;}return value;}
export function compatibleContainerPaths(specification:unknown):string[]{if(!object(specification))return[];const paths=["/components","/toolbar","/leftPanel","/rightPanel"].filter(path=>Array.isArray(at(specification,path)));visitSpecificationComponents(specification,visit=>{const descriptor=getComponentDescriptor(String(visit.component.type));for(const container of descriptor?.containers??[]){if(container.kind==="array")paths.push(`${visit.path}/${container.property}`);else if(container.kind==="tabs"&&Array.isArray(visit.component.tabs)){const key=container.property.split(".")[1];visit.component.tabs.forEach((_tab,index)=>paths.push(`${visit.path}/tabs/${index}/${key}`));}else if(container.kind==="accordion"&&Array.isArray(visit.component.items)){const key=container.property.split(".")[1];visit.component.items.forEach((_item,index)=>paths.push(`${visit.path}/items/${index}/${key}`));}}});return Array.from(new Set(paths));}
export function insertComponent(specification:unknown,targetId:string,position:"before"|"after",component:Json):unknown{if(!object(specification))return specification;const next=copy(specification);const found=locateComponent(next,targetId);if(!found||!Array.isArray(found.parent))return specification;found.parent.splice((found.index as number)+(position==="after"?1:0),0,copy(component));return next;}
export function appendToContainer(specification:unknown,containerPath:string,component:Json):unknown{if(!object(specification))return specification;const next=copy(specification);const target=at(next,containerPath);if(!Array.isArray(target))return specification;target.push(copy(component));return next;}
export function appendChild(specification:unknown,targetId:string,component:Json,container="children"):unknown{const location=locateComponent(specification,targetId);return location?appendToContainer(specification,`${location.path}/${container}`,component):specification;}
export function moveComponentTo(specification:unknown,id:string,containerPath:string,index?:number):unknown{if(!object(specification))return specification;const next=copy(specification);const found=locateComponent(next,id);const target=at(next,containerPath);if(!found||!Array.isArray(found.parent)||!Array.isArray(target)||target===found.parent)return specification;const[item]=found.parent.splice(found.index as number,1);target.splice(Math.max(0,Math.min(index??target.length,target.length)),0,item);return next;}
export function createComponent(type:string,existing:unknown):Json{const used=ids(existing);let id=type,index=2;while(used.has(id))id=`${type}-${index++}`;return{type,id};}
export class SpecificationHistory{private snapshots:string[];private cursor=0;constructor(initial:string,private readonly limit=50){this.snapshots=[initial];}get value(){return this.snapshots[this.cursor];}get canUndo(){return this.cursor>0;}get canRedo(){return this.cursor<this.snapshots.length-1;}commit(next:string){if(next!==this.value){this.snapshots=[...this.snapshots.slice(0,this.cursor+1),next].slice(-this.limit);this.cursor=this.snapshots.length-1;}return this.value;}undo(){if(this.canUndo)this.cursor--;return this.value;}redo(){if(this.canRedo)this.cursor++;return this.value;}reset(next:string){this.snapshots=[next];this.cursor=0;return next;}}
