import { useEffect, useMemo, useState } from "preact/hooks";
import { defaultConfig, defaultConfigJson, HyperPbiConfig } from "../../config/hyperpbiConfig";
import { NormalizedData } from "../../data/normalizeData";
import { getBasemapProvider, listBasemapProviders } from "../../providers/basemapProviderRegistry";
import { getGeocoderProvider, listGeocoderProviders } from "../../providers/geocoderProviderRegistry";
import { copyText } from "../textActions";
import { formToRuntimeConfig, normalizeRuntimeConfig, RuntimeConfigForm, runtimeConfigToForm } from "./runtimeConfigForm";

const ARC_GIS_EXAMPLE="https://geosop1.houstontx.gov/arcgis/rest/services/Geocoders/COH_Locator_Compo/GeocodeServer";
const bindingFields:Array<[keyof RuntimeConfigForm["map"],string]>=[["address","Address"],["city","City"],["state","State"],["zip","ZIP"],["latitude","Latitude"],["longitude","Longitude"],["x","X"],["y","Y"],["geometry","Geometry"]];

export function RuntimeConfigTab({data,configuration,onChange}:{data:NormalizedData;configuration:string;onChange:(value:string)=>void;theme?:string;fontSize?:number;wordWrap?:boolean}){
    const initial=normalizeRuntimeConfig(configuration);const [applied,setApplied]=useState<HyperPbiConfig>(initial.config??defaultConfig);const [form,setForm]=useState<RuntimeConfigForm>(()=>runtimeConfigToForm(initial.config??defaultConfig));const [jsonDraft,setJsonDraft]=useState(configuration||defaultConfigJson);const [errors,setErrors]=useState<string[]>(initial.errors);const [message,setMessage]=useState("");
    useEffect(()=>{const next=normalizeRuntimeConfig(configuration);if(!next.config)return;setApplied(next.config);setForm(runtimeConfigToForm(next.config));setJsonDraft(JSON.stringify(next.config,null,2));setErrors([]);},[configuration]);
    const draftValidation=useMemo(()=>normalizeRuntimeConfig(jsonDraft),[jsonDraft]);const normalizedApplied=JSON.stringify(applied,null,2);const unsavedJson=jsonDraft.trim()!==normalizedApplied.trim();const status=errors.length||draftValidation.errors.length?"Invalid":unsavedJson?"Unsaved JSON changes":"Valid";
    const commitForm=(next:RuntimeConfigForm)=>{const config=formToRuntimeConfig(next,applied);const normalized=normalizeRuntimeConfig(config);if(!normalized.config){setErrors(normalized.errors);return;}const json=JSON.stringify(normalized.config,null,2);setForm(runtimeConfigToForm(normalized.config));setApplied(normalized.config);setJsonDraft(json);setErrors([]);setMessage("GUI change applied.");onChange(json);};
    const update=<K extends keyof RuntimeConfigForm>(key:K,value:RuntimeConfigForm[K])=>commitForm({...form,[key]:value});
    const updateMap=(key:keyof RuntimeConfigForm["map"],value:string|string[])=>commitForm({...form,map:{...form.map,[key]:value||undefined}});
    const applyJson=()=>{const result=normalizeRuntimeConfig(jsonDraft);if(!result.config){setErrors(result.errors);setMessage("JSON was not applied; GUI values are unchanged.");return;}const json=JSON.stringify(result.config,null,2);setApplied(result.config);setForm(runtimeConfigToForm(result.config));setJsonDraft(json);setErrors([]);setMessage("JSON applied to the GUI.");onChange(json);};
    const formatJson=()=>{try{setJsonDraft(JSON.stringify(JSON.parse(jsonDraft),null,2));setErrors([]);setMessage("JSON formatted. Select Apply JSON to update the GUI.");}catch(error){setErrors([`Configuration JSON: ${error instanceof Error?error.message:String(error)}`]);}};
    const reset=()=>{const next=normalizeRuntimeConfig(defaultConfigJson).config??defaultConfig;const json=JSON.stringify(next,null,2);setApplied(next);setForm(runtimeConfigToForm(next));setJsonDraft(json);setErrors([]);setMessage("Runtime config reset to defaults.");onChange(json);};
    const validate=()=>{const result=normalizeRuntimeConfig(jsonDraft);setErrors(result.errors);setMessage(result.errors.length?"Configuration is invalid.":unsavedJson?"JSON is valid and ready to apply.":"Configuration is valid.");};
    const changeBasemap=(provider:RuntimeConfigForm["basemapProvider"])=>{const defaults=getBasemapProvider(provider).defaults;commitForm({...form,basemapProvider:provider,basemapEnabled:provider!=="none",tileUrl:defaults.tileUrl??form.tileUrl,attribution:defaults.attribution??form.attribution,maxZoom:defaults.maxZoom??form.maxZoom});};
    const changeGeocoder=(provider:RuntimeConfigForm["geocoderProvider"])=>{const defaults=getGeocoderProvider(provider).defaults;commitForm({...form,geocoderProvider:provider,geocoderEnabled:provider!=="none",endpoint:defaults.endpoint??form.endpoint,rateLimitPerSecond:defaults.rateLimitPerSecond??form.rateLimitPerSecond,resultLimit:defaults.resultLimit??form.resultLimit,minScore:defaults.minScore??form.minScore});};
    const fields=Object.values(data.fields);const fieldSelect=(key:keyof RuntimeConfigForm["map"],label:string)=><label><span>{label}</span><select value={String(form.map[key]??"")} onChange={event=>updateMap(key,event.currentTarget.value)}><option value="">Not assigned</option>{fields.map(field=><option value={field.key}>{field.displayName} · {field.key}</option>)}</select></label>;
    return <div class="hp-runtime-config"><header><div><h2>Runtime Config</h2><p>Use the form for normal setup. Advanced JSON changes remain isolated until Apply JSON.</p></div><span class={`hp-config-status hp-config-${status.toLowerCase().replaceAll(" ","-")}`}>{status}</span></header>{message&&<div class="hp-config-message">{message}</div>}{errors.length>0&&<div class="hp-studio-inline-error"><strong>Configuration issues</strong><ul>{errors.map(error=><li>{error}</li>)}</ul></div>}<div class="hp-runtime-config-form">
        <section><h3>Renderer</h3><div class="hp-config-checks"><label><input type="checkbox" checked={form.showHeader} onChange={event=>update("showHeader",event.currentTarget.checked)}/>Show dashboard header</label><label><input type="checkbox" checked={form.showRowCount} onChange={event=>update("showRowCount",event.currentTarget.checked)}/>Show row count</label><label><input type="checkbox" checked={form.showStudioButton} onChange={event=>update("showStudioButton",event.currentTarget.checked)}/>Show Studio button</label></div></section>
        <section><h3>Interactions</h3><div class="hp-config-checks"><label><input type="checkbox" checked={form.crossFilter} onChange={event=>update("crossFilter",event.currentTarget.checked)}/>Enable cross-filter / external interactions</label><label><input type="checkbox" checked={form.multiSelect} onChange={event=>update("multiSelect",event.currentTarget.checked)}/>Multi-select</label></div><label><span>External behavior mode</span><select value={form.externalMode} onChange={event=>update("externalMode",event.currentTarget.value as RuntimeConfigForm["externalMode"])}><option value="auto">Auto / Recommended</option><option value="filter">Power BI filter for slicer controls</option><option value="selection">Row selection for data-point clicks</option></select></label><p>Slicers use Power BI filters; table, chart, and map data-point clicks use Power BI selection.</p></section>
        <section><h3>Security / Authoring mode</h3><div class="hp-config-grid"><label><span>CSS mode</span><select value={form.cssMode} onChange={event=>update("cssMode",event.currentTarget.value as RuntimeConfigForm["cssMode"])}><option value="scoped">Scoped safe CSS</option><option value="trusted">Trusted author CSS</option></select></label><label><span>HTML mode</span><select value={form.htmlMode} onChange={event=>update("htmlMode",event.currentTarget.value as RuntimeConfigForm["htmlMode"])}><option value="sanitized">Sanitized HTML</option><option value="trusted">Trusted author HTML</option></select></label></div><label class="hp-config-inline-check"><input type="checkbox" checked={form.showSanitizerWarnings} onChange={event=>update("showSanitizerWarnings",event.currentTarget.checked)}/>Show sanitizer warnings</label><p>Trusted mode is for internal/trusted dashboards; it is not the certification-safe posture for public visuals.</p></section>
        <section><h3>Map services</h3><div class="hp-config-grid"><label><span>Package mode</span><select value={form.packageMode} onChange={event=>update("packageMode",event.currentTarget.value as RuntimeConfigForm["packageMode"])}><option value="core">Core / no external services</option><option value="maps">Maps enabled</option></select></label><label><span>Basemap provider</span><select value={form.basemapProvider} onChange={event=>changeBasemap(event.currentTarget.value as RuntimeConfigForm["basemapProvider"])}>{listBasemapProviders().map(provider=><option value={provider.id}>{provider.label}</option>)}</select></label><label class="hp-config-inline-check"><input type="checkbox" checked={form.basemapEnabled} onChange={event=>update("basemapEnabled",event.currentTarget.checked)}/>Basemap enabled</label><label><span>Tile URL</span><input value={form.tileUrl} onInput={event=>update("tileUrl",event.currentTarget.value)}/></label><label><span>Attribution</span><input value={form.attribution} onInput={event=>update("attribution",event.currentTarget.value)}/></label><label><span>Max zoom</span><input type="number" min="1" max="24" value={form.maxZoom} onInput={event=>update("maxZoom",Number(event.currentTarget.value))}/></label></div></section>
        <section><h3>Geocoder</h3><div class="hp-config-grid"><label><span>Provider</span><select value={form.geocoderProvider} onChange={event=>changeGeocoder(event.currentTarget.value as RuntimeConfigForm["geocoderProvider"])}>{listGeocoderProviders().map(provider=><option value={provider.id}>{provider.label}</option>)}</select></label><label class="hp-config-inline-check"><input type="checkbox" checked={form.geocoderEnabled} onChange={event=>update("geocoderEnabled",event.currentTarget.checked)}/>Enabled</label><label><span>Endpoint</span><input value={form.endpoint} onInput={event=>update("endpoint",event.currentTarget.value)}/></label><label><span>Rate limit / second</span><input type="number" min="0.05" step="0.05" value={form.rateLimitPerSecond} onInput={event=>update("rateLimitPerSecond",Number(event.currentTarget.value))}/></label><label><span>Result limit</span><input type="number" min="1" max="50" value={form.resultLimit} onInput={event=>update("resultLimit",Number(event.currentTarget.value))}/></label><label class="hp-config-inline-check"><input type="checkbox" checked={form.cache} onChange={event=>update("cache",event.currentTarget.checked)}/>Cache results</label><label class="hp-config-inline-check"><input type="checkbox" checked={form.privacyAcknowledged} onChange={event=>update("privacyAcknowledged",event.currentTarget.checked)}/>Privacy acknowledged</label>{form.geocoderProvider==="arcgis"&&<><label><span>Minimum score</span><input type="number" min="0" max="100" value={form.minScore} onInput={event=>update("minScore",Number(event.currentTarget.value))}/></label><label><span>Token (optional)</span><input type="password" value={form.token} onInput={event=>update("token",event.currentTarget.value)}/></label><label><span>Country code (optional)</span><input value={form.countryCode} onInput={event=>update("countryCode",event.currentTarget.value)}/></label><label><span>Category (optional)</span><input value={form.category} onInput={event=>update("category",event.currentTarget.value)}/></label><button type="button" onClick={()=>update("endpoint",ARC_GIS_EXAMPLE)}>Use Houston ArcGIS example</button></>}</div></section>
        <section><h3>Map bindings</h3><div class="hp-config-grid">{bindingFields.map(([key,label])=>fieldSelect(key,label))}</div><div class="hp-config-grid"><label><span>Tooltip fields</span><select multiple value={undefined} onChange={event=>updateMap("tooltip",Array.from(event.currentTarget.selectedOptions).map(option=>option.value))}>{fields.map(field=><option value={field.key} selected={form.map.tooltip?.includes(field.key)}>{field.displayName} · {field.key}</option>)}</select></label><label><span>Detail fields</span><select multiple value={undefined} onChange={event=>updateMap("details",Array.from(event.currentTarget.selectedOptions).map(option=>option.value))}>{fields.map(field=><option value={field.key} selected={form.map.details?.includes(field.key)}>{field.displayName} · {field.key}</option>)}</select></label></div></section>
    </div><details class="hp-runtime-advanced" open><summary>Advanced JSON</summary><div class="hp-config-actions"><button type="button" onClick={applyJson}>Apply JSON</button><button type="button" onClick={formatJson}>Format JSON</button><button type="button" onClick={reset}>Reset to defaults</button><button type="button" onClick={()=>void copyText(jsonDraft)}>Copy config JSON</button><button type="button" onClick={validate}>Validate config</button></div><div class="hp-runtime-json-editor"><textarea value={jsonDraft} onInput={event=>setJsonDraft(event.currentTarget.value)} aria-label="Advanced runtime configuration JSON" spellcheck={false}/></div></details></div>;
}
