import { HyperPbiStyleSystem, HyperPbiTheme } from "../schema/hyperpbiSchema";

export interface DesignPreset {
    id: string;
    name: string;
    summary: string;
    theme: HyperPbiTheme;
    styles: HyperPbiStyleSystem;
    guidance: { card: string; kpi: string; table: string; chart: string; controls: string; selected: string; spacing: string };
}

const preset = (id: string, name: string, summary: string, theme: HyperPbiTheme, globalCss: string, guidance: DesignPreset["guidance"]): DesignPreset => ({ id, name, summary, theme, styles: { globalCss, components: { "*": { style: { minWidth: 0 } }, table: { css: ".hp-table th{font-weight:700}.hp-table td{vertical-align:middle}" }, kpi: { css: ".hp-metric{min-height:72px}" } } }, guidance });

export const designPresets: DesignPreset[] = [
    preset("enterprise-light", "Enterprise Light", "Neutral, compact, and audit-friendly.", { mode: "light", density: "compact", primaryColor: "#1f4e79", accentColor: "#4f81bd", surfaceColor: "#ffffff", textColor: "#17212b", borderColor: "#d7dee7", radius: 6, cardPadding: 12, gap: 8 }, ".hp-card{box-shadow:0 1px 3px rgb(23 33 43 / 8%)}", { card: "White surfaces, one-pixel cool gray borders, restrained shadow", kpi: "Dark labels and a narrow primary accent", table: "Subtle header fill, compact rows, no zebra noise", chart: "Primary blue plus restrained semantic colors; direct labels only when sparse", controls: "Small bordered controls aligned in one toolbar", selected: "Pale blue background and #1f4e79 border", spacing: "8px gaps, 12px cards, compact density" }),
    preset("bright-modern", "Bright Modern", "Crisp white surfaces with confident blue and teal accents.", { mode: "light", density: "compact", primaryColor: "#2563eb", accentColor: "#0891b2", surfaceColor: "#ffffff", textColor: "#0f172a", borderColor: "#dbe4f0", successColor: "#059669", radius: 10, cardPadding: 14, gap: 10 }, ".hp-card{box-shadow:0 6px 18px rgb(37 99 235 / 7%)}", { card: "Bright white with soft cool shadow", kpi: "Large value, concise label, one accent edge", table: "Clean white rows and sticky pale-blue header", chart: "Blue/teal palette with semantic exceptions", controls: "Rounded 8px controls, clear focus states", selected: "Blue tint with strong blue outline", spacing: "10px gaps; never oversized" }),
    preset("futuristic-light", "Futuristic Light", "Technical light interface with cyan accents and precise geometry.", { mode: "light", density: "compact", primaryColor: "#0f6cbd", accentColor: "#06b6d4", surfaceColor: "#fafdff", textColor: "#102a43", borderColor: "#b8d8e8", radius: 4, cardPadding: 12, gap: 8 }, ".hp-card{background:linear-gradient(145deg,#fff,#f5fbff);box-shadow:0 0 0 1px rgb(6 182 212 / 8%)}", { card: "Near-white technical panels with minimal cyan edge", kpi: "Monospaced-feel numeric hierarchy without novelty fonts", table: "Fine grid, compact typography", chart: "Cyan/blue lines on white; avoid glow and excessive gradients", controls: "Precise 4px corners and compact labels", selected: "Cyan inset border with pale cyan fill", spacing: "8px modular rhythm" }),
    preset("dark-ops", "Dark Ops Center", "Low-glare operational monitoring with readable semantic alerts.", { mode: "dark", density: "compact", primaryColor: "#38bdf8", accentColor: "#22d3ee", surfaceColor: "#111827", textColor: "#e5eef8", borderColor: "#334155", dangerColor: "#fb7185", warningColor: "#fbbf24", successColor: "#34d399", radius: 6, cardPadding: 12, gap: 8 }, ".hp-card{background:#111827;box-shadow:none}.hp-table th{background:#1e293b}", { card: "Flat dark navy with visible borders", kpi: "High-contrast values and muted labels", table: "Dark sticky header and restrained hover", chart: "Cyan primary with semantic amber/red/green", controls: "Dark surfaces with explicit borders", selected: "Cyan border and translucent cyan fill", spacing: "Dense 8px gaps" }),
    preset("dense-compact", "Dense Compact", "Maximum useful content for standard Power BI tiles.", { mode: "light", density: "compact", primaryColor: "#334155", accentColor: "#64748b", surfaceColor: "#ffffff", textColor: "#111827", borderColor: "#d1d5db", radius: 4, cardPadding: 8, gap: 6 }, ".hp-card{box-shadow:none}.hp-card-header{min-height:30px;padding:5px 8px}.hp-card-body{padding:8px}", { card: "Flat, bordered, compact", kpi: "Short labels and 18–22px values", table: "28px-equivalent rows and narrow cells", chart: "Minimal legends, labels, and grid margins", controls: "Single compact toolbar", selected: "Gray-blue highlight with visible border", spacing: "6px gaps, 8px card padding" }),
    preset("map-command", "Map Command Center", "Map-dominant operational layout with compact supporting panels.", { mode: "dark", density: "compact", primaryColor: "#22d3ee", accentColor: "#60a5fa", surfaceColor: "#0f172a", textColor: "#e2e8f0", borderColor: "#334155", warningColor: "#f59e0b", dangerColor: "#f43f5e", radius: 5, cardPadding: 10, gap: 7 }, ".hp-map-frame{min-height:320px}.hp-card{box-shadow:none}", { card: "Dark supporting panels around a dominant map", kpi: "One compact status rail", table: "Short exception list, not a giant grid", chart: "Only charts that explain geography", controls: "Collapsible filter drawer", selected: "Cyan selection edge and clear map/detail link", spacing: "7px gaps; map receives most area" })
];

export const designPresetNames = designPresets.map(presetItem => presetItem.name);
export const getDesignPreset = (nameOrId: string): DesignPreset => designPresets.find(item => item.name === nameOrId || item.id === nameOrId) ?? designPresets[0];
export const designPresetPrompt = (selected?: string): string => {
    const chosen = getDesignPreset(selected ?? "enterprise-light");
    return `Selected preset: ${chosen.name} — ${chosen.summary}\nUse these JSON-ready theme tokens: ${JSON.stringify(chosen.theme)}\nUse these reusable style rules as the starting point: ${JSON.stringify(chosen.styles)}\nCard: ${chosen.guidance.card}. KPI: ${chosen.guidance.kpi}. Table: ${chosen.guidance.table}. Chart: ${chosen.guidance.chart}. Controls: ${chosen.guidance.controls}. Selected state: ${chosen.guidance.selected}. Spacing: ${chosen.guidance.spacing}.`;
};
