import { DashboardComponent } from "./hyperpbiSchema";
import { Diagnostic } from "./diagnostics";

const plain=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
function merge(base:unknown,instance:unknown):unknown{if(instance===undefined)return base;if(plain(base)&&plain(instance)){const result:{[key:string]:unknown}={...base};for(const [key,value]of Object.entries(instance))result[key]=merge(result[key],value);return result;}return instance;}

export function expandDefinitions(value:unknown):{value:unknown;diagnostics:Diagnostic[]}{
    if(!plain(value))return{value,diagnostics:[]};const root={...value};const definitions=plain(root.definitions)?root.definitions:{};const diagnostics:Diagnostic[]=[];const resolving:string[]=[];const resolved=new Map<string,Record<string,unknown>>();
    const resolve=(name:string):Record<string,unknown>|undefined=>{if(resolved.has(name))return resolved.get(name);const definition=definitions[name];if(!plain(definition)){diagnostics.push({code:"UNKNOWN_DEFINITION",severity:"error",path:`/definitions/${name}`,message:`Reusable definition “${name}” is not defined.`,received:name});return undefined;}if(resolving.includes(name)){diagnostics.push({code:"DEFINITION_CYCLE",severity:"error",path:`/definitions/${name}`,message:`Definition cycle: ${[...resolving.slice(resolving.indexOf(name)),name].join(" → ")}.`});return undefined;}resolving.push(name);let result={...definition};if(typeof result.use==="string"){const parent=resolve(result.use);if(parent)result=merge(parent,result) as Record<string,unknown>;delete result.use;}resolving.pop();delete result.id;resolved.set(name,result);return result;};
    const expand=(node:unknown,path:string):unknown=>{if(Array.isArray(node))return node.map((item,index)=>expand(item,`${path}/${index}`));if(!plain(node))return node;let result={...node};if(typeof result.use==="string"){const definition=resolve(result.use);if(definition)result=merge(definition,result) as Record<string,unknown>;else diagnostics.push({code:"UNKNOWN_DEFINITION",severity:"error",path:`${path}/use`,componentId:typeof result.id==="string"?result.id:undefined,message:`Reusable definition “${result.use}” is not defined.`,received:result.use});delete result.use;if(typeof result.id!=="string"||!result.id)diagnostics.push({code:"MISSING_REQUIRED_PROPERTY",severity:"error",path:`${path}/id`,message:"A component using a reusable definition must supply its own ID."});}
        for(const key of ["children","footer"]){if(Array.isArray(result[key]))result[key]=expand(result[key],`${path}/${key}`);}if(Array.isArray(result.tabs))result.tabs=result.tabs.map((tab,index)=>{if(!plain(tab))return tab;const canonical={...tab};const children=canonical.children??canonical.components??canonical.content??[];delete canonical.components;delete canonical.content;canonical.children=expand(children,`${path}/tabs/${index}/children`);return canonical;});return result;};
    for(const key of ["components","toolbar","leftPanel","rightPanel"])if(Array.isArray(root[key]))root[key]=expand(root[key],`/${key}`) as DashboardComponent[];
    return{value:root,diagnostics};
}
