import { NormalizedData } from "../data/normalizeData";
import { resolveDatasetSchemas, DatasetSchemaEvaluation } from "../data/datasetSchema";
import { DatasetDefinition } from "../data/datasets";
import { Diagnostic, closestMatches, diagnosticsToStrings } from "./diagnostics";
import { expandDefinitions } from "./definitionExpansion";
import { HyperPbiSchema } from "./hyperpbiSchema";
import { migrateFieldReferences } from "./migrateFieldReferences";
import { expandPatterns } from "./patternRegistry";
import { migrateSchema } from "./schemaMigrations";
import { validateSchema } from "./validateSchema";
import { designPresets, getDesignPreset } from "../design/stylePresets";
import { canonicalizePreSchemaFieldReferences, canonicalizeSpecificationFieldReferences } from "../fields/specificationFieldReferences";
import { validateCalculations } from "../calculations/calculationValidator";
import { calculatedFieldMetadata } from "../calculations/derivedFields";
import type { CalculationSpecification } from "../calculations/calculationTypes";
import { componentPathById as collectComponentPaths } from "./jsonPointer";

const clone=<T>(value:T):T=>value===undefined?value:JSON.parse(JSON.stringify(value)) as T;
const record=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);

function safeRepairs(value:unknown):{value:unknown;diagnostics:Diagnostic[]}{if(!record(value))return{value,diagnostics:[]};const root=clone(value);const diagnostics:Diagnostic[]=[];if(root.version===undefined&&Array.isArray(root.components)){root.version="2.0";diagnostics.push({code:"REPAIR_APPLIED",severity:"info",path:"/version",message:"Added version 2.0 because the specification shape was unambiguous.",autoFixAvailable:true});}
    const typo:Record<string,string>={meausre:"measure",catgory:"category",componets:"components",aggregration:"aggregation"};const numeric=new Set(["span","height","width","limit","pageSize","maxRows","columns","gap"]);const visit=(node:unknown,path:string)=>{if(Array.isArray(node)){node.forEach((item,index)=>visit(item,`${path}/${index}`));return;}if(!record(node))return;for(const key of Object.keys(node)){const replacement=typo[key];if(replacement&&node[replacement]===undefined){node[replacement]=node[key];delete node[key];diagnostics.push({code:"REPAIR_APPLIED",severity:"info",path:`${path}/${key}`,componentId:typeof node.id==="string"?node.id:undefined,message:`Renamed unambiguous property typo “${key}” to “${replacement}”.`,received:key,suggestions:[replacement],autoFixAvailable:true});continue;}if(numeric.has(key)&&typeof node[key]==="string"&&/^[-+]?\d+(\.\d+)?$/.test(node[key] as string)){node[key]=Number(node[key]);diagnostics.push({code:"REPAIR_APPLIED",severity:"info",path:`${path}/${key}`,message:`Converted numeric string for “${key}” to a number.`,autoFixAvailable:true});}visit(node[key],`${path}/${key}`);}};visit(root,"");return{value:root,diagnostics};}

function assignIds(value:unknown):Diagnostic[]{const diagnostics:Diagnostic[]=[];if(!record(value)||value.version!=="2.0")return diagnostics;let sequence=0;const visit=(node:unknown,path:string)=>{if(Array.isArray(node)){node.forEach((item,index)=>visit(item,`${path}/${index}`));return;}if(!record(node))return;if(typeof node.type==="string"&&node.type!=="pattern"&&!node.id){sequence+=1;node.id=`${node.type}-${sequence}`;diagnostics.push({code:"REPAIR_APPLIED",severity:"info",path:`${path}/id`,message:`Generated stable import ID “${node.id}”.`,autoFixAvailable:true});}Object.entries(node).forEach(([key,child])=>{if(["components","toolbar","leftPanel","rightPanel","children","footer","tabs","items","chart"].includes(key))visit(child,`${path}/${key}`);});};for(const key of ["components","toolbar","leftPanel","rightPanel"])visit(value[key],`/${key}`);return diagnostics;}

function applyDesignSystem(value:unknown):void{if(!record(value)||!record(value.app)||typeof value.app.designSystem!=="string")return;const preset=getDesignPreset(value.app.designSystem);value.theme={...preset.theme,...(record(value.theme)?value.theme:{})};const existing=record(value.styles)?value.styles:{};value.styles={...preset.styles,...existing,components:{...(preset.styles.components??{}),...(record(existing.components)?existing.components:{})}};delete value.app.designSystem;}

function validateDesignSystem(value:unknown):Diagnostic[]{if(!record(value)||!record(value.app)||typeof value.app.designSystem!=="string")return[];const reference=value.app.designSystem;if(designPresets.some(item=>item.id===reference||item.name===reference))return[];return[{code:"INVALID_ENUM_VALUE",severity:"error",path:"/app/designSystem",message:`Design system “${reference}” is not supported.`,received:reference,suggestions:closestMatches(reference,designPresets.flatMap(item=>[item.id,item.name]))}];}

function validateComponentDatasets(value:unknown,datasets:DatasetSchemaEvaluation):Diagnostic[]{const diagnostics:Diagnostic[]=[];const visit=(node:unknown,path:string)=>{if(Array.isArray(node)){node.forEach((item,index)=>visit(item,`${path}/${index}`));return;}if(!record(node))return;if(typeof node.dataset==="string"&&!datasets.datasets.has(node.dataset))diagnostics.push({code:"UNKNOWN_DATASET",severity:"error",path:`${path}/dataset`,componentId:typeof node.id==="string"?node.id:undefined,message:`Dataset “${node.dataset}” is not defined.`,received:node.dataset,suggestions:closestMatches(node.dataset,datasets.datasets.keys())});if(node.type==="map"&&Array.isArray(node.layers))node.layers.forEach((layer,index)=>{if(!record(layer))return;const datasetName=typeof layer.dataset==="string"?layer.dataset:typeof node.dataset==="string"?node.dataset:"powerbi";if(!datasets.datasets.has(datasetName))diagnostics.push({code:"MAP_LAYER_DATASET_NOT_FOUND",severity:"error",path:`${path}/layers/${index}/dataset`,componentId:typeof node.id==="string"?node.id:undefined,message:`Map layer dataset “${datasetName}” is not defined.`,received:datasetName,suggestions:closestMatches(datasetName,datasets.datasets.keys())});});for(const key of ["children","footer","tabs","items","chart","elements","repeat"])if(node[key]!==undefined)visit(node[key],`${path}/${key}`);};if(record(value))for(const key of ["components","toolbar","leftPanel","rightPanel"])if(Array.isArray(value[key]))visit(value[key],`/${key}`);return diagnostics;}

export interface PreparedSpecification { schema?:HyperPbiSchema;authoring?:unknown;diagnostics:Diagnostic[];errors:string[];warnings:string[];repairs:Diagnostic[];datasets?:DatasetSchemaEvaluation;ownerByRuntimeId:Record<string,string>;componentPathById:Record<string,string>; }
export function prepareSpecification(input:unknown,data:NormalizedData,{repair=true,aliasOverrides={}}:{repair?:boolean;aliasOverrides?:Record<string,string>}={}):PreparedSpecification{
    const repaired=repair?safeRepairs(input):{value:clone(input),diagnostics:[] as Diagnostic[]};let canonical=migrateSchema(repaired.value);if(record(canonical)&&canonical.version==="1.0")canonical=migrateFieldReferences(canonical,data.fields);const idRepairs=repair?assignIds(canonical):[];
    const componentPaths=collectComponentPaths(canonical);const definitions=expandDefinitions(clone(canonical));const patterns=expandPatterns(definitions.value);const root=patterns.value;const designDiagnostics=validateDesignSystem(root);canonicalizePreSchemaFieldReferences(root,data,aliasOverrides);const calculationSpec=record(root)&&record(root.calculations)?root.calculations as unknown as CalculationSpecification:undefined;const calculationMessages=validateCalculations(calculationSpec,Object.keys(data.fields));const calculationDiagnostics:Diagnostic[]=calculationMessages.map(item=>({code:"INVALID_DATASET_DEFINITION",severity:item.level,path:`/calculations/${item.path.replace(/\[(\d+)\]/g,"/$1").replace(/\./g,"/")}`,message:item.message}));const augmentedData:NormalizedData={...data,fields:calculatedFieldMetadata(data.fields,calculationSpec?.fields)};const datasetDefinitions=record(root)&&record(root.data)&&record(root.data.datasets)?root.data.datasets as Record<string,DatasetDefinition>:{};const datasets=resolveDatasetSchemas(augmentedData,datasetDefinitions);const componentDatasetDiagnostics=validateComponentDatasets(root,datasets);const fieldDiagnostics=canonicalizeSpecificationFieldReferences(root,augmentedData,datasets,aliasOverrides);applyDesignSystem(root);const validation=validateSchema(root);const diagnostics=[...repaired.diagnostics,...definitions.diagnostics,...patterns.diagnostics,...idRepairs,...designDiagnostics,...calculationDiagnostics,...datasets.diagnostics,...componentDatasetDiagnostics,...fieldDiagnostics,...(validation.diagnostics??[])];const errors=diagnosticsToStrings(diagnostics.filter(item=>item.severity==="error"));const warnings=diagnosticsToStrings(diagnostics.filter(item=>item.severity==="warning"));return{schema:errors.length?undefined:validation.schema,authoring:canonical,diagnostics,errors,warnings,repairs:[...repaired.diagnostics,...idRepairs],datasets,ownerByRuntimeId:patterns.ownerByRuntimeId,componentPathById:componentPaths};
}
