import { NormalizedData } from "../data/normalizeData";
import { evaluateDatasets } from "../data/datasets";
import { FieldResolver } from "../fields/fieldResolver";
import { Diagnostic, closestMatches, diagnosticsToStrings } from "./diagnostics";
import { expandDefinitions } from "./definitionExpansion";
import { HyperPbiSchema } from "./hyperpbiSchema";
import { migrateFieldReferences } from "./migrateFieldReferences";
import { expandPatterns } from "./patternRegistry";
import { migrateSchema } from "./schemaMigrations";
import { validateSchema } from "./validateSchema";
import { designPresets, getDesignPreset } from "../design/stylePresets";

const clone=<T>(value:T):T=>value===undefined?value:JSON.parse(JSON.stringify(value)) as T;
const record=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const fieldProperties=new Set(["field","bind","sortBy","keyField","category","measure","x","y","pointSize","splitField","dateField","titleField","categoryField","statusField","descriptionField","sourceField","targetField","valueField","labelField","groupField","primaryField","secondaryField","badgeField","stageField"]);

function safeRepairs(value:unknown):{value:unknown;diagnostics:Diagnostic[]}{if(!record(value))return{value,diagnostics:[]};const root=clone(value);const diagnostics:Diagnostic[]=[];if(root.version===undefined&&Array.isArray(root.components)){root.version="2.0";diagnostics.push({code:"REPAIR_APPLIED",severity:"info",path:"/version",message:"Added version 2.0 because the specification shape was unambiguous.",autoFixAvailable:true});}
    const typo:Record<string,string>={meausre:"measure",catgory:"category",componets:"components",aggregration:"aggregation"};const numeric=new Set(["span","height","width","limit","pageSize","maxRows","columns","gap"]);const visit=(node:unknown,path:string)=>{if(Array.isArray(node)){node.forEach((item,index)=>visit(item,`${path}/${index}`));return;}if(!record(node))return;for(const key of Object.keys(node)){const replacement=typo[key];if(replacement&&node[replacement]===undefined){node[replacement]=node[key];delete node[key];diagnostics.push({code:"REPAIR_APPLIED",severity:"info",path:`${path}/${key}`,componentId:typeof node.id==="string"?node.id:undefined,message:`Renamed unambiguous property typo “${key}” to “${replacement}”.`,received:key,suggestions:[replacement],autoFixAvailable:true});continue;}if(numeric.has(key)&&typeof node[key]==="string"&&/^[-+]?\d+(\.\d+)?$/.test(node[key] as string)){node[key]=Number(node[key]);diagnostics.push({code:"REPAIR_APPLIED",severity:"info",path:`${path}/${key}`,message:`Converted numeric string for “${key}” to a number.`,autoFixAvailable:true});}visit(node[key],`${path}/${key}`);}};visit(root,"");return{value:root,diagnostics};}

function assignIds(value:unknown):Diagnostic[]{const diagnostics:Diagnostic[]=[];if(!record(value)||value.version!=="2.0")return diagnostics;let sequence=0;const visit=(node:unknown,path:string)=>{if(Array.isArray(node)){node.forEach((item,index)=>visit(item,`${path}/${index}`));return;}if(!record(node))return;if(typeof node.type==="string"&&node.type!=="pattern"&&!node.id){sequence+=1;node.id=`${node.type}-${sequence}`;diagnostics.push({code:"REPAIR_APPLIED",severity:"info",path:`${path}/id`,message:`Generated stable import ID “${node.id}”.`,autoFixAvailable:true});}Object.entries(node).forEach(([key,child])=>{if(["components","toolbar","leftPanel","rightPanel","children","footer","tabs","items","chart"].includes(key))visit(child,`${path}/${key}`);});};for(const key of ["components","toolbar","leftPanel","rightPanel"])visit(value[key],`/${key}`);return diagnostics;}

function resolveFields(value:unknown,data:NormalizedData,datasets:ReturnType<typeof evaluateDatasets>,aliasOverrides:Record<string,string>={}):Diagnostic[]{const diagnostics:Diagnostic[]=[];const baseResolver=new FieldResolver(data,aliasOverrides);const visit=(node:unknown,path:string,datasetName?:string)=>{if(Array.isArray(node)){node.forEach((item,index)=>visit(item,`${path}/${index}`,datasetName));return;}if(!record(node))return;const currentDataset=typeof node.dataset==="string"?node.dataset:datasetName;const dataset=currentDataset?datasets.datasets.get(currentDataset):undefined;const knownDatasetFields=dataset?new Set(Object.keys(dataset.data.fields)):undefined;const resolve=(reference:string,fieldPath:string)=>{if(knownDatasetFields?.has(reference))return reference;const result=baseResolver.resolve(reference);if(result.status==="resolved"&&result.key)return result.key;const aliases=baseResolver.registry.entries.map(item=>item.alias);diagnostics.push({code:result.status==="ambiguous"?"AMBIGUOUS_FIELD":"UNKNOWN_FIELD",severity:"error",path:fieldPath,componentId:typeof node.id==="string"?node.id:undefined,message:result.status==="ambiguous"?`Field “${reference}” is ambiguous.`:`Field “${reference}” is not available.`,received:reference,suggestions:result.candidates??closestMatches(reference,[...(knownDatasetFields??[]),...aliases]),autoFixAvailable:false});return reference;};
        const numeric=new Set(["measure","x","y","pointSize","valueField"]);for(const [key,child]of Object.entries(node)){if(fieldProperties.has(key)&&typeof child==="string"&&!child.startsWith("$")){const resolved=resolve(child,`${path}/${key}`);node[key]=resolved;if(numeric.has(key)){const field=dataset?.data.fields[resolved]??data.fields[resolved];const values=(dataset?.data.rows??data.rows).map(row=>row[resolved]).filter(value=>value!==null&&value!==undefined);if(field&&values.length&&!values.some(value=>typeof value==="number"&&Number.isFinite(value)))diagnostics.push({code:"FIELD_TYPE_MISMATCH",severity:"error",path:`${path}/${key}`,componentId:typeof node.id==="string"?node.id:undefined,message:`Property “${key}” requires a numeric field, but “${child}” is not numeric.`,received:child});}}else if(["columns","rows","pathFields","fields"].includes(key)&&Array.isArray(child))node[key]=child.map((item,index)=>typeof item==="string"?resolve(item,`${path}/${key}/${index}`):item);else if(key==="series"&&Array.isArray(child))child.forEach((item,index)=>{if(record(item)&&typeof item.field==="string")item.field=resolve(item.field,`${path}/series/${index}/field`);});else if(key==="indicators"&&Array.isArray(child))child.forEach((item,index)=>{if(record(item)&&typeof item.field==="string")item.field=resolve(item.field,`${path}/indicators/${index}/field`);});}
        for(const [key,child]of Object.entries(node))if(!fieldProperties.has(key)&&!["columns","rows","pathFields","fields","series","indicators"].includes(key)&&(Array.isArray(child)||record(child)))visit(child,`${path}/${key}`,currentDataset);};for(const key of ["components","toolbar","leftPanel","rightPanel"])if(record(value)&&Array.isArray(value[key]))visit(value[key],`/${key}`);return diagnostics;}

function resolveDatasetDefinitions(value:unknown,data:NormalizedData,aliasOverrides:Record<string,string>={}):void{if(!record(value)||!record(value.data)||!record(value.data.datasets))return;const resolver=new FieldResolver(data,aliasOverrides);const resolve=(reference:string)=>resolver.resolve(reference).key??reference;const expression=(node:unknown):void=>{if(Array.isArray(node)){node.forEach(expression);return;}if(!record(node))return;if(typeof node.field==="string")node.field=resolve(node.field);Object.values(node).forEach(expression);};for(const definition of Object.values(value.data.datasets)){if(!record(definition))continue;if(Array.isArray(definition.select))definition.select=definition.select.map(item=>typeof item==="string"?resolve(item):item);if(record(definition.rename)){const renamed:Record<string,unknown>={};for(const [key,target]of Object.entries(definition.rename))renamed[resolve(key)]=target;definition.rename=renamed;}const filters=Array.isArray(definition.filter)?definition.filter:[definition.filter];filters.forEach(filter=>{if(record(filter)&&typeof filter.field==="string")filter.field=resolve(filter.field);});if(Array.isArray(definition.groupBy))definition.groupBy=definition.groupBy.map(item=>typeof item==="string"?resolve(item):item);if(record(definition.metrics))Object.values(definition.metrics).forEach(metric=>{if(record(metric)&&typeof metric.field==="string")metric.field=resolve(metric.field);});if(Array.isArray(definition.sort))definition.sort.forEach(sort=>{if(record(sort)&&typeof sort.field==="string")sort.field=resolve(sort.field);});if(Array.isArray(definition.distinct))definition.distinct=definition.distinct.map(item=>typeof item==="string"?resolve(item):item);if(record(definition.derive))Object.values(definition.derive).forEach(expression);}}

function applyDesignSystem(value:unknown):void{if(!record(value)||!record(value.app)||typeof value.app.designSystem!=="string")return;const preset=getDesignPreset(value.app.designSystem);value.theme={...preset.theme,...(record(value.theme)?value.theme:{})};const existing=record(value.styles)?value.styles:{};value.styles={...preset.styles,...existing,components:{...(preset.styles.components??{}),...(record(existing.components)?existing.components:{})}};delete value.app.designSystem;}

function validateDesignSystem(value:unknown):Diagnostic[]{if(!record(value)||!record(value.app)||typeof value.app.designSystem!=="string")return[];const reference=value.app.designSystem;if(designPresets.some(item=>item.id===reference||item.name===reference))return[];return[{code:"INVALID_ENUM_VALUE",severity:"error",path:"/app/designSystem",message:`Design system “${reference}” is not supported.`,received:reference,suggestions:closestMatches(reference,designPresets.flatMap(item=>[item.id,item.name]))}];}

function validateComponentDatasets(value:unknown,datasets:ReturnType<typeof evaluateDatasets>):Diagnostic[]{const diagnostics:Diagnostic[]=[];const visit=(node:unknown,path:string)=>{if(Array.isArray(node)){node.forEach((item,index)=>visit(item,`${path}/${index}`));return;}if(!record(node))return;if(typeof node.dataset==="string"&&!datasets.datasets.has(node.dataset))diagnostics.push({code:"UNKNOWN_DATASET",severity:"error",path:`${path}/dataset`,componentId:typeof node.id==="string"?node.id:undefined,message:`Dataset “${node.dataset}” is not defined.`,received:node.dataset,suggestions:closestMatches(node.dataset,datasets.datasets.keys())});for(const key of ["children","footer","tabs","items","chart","elements","repeat"])if(node[key]!==undefined)visit(node[key],`${path}/${key}`);};if(record(value))for(const key of ["components","toolbar","leftPanel","rightPanel"])if(Array.isArray(value[key]))visit(value[key],`/${key}`);return diagnostics;}

export interface PreparedSpecification { schema?:HyperPbiSchema;authoring?:unknown;diagnostics:Diagnostic[];errors:string[];warnings:string[];repairs:Diagnostic[];datasets?:ReturnType<typeof evaluateDatasets>; }
export function prepareSpecification(input:unknown,data:NormalizedData,{repair=true,aliasOverrides={}}:{repair?:boolean;aliasOverrides?:Record<string,string>}={}):PreparedSpecification{
    const repaired=repair?safeRepairs(input):{value:clone(input),diagnostics:[] as Diagnostic[]};let canonical=migrateSchema(repaired.value);if(record(canonical)&&canonical.version==="1.0")canonical=migrateFieldReferences(canonical,data.fields);const idRepairs=repair?assignIds(canonical):[];
    const definitions=expandDefinitions(clone(canonical));const patterns=expandPatterns(definitions.value);const root=patterns.value;const designDiagnostics=validateDesignSystem(root);resolveDatasetDefinitions(root,data,aliasOverrides);const datasetDefinitions=record(root)&&record(root.data)&&record(root.data.datasets)?root.data.datasets as Parameters<typeof evaluateDatasets>[1]:{};const datasets=evaluateDatasets(data,datasetDefinitions);const datasetDiagnostics:Diagnostic[]=datasets.errors.map(item=>({code:item.code,severity:"error",path:`/data/datasets/${item.dataset}/source`,message:item.message,received:item.dataset}));const componentDatasetDiagnostics=validateComponentDatasets(root,datasets);const fieldDiagnostics=resolveFields(root,data,datasets,aliasOverrides);applyDesignSystem(root);const validation=validateSchema(root);const diagnostics=[...repaired.diagnostics,...definitions.diagnostics,...patterns.diagnostics,...idRepairs,...designDiagnostics,...datasetDiagnostics,...componentDatasetDiagnostics,...fieldDiagnostics,...(validation.diagnostics??[])];const errors=diagnosticsToStrings(diagnostics.filter(item=>item.severity==="error"));const warnings=diagnosticsToStrings(diagnostics.filter(item=>item.severity==="warning"));return{schema:errors.length?undefined:validation.schema,authoring:canonical,diagnostics,errors,warnings,repairs:[...repaired.diagnostics,...idRepairs],datasets};
}
