import { componentDescriptors } from "../catalog/componentDescriptors";
import { Diagnostic, closestMatches } from "./diagnostics";
import { HyperPbiSchema } from "./hyperpbiSchema";
import { SVG_LIMITS } from "../components/svg/svgTypes";
import { validateSvgComponentSchema } from "../components/svg/svgSchema";

const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
const componentTypeNames=componentDescriptors.map(component=>component.type);
const rootProperties=new Set(["version","title","theme","layout","state","app","leftPanel","rightPanel","toolbar","components","css","styles","calculations","data","definitions"]);
export const v2CommonComponentProperties=componentDescriptors.map(descriptor=>new Set(descriptor.schema.allowed)).reduce<string[]>((common,allowed)=>common.filter(property=>allowed.has(property)),[...componentDescriptors[0].schema.allowed]);
const common=new Set<string>(v2CommonComponentProperties);
export const v2ComponentPropertiesByType:Record<string,string[]>=Object.fromEntries(componentDescriptors.map(descriptor=>[descriptor.type,descriptor.schema.allowed.filter(property=>!common.has(property))]));
export const v2RequiredPropertiesByType:Record<string,string[]>=Object.fromEntries(componentDescriptors.map(descriptor=>[descriptor.type,descriptor.schema.required.filter(property=>property!=="type"&&property!=="id")]));
const deprecated=new Map([["internal","interaction.internalMode"],["external","interaction.externalMode"],["selectable","interaction.showSelector"],["selectionMode","interaction.internalMode"]]);

export function validateV2Schema(value:unknown):{valid:boolean;schema?:HyperPbiSchema;diagnostics:Diagnostic[]}{
    const diagnostics:Diagnostic[]=[];if(!object(value)){return{valid:false,diagnostics:[{code:"INVALID_PROPERTY_TYPE",severity:"error",path:"/",message:"Specification must be one JSON object.",received:value}]};}
    for(const key of Object.keys(value))if(!rootProperties.has(key))diagnostics.push({code:"UNKNOWN_PROPERTY",severity:"error",path:`/${key}`,message:`Root property “${key}” is not supported in version 2.0.`,received:key,suggestions:closestMatches(key,rootProperties),autoFixAvailable:false});
    if(value.version!=="2.0")diagnostics.push({code:"UNSUPPORTED_VERSION",severity:"error",path:"/version",message:`Version 2.0 validation received “${String(value.version)}”.`,received:value.version});
    if(!Array.isArray(value.components))diagnostics.push({code:"MISSING_REQUIRED_PROPERTY",severity:"error",path:"/components",message:"A components array is required."});
    if(value.data!==undefined&&!object(value.data))diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path:"/data",message:"Data must be an object."});else if(object(value.data)){for(const key of Object.keys(value.data))if(key!=="datasets")diagnostics.push({code:"UNKNOWN_PROPERTY",severity:"error",path:`/data/${key}`,message:`Data property “${key}” is not supported.`,received:key,suggestions:closestMatches(key,["datasets"])});if(value.data.datasets!==undefined&&!object(value.data.datasets))diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path:"/data/datasets",message:"Datasets must be a named object."});else if(object(value.data.datasets)){const allowed=new Set(["source","select","rename","filter","sort","groupBy","metrics","derive","distinct","limit"]);for(const [name,dataset]of Object.entries(value.data.datasets)){const path=`/data/datasets/${name}`;if(!object(dataset)){diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path,message:"Dataset definition must be an object."});continue;}if(typeof dataset.source!=="string"||!dataset.source)diagnostics.push({code:"MISSING_REQUIRED_PROPERTY",severity:"error",path:`${path}/source`,message:"Dataset source is required."});for(const key of Object.keys(dataset))if(!allowed.has(key))diagnostics.push({code:"UNKNOWN_PROPERTY",severity:"error",path:`${path}/${key}`,message:`Dataset property “${key}” is not supported.`,received:key,suggestions:closestMatches(key,allowed)});if(dataset.select!==undefined&&!Array.isArray(dataset.select))diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path:`${path}/select`,message:"select must be an array of fields."});if(dataset.groupBy!==undefined&&!Array.isArray(dataset.groupBy))diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path:`${path}/groupBy`,message:"groupBy must be an array of fields."});if(dataset.limit!==undefined&&(!Number.isInteger(dataset.limit)||Number(dataset.limit)<0))diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path:`${path}/limit`,message:"limit must be a nonnegative integer."});}}}
    let totalSvgElements=0,totalSvgAnimations=0;const ids=new Map<string,string>();const targets:Array<{target:string;path:string;componentId?:string}>=[];const visit=(component:unknown,path:string)=>{if(!object(component)){diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path,message:"Component must be an object.",received:component});return;}const type=typeof component.type==="string"?component.type:"";const componentId=typeof component.id==="string"?component.id:undefined;
        if(!type)diagnostics.push({code:"MISSING_REQUIRED_PROPERTY",severity:"error",path:`${path}/type`,componentId,message:"Component type is required."});else if(!componentTypeNames.includes(type))diagnostics.push({code:"UNKNOWN_COMPONENT_TYPE",severity:"error",path:`${path}/type`,componentId,message:`Component type “${type}” is not supported.`,received:type,suggestions:closestMatches(type,componentTypeNames)});
        if(!componentId)diagnostics.push({code:"MISSING_REQUIRED_PROPERTY",severity:"error",path:`${path}/id`,message:"Every version 2.0 component requires a stable ID.",autoFixAvailable:true});else if(!/^[A-Za-z][A-Za-z0-9_-]{0,99}$/.test(componentId))diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path:`${path}/id`,componentId,message:"Component ID must start with a letter and contain only letters, digits, _ or -."});else if(ids.has(componentId))diagnostics.push({code:"DUPLICATE_COMPONENT_ID",severity:"error",path:`${path}/id`,componentId,message:`Component ID “${componentId}” duplicates ${ids.get(componentId)}.`,received:componentId});else ids.set(componentId,`${path}/id`);
        const allowed=new Set([...common,...(v2ComponentPropertiesByType[type]??[])]);for(const key of Object.keys(component)){if(deprecated.has(key))diagnostics.push({code:"DEPRECATED_PROPERTY",severity:"warning",path:`${path}/${key}`,componentId,message:`Property “${key}” is deprecated; use ${deprecated.get(key)}.`,received:key});else if(!allowed.has(key))diagnostics.push({code:"UNKNOWN_PROPERTY",severity:"error",path:`${path}/${key}`,componentId,message:`Property “${key}” is not supported on ${type||"this component"}.`,received:key,suggestions:closestMatches(key,allowed),autoFixAvailable:closestMatches(key,allowed).length===1});}
        for(const property of v2RequiredPropertiesByType[type]??[])if(component[property]===undefined)diagnostics.push({code:"MISSING_REQUIRED_PROPERTY",severity:"error",path:`${path}/${property}`,componentId,message:`${type} requires property “${property}”.`});
        if(component.span!==undefined&&(typeof component.span!=="number"||component.span<1||component.span>12))diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path:`${path}/span`,componentId,message:"Span must be a number from 1 through 12.",received:component.span});
        for(const property of ["title","subtitle","dataset","ariaLabel"] as const)if(component[property]!==undefined&&typeof component[property]!=="string")diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path:`${path}/${property}`,componentId,message:`${property} must be a string.`,received:component[property]});
        if(component.hidden!==undefined&&typeof component.hidden!=="boolean")diagnostics.push({code:"INVALID_PROPERTY_TYPE",severity:"error",path:`${path}/hidden`,componentId,message:"hidden must be a boolean.",received:component.hidden});
        if(type==="svg"||type==="svgMarkup"){const result=validateSvgComponentSchema(component,path,componentId);diagnostics.push(...result.diagnostics);totalSvgElements+=result.counts.elements;totalSvgAnimations+=result.counts.animated;}
        const aggregations=new Set(["sum","avg","min","max","count","distinctCount","countWhere","first"]);if(component.aggregation!==undefined&&!aggregations.has(String(component.aggregation)))diagnostics.push({code:"INVALID_ENUM_VALUE",severity:"error",path:`${path}/aggregation`,componentId,message:`Aggregation “${String(component.aggregation)}” is not supported.`,received:component.aggregation,suggestions:closestMatches(String(component.aggregation),aggregations)});
        const interaction=component.interaction;if(interaction!==undefined&&!object(interaction))diagnostics.push({code:"INVALID_INTERACTION",severity:"error",path:`${path}/interaction`,componentId,message:"Interaction must be an object."});else if(object(interaction)){const interactionProperties=new Set(["enabled","trigger","internalMode","internalScope","externalMode","field","operator","value","selectionMode","multiSelect","showSelector","clearOnSecondClick","target"]);for(const key of Object.keys(interaction))if(!interactionProperties.has(key))diagnostics.push({code:"INVALID_INTERACTION",severity:"error",path:`${path}/interaction/${key}`,componentId,message:`Interaction property “${key}” is not supported.`,received:key,suggestions:closestMatches(key,interactionProperties)});const enums:Record<string,string[]>={trigger:["auto","click","change"],internalMode:["none","highlight","filter"],internalScope:["self","others","all"],externalMode:["none","auto","selection","filter"],selectionMode:["replace","toggle","add"],operator:["=","!=",">",">=","<","<=","contains","in","between"]};for(const [property,values]of Object.entries(enums))if(interaction[property]!==undefined&&!values.includes(String(interaction[property])))diagnostics.push({code:"INVALID_ENUM_VALUE",severity:"error",path:`${path}/interaction/${property}`,componentId,message:`Interaction ${property} has unsupported value “${String(interaction[property])}”.`,received:interaction[property],suggestions:closestMatches(String(interaction[property]),values)});if(typeof interaction.target==="string")targets.push({target:interaction.target,path:`${path}/interaction/target`,componentId});}
        if(Array.isArray(component.targets))for(const [index,target]of component.targets.entries())if(typeof target==="string")targets.push({target,path:`${path}/targets/${index}`,componentId});
        if(Array.isArray(component.children))component.children.forEach((item,index)=>visit(item,`${path}/children/${index}`));if(Array.isArray(component.footer))component.footer.forEach((item,index)=>visit(item,`${path}/footer/${index}`));if(Array.isArray(component.tabs))component.tabs.forEach((tab,tabIndex)=>{if(object(tab)){const children=tab.children;if(Array.isArray(children))children.forEach((item,index)=>visit(item,`${path}/tabs/${tabIndex}/children/${index}`));}});if(Array.isArray(component.items)&&type==="accordion")component.items.forEach((item,itemIndex)=>{if(object(item)&&Array.isArray(item.children))item.children.forEach((child,index)=>visit(child,`${path}/items/${itemIndex}/children/${index}`));});if(object(component.chart))visit(component.chart,`${path}/chart`);};
    for(const key of ["components","toolbar","leftPanel","rightPanel"])if(Array.isArray(value[key]))value[key].forEach((component,index)=>visit(component,`/${key}/${index}`));
    if(totalSvgElements>SVG_LIMITS.maxElementsPerDashboard)diagnostics.push({code:"SVG_DASHBOARD_ELEMENT_LIMIT",severity:"error",path:"/components",message:`Dashboard SVG definitions exceed ${SVG_LIMITS.maxElementsPerDashboard} elements.`,received:totalSvgElements});
    if(totalSvgAnimations>SVG_LIMITS.maxAnimatedPerDashboard)diagnostics.push({code:"SVG_DASHBOARD_ANIMATION_LIMIT",severity:"error",path:"/components",message:`Dashboard SVG definitions exceed ${SVG_LIMITS.maxAnimatedPerDashboard} animated elements.`,received:totalSvgAnimations});
    for(const item of targets)if(!ids.has(item.target))diagnostics.push({code:"UNKNOWN_COMPONENT_TARGET",severity:"error",path:item.path,componentId:item.componentId,message:`Target component “${item.target}” does not exist.`,received:item.target,suggestions:closestMatches(item.target,ids.keys())});
    const errors=diagnostics.some(item=>item.severity==="error");return{valid:!errors,schema:errors?undefined:value as unknown as HyperPbiSchema,diagnostics};
}
