import {visitSpecificationComponents} from "../catalog/componentTraversal";
import {resolveDatasetSchemas} from "../data/datasetSchema";
import type {NormalizedData} from "../data/normalizeData";
import {specificationFieldReferences} from "../fields/specificationFieldReferences";
import {externalFilterTargetFor} from "../powerbi/externalFilters";
import type {HyperPbiSchema} from "./hyperpbiSchema";

const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==="object"&&!Array.isArray(value);
export function validateReferences(schema:HyperPbiSchema,data:NormalizedData):string[]{const errors:string[]=[];const schemas=resolveDatasetSchemas(data,schema.data?.datasets??{});errors.push(...schemas.diagnostics.map(item=>item.message));for(const occurrence of specificationFieldReferences(schema)){if(occurrence.path.startsWith("/data/")||occurrence.source==="service"||occurrence.source==="joined")continue;const scope=schemas.datasets.get(occurrence.datasetName)??schemas.datasets.get("powerbi");const field=scope?.fields[occurrence.reference];if(!field)errors.push(`${occurrence.path} references missing field “${occurrence.reference}” in dataset “${occurrence.datasetName}”.`);else if(occurrence.requirement==="numeric"&&field.dataType&&field.dataType!=="unknown"&&field.dataType!=="number")errors.push(`${occurrence.path} requires numeric field “${occurrence.reference}” in dataset “${occurrence.datasetName}”, but it is ${field.dataType}.`);}
    visitSpecificationComponents(schema,visit=>{const component=visit.component;const owner=typeof component.id==="string"?component.id:String(component.type);const scope=schemas.datasets.get(visit.datasetName)??schemas.datasets.get("powerbi");const interaction=object(component.interaction)?component.interaction:undefined;if(interaction?.enabled===true){const displayTypes=new Set(["kpi","metricGrid","infoCard","statusBadge","progressBar","alert","statList","detailPanel","gauge"]);if(displayTypes.has(String(component.type))){const metrics=Array.isArray(component.metrics)?component.metrics:[];const items=Array.isArray(component.items)?component.items:[];const groups=Array.isArray(component.groups)?component.groups:[];const usable=interaction.field||interaction.value!==undefined||component.field||component.measure||object(metrics[0])&&metrics[0].field||object(items[0])&&items[0].field||object(groups[0])&&Array.isArray(groups[0].fields)&&groups[0].fields.length;if(!usable)errors.push(`${owner} enables interaction but has no usable field, value, or row payload.`);}if(interaction.externalMode==="filter"){if(["table","matrix","map","scatterChart","advancedChart"].includes(String(component.type))&&!interaction.field)errors.push(`${owner} uses external filter mode and requires an explicit interaction.field.`);if(typeof interaction.field==="string"){const field=scope?.fields[interaction.field];if(field&&!externalFilterTargetFor(field)){const description=field.origin==="calculated-field"?"root calculated field":field.origin==="dataset-metric"?"dataset metric":field.origin==="dataset-derived"?"derived dataset field":field.kind==="measure"?"Power BI measure":"generated field";errors.push(`${owner} uses external filter mode with ${description} “${interaction.field}” in dataset “${visit.datasetName}”, which has no Power BI model-column target. Use selection/highlight or filter through a group-by source field.`);}}}}});
    const ignored:Record<string,string>={externalSelection:"Property externalSelection is not used. Use component.interaction.externalMode instead.",selectionTarget:"Property selectionTarget is obsolete and ignored only for HyperPBI 1.0 compatibility.",crossFilter:"Property crossFilter is not used in dashboard JSON. Use component.interaction and the Runtime Config global gate.",powerBISelection:"Property powerBISelection is not used. Use component.interaction.externalMode instead."};const scan=(value:unknown):void=>{if(Array.isArray(value)){value.forEach(scan);return;}if(!object(value))return;for(const [key,child]of Object.entries(value)){if(ignored[key])errors.push(ignored[key]);scan(child);}};scan(schema);return Array.from(new Set(errors));}
